---
- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install System Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  become: true
  apt: pkg={{ item }} state=latest
  with_items: "{{ server.packages }}"
  when: server.packages is defined

- name: Configure the timezone
  become: true
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: true
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  become: true
