
alias oec="$SCRIPTDIR/oe-checkout.sh"
alias oemig="$SCRIPTDIR/oe-migrate.sh"
alias oereset="$SCRIPTDIR/oe-reset.sh"
alias oeu="$SCRIPTDIR/oe-update.sh"
alias oefix="$SCRIPTDIR/oe-fix.sh"
alias oe-checkout="oec"
alias oe-migrate="oemig"
alias oe-reset="oereset"
alias oe-update="oeu"
alias oe-fix="oefix"

alias cdoe="cd $WROOT"
alias cded="cd $WROOT/protected/modules/eyedraw"
alias cdnb="cd $WROOT/protected/assets/newblue"
alias cdsample="cd $WROOT/protected/modules/sample/sql"
alias cdscripts="cd $SCRIPTDIR"
alias cdiolm="cd $WROOT/protected/javamodules/IOLMasterImport"
alias cdprotected="cd $WROOT/protected"

alias oelogson="tail $WROOT/protected/runtime/application.log -f &"
alias oelogsoff="kill -9 $(pgrep -f protected/runtime/application.log)"
