let name_on_btn= {'Examination Anterior Segment':'Anterior Segment'};
var lvl_1_to_section_id = {'Examination Anterior Segment' : 315};
var lvl_2_to_doodle_id = {
  'Adenoviral keratitis' : 'AdenoviralKeratitis',
  'Conjunctivitis' : 'Conjunctivitis',
  'Corneal epithelial defect' : 'CornealEpithelialDefect',
  'Corneal laceration' : 'CornealLaceration',
  'Corneal opacity' : 'CornealOpacity',
  'Corneal pigmentation' : 'CornealPigmentation',
  'Dendritic ulcer' : 'DendriticUlcer',
  'Marginal keratitis' : 'MarginalKeratitis',
  'Pingueculum' : 'Pingueculum',
  'Pterygium' : 'Pterygium',
  'SPEE' : 'SPEE',
  'Metallic foreign body' : 'MetallicForeignBody',

  'No description available for this doodle' : 'NONE',
  'Anterior chamber IOL' : 'ACIOL',
  'AC maintainer' : 'ACMaintainer',
  'Adnexal eye template' : 'AdnexalEye',
  'Angle grade' : 'AngleGrade',
  'Angle Grade East' : 'AngleGradeEast',
  'Angle Grade North' : 'AngleGradeNorth',
  'Angle Grade South' : 'AngleGradeSouth',
  'Angle Grade West' : 'AngleGradeWest',
  'Angle new vessels' : 'AngleNV',
  'Angle recession' : 'AngleRecession',
  'Anterior PVR' : 'AntPVR',
  'Anterior segment' : 'AntSeg',
  'Anterior synechiae' : 'AntSynech',
  'A pattern' : 'APattern',
  'Arcuate keratotomy' : 'ArcuateKeratotomy',
  'Arcuate scotoma' : 'ArcuateScotoma',
  'Arrow' : 'Arrow',
  'Biopsy site' : 'BiopsySite',
  'Trabeculectomy bleb' : 'Bleb',
  'Blot haemorrhage' : 'BlotHaemorrhage',
  'Buckle' : 'Buckle',
  'Buckle operation' : 'BuckleOperation',
  'Buckle suture' : 'BuckleSuture',
  'Busacca nodule' : 'BusaccaNodule',
  'Capsular Tension Ring' : 'CapsularTensionRing',
  'Double chandelier' : 'ChandelierDouble',
  'Chandelier' : 'ChandelierSingle',
  'Choroidal haemorrhage' : 'ChoroidalHaemorrhage',
  'Choroidal naevus' : 'ChoroidalNaevus',
  'Cilary injection' : 'CiliaryInjection',
  'Circinate retinopathy' : 'Circinate',
  'Circumferential buckle' : 'CircumferentialBuckle',
  'Choroidal new vessels' : 'CNV',
  'Conjunctival flap' : 'ConjunctivalFlap',
  'Conjunctival suture' : 'ConjunctivalSuture',
  'Corneal abrasion' : 'CornealAbrasion',
  'Removal of corneal epithelium' : 'CornealErosion',
  'Corneal graft' : 'CornealGraft',
  'Corneal inlay' : 'CornealInlay',
  'Corneal oedema' : 'CornealOedema',
  'Corneal scar' : 'CornealScar',
  'Corneal striae' : 'CornealStriae',
  'Corneal suture' : 'CornealSuture',
  'Cortical cataract' : 'CorticalCataract',
  'Cotton wool spot' : 'CottonWoolSpot',
  'Cryotherapy scar' : 'Cryo',
  'Cutter iridectomy' : 'CutterPI',
  'Cystoid macular oedema' : 'CystoidMacularOedema',
  'Diabetic new vessels' : 'DiabeticNV',
  'Dialysis' : 'Dialysis',
  'Disc haemorrhage' : 'DiscHaemorrhage',
  'Disc pallor' : 'DiscPallor',
  'Drainage retinotomy' : 'DrainageRetinotomy',
  'Drainage site' : 'DrainageSite',
  'Encircling band' : 'EncirclingBand',
  'Entry site break' : 'EntrySiteBreak',
  'Epiretinal membrane' : 'EpiretinalMembrane',
  'Episcleritis' : 'Episcleritis',
  'Fibrous proliferation' : 'FibrousProliferation',
  'Fibrovascular Scar' : 'FibrovascularScar',
  'Focal laser' : 'FocalLaser',
  'Freehand drawing' : 'Freehand',
  'Guttata' : 'Fuchs',
  'Fundus' : 'Fundus',
  'Geographic atrophy' : 'Geographic',
  'Gonioscopy' : 'Gonioscopy',
  'Giant retinal tear' : 'GRT',
  'Hard drusen' : 'HardDrusen',
  'Hard exudate' : 'HardExudate',
  'Hyphaema' : 'Hyphaema',
  'Hypopyon' : 'Hypopyon',
  'IatrogenicBreak' : 'IatrogenicBreak',
  'ILM peel' : 'ILMPeel',
  'Implantable Collamer Lens' : 'ICL',
  'Intraocular lens' : 'IOL',
  'Injection site' : 'InjectionSite',
  'Inner leaf break' : 'InnerLeafBreak',
  'Iris' : 'Iris',
  'Iris hook' : 'IrisHook',
  'Iris naevus' : 'IrisNaevus',
  'Intraretinal microvascular abnormalities' : 'IRMA',
  'Keratic precipitates' : 'KeraticPrecipitates',
  'Koeppe nodule' : 'KoeppeNodule',
  'Krukenberg spindle' : 'KrukenbergSpindle',
  'Label' : 'Label',
  'Circle of laser photocoagulation' : 'LaserCircle',
  'Laser demarcation' : 'LaserDemarcation',
  'LASIK flap' : 'LasikFlap',
  'Laser spot' : 'LaserSpot',
  'Lattice' : 'Lattice',
  'Lens' : 'Lens',
  'Limbal relaxing incision' : 'LimbalRelaxingIncision',
  'Macroaneurysm' : 'Macroaneurysm',
  'Macular dystrophy' : 'MacularDystrophy',
  'Macular grid laser' : 'MacularGrid',
  'Macular hole' : 'MacularHole',
  'Macular thickening' : 'MacularThickening',
  'Malyugin ring' : 'Malyugin',
  'Mattress suture' : 'MattressSuture',
  'Microaneurysm' : 'Microaneurysm',
  'Nerve fibre defect' : 'NerveFibreDefect',
  'Nuclear cataract' : 'NuclearCataract',
  'Optic cup' : 'OpticCup',
  'Optic disc' : 'OpticDisc',
  'Optic disc pit' : 'OpticDiscPit',
  'Orthoptic eye' : 'OrthopticEye',
  'Outer leaf break' : 'OuterLeafBreak',
  'Papilloedema' : 'Papilloedema',
  'Tube patch' : 'Patch',
  'Posterior chamber IOL' : 'PCIOL',
  'Peripapillary atrophy' : 'PeripapillaryAtrophy',
  'Peripheral retinectomy' : 'PeripheralRetinectomy',
  'Phako incision' : 'PhakoIncision',
  'Peripheral iridectomy' : 'PI',
  'Point in line' : 'PointInLine',
  'Posterior capsule' : 'PosteriorCapsule',
  'Posterior embryotoxon' : 'PosteriorEmbryotoxon',
  'Posterior pole' : 'PostPole',
  'Posterior subcapsular cataract' : 'PostSubcapCataract',
  'Posterior retinectomy' : 'PosteriorRetinectomy',
  'Posterior synechia' : 'PosteriorSynechia',
  'Pre-retinal haemorrhage' : 'PreRetinalHaemorrhage',
  'Panretinal photocoagulation' : 'PRP',
  'Panretinal photocoagulation (posterior pole)' : 'PRPPostPole',
  'Phototherapeutic keratectomy' : 'PTK',
  'Pupil' : 'Pupil',
  'Radial sponge' : 'RadialSponge',
  'Retinal artery occlusion' : 'RetinalArteryOcclusionPostPole',
  'Retinal haemorrhage' : 'RetinalHaemorrhage',
  'Retinal touch' : 'RetinalTouch',
  'Retinal vein occluson' : 'RetinalVeinOcclusionPostPole',
  'Retinoschisis' : 'Retinoschisis',
  'Radial keratotomy' : 'RK',
  'Round hole' : 'RoundHole',
  'RPE Atrophy' : 'RPEAtrophy',
  'RPE detachment' : 'RPEDetachment',
  'RPE Hypertrophy' : 'RPEHypertrophy',
  'RPE rip' : 'RPERip',
  'Rhegmatogenous retinal detachment' : 'RRD',
  'Rubeosis iridis' : 'Rubeosis',
  'Sector PRP' : 'SectorPRP',
  'Sector PRP (posterior pole)' : 'SectorPRPPostPole',
  'Scleral Incision' : 'ScleralIncision',
  'Sclerostomy' : 'Sclerostomy',
  'Sector iridectomy' : 'SectorIridectomy',
  'Shading' : 'Shading',
  'Side port' : 'SidePort',
  'Slider' : 'Slider',
  'Small incision lenticule extraction' : 'SMILE',
  'Star fold' : 'StarFold',
  'Subretinal fluid' : 'SubretinalFluid',
  'Subretinal PFCL' : 'SubretinalPFCL',
  'Supramid suture' : 'Supramid',
  'Swollen disc' : 'SwollenDisc',
  'Parafoveal telangiectasia' : 'Telangiectasis',
  'Trabectome' : 'Trabectome',
  'Trabeculectomy conjunctival incision' : 'TrabyConjIncision',
  'Trabeculectomy flap' : 'TrabyFlap',
  'Trabeculectomy suture' : 'TrabySuture',
  'Toric posterior chamber IOL' : 'ToricPCIOL',
  'Traction retinal detachment' : 'TractionRetinalDetachment',
  'Transillumination defect' : 'TransilluminationDefect',
  'Drainage tube' : 'Tube',
  'Tube extender' : 'TubeExtender',
  'Ligation suture' : 'TubeLigation',
  'Up drift' : 'UpDrift',
  'Up shoot' : 'UpShoot',
  'Traction ‘U’ tear' : 'UTear',
  'Vicryl suture' : 'Vicryl',
  'View obscured' : 'ViewObscured',
  'Vitreous opacity' : 'VitreousOpacity',
  'V pattern' : 'VPattern',
  'Crepitations' : 'Crepitations',
  'Stenosis' : 'Stenosis',
  'Wheeze' : 'Wheeze',
  'Pleural effusion' : 'Effusion',
  'Left coronary artery' : 'LeftCoronaryArtery',
  'Drug eluting stent' : 'DrugStent',
  'Metal stent' : 'MetalStent',
  'Coronary artery bypass' : 'Bypass',
  'Bruit' : 'Bruit',
  'Bruising' : 'Bruising',
  'Haematoma' : 'Haematoma',
}
