<?php
use Behat\Behat\Context\ClosuredContextInterface, Behat\Behat\Context\TranslatedContextInterface, Behat\Behat\Context\BehatContext, Behat\Behat\Exception\PendingException;
use Behat\Gherkin\Node\PyStringNode, Behat\Gherkin\Node\TableNode;
use Behat\MinkExtension\Context\MinkContext;

use Behat\Mink\Driver\Selenium2Driver;
use \SensioLabs\Behat\PageObjectExtension\Context\PageObjectContext;
use WebDriver\WebDriver;
class BiometryContext extends PageObjectContext
{
    public function __construct(array $parameters)
    {
    }

    /**
     * @Then /^I Save the Biometry$/
     */
    public function iSaveTheBiometry() {
        /**
         *
         * @var Biometry $biometry
         */
        $biometry = $this->getPage ( 'Biometry' );
        $biometry->saveBiometry();
    }


    /**
     * @Then /^I Check that no lenstype selection is not showing any error$/
     */
    public function iCheckThatNoLenstypeSelectionIsNotShowingAnyError()
    {
        /**
         *
         * @var Biometry $biometry
         */
        $biometry = $this->getPage('Biometry');
        $biometry->noLensErrorConfirm();
    }

    /**
     * @Then /^I Check that lenstype is not selected by default$/
     */
    public function iCheckThatLenstypeIsNotSelectedByDefault()
    {
        /**
         *
         * @var Biometry $biometry
         */
        $biometry = $this->getPage('Biometry');
        $biometry->noLensByDefaultConfirm();
    }

    /**
     * @Then /^I verify that the event is auto generated from DICOM files$/
     */
    public function iVerifyEventIsAutoGeneratedFromDicom(){
        /**
         *
         * @var Biometry $biometry
         */
        $biometry = $this->getPage('Biometry');
        $biometry->verifyEventIsAuto();
    }
}