<?php

class m111221_121341_add_new_created_user_id_and_date_fields_and_remove_old_user_id_fields extends CDbMigration
{
	public function up()
	{
		$this->addColumn('address','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('address_created_user_id_fk','address','created_user_id','user','id');
		$this->addColumn('address','created_date','datetime NOT NULL');
		$this->addColumn('authassignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('authassignment_created_user_id_fk','authassignment','created_user_id','user','id');
		$this->addColumn('authassignment','created_date','datetime NOT NULL');
		$this->addColumn('authitem','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('authitem_created_user_id_fk','authitem','created_user_id','user','id');
		$this->addColumn('authitem','created_date','datetime NOT NULL');
		$this->addColumn('authitemchild','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('authitemchild_created_user_id_fk','authitemchild','created_user_id','user','id');
		$this->addColumn('authitemchild','created_date','datetime NOT NULL');
		$this->addColumn('booking','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('booking_created_user_id_fk','booking','created_user_id','user','id');
		$this->addColumn('booking','created_date','datetime NOT NULL');
		$this->addColumn('cancellation_reason','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('cancellation_reason_created_user_id_fk','cancellation_reason','created_user_id','user','id');
		$this->addColumn('cancellation_reason','created_date','datetime NOT NULL');
		$this->renameColumn('cancelled_booking','user_id','created_user_id');
		$this->addForeignKey('cancelled_booking_created_user_id_fk','cancelled_booking','created_user_id','user','id');
		$this->addColumn('cancelled_booking','created_date','datetime NOT NULL');
		$this->renameColumn('cancelled_operation','user_id','created_user_id');
		$this->addForeignKey('cancelled_operation_created_user_id_fk','cancelled_operation','created_user_id','user','id');
		$this->addColumn('cancelled_operation','created_date','datetime NOT NULL');
		$this->addColumn('common_ophthalmic_disorder','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('common_ophthalmic_disorder_created_user_id_fk','common_ophthalmic_disorder','created_user_id','user','id');
		$this->addColumn('common_ophthalmic_disorder','created_date','datetime NOT NULL');
		$this->addColumn('common_systemic_disorder','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('common_systemic_disorder_created_user_id_fk','common_systemic_disorder','created_user_id','user','id');
		$this->addColumn('common_systemic_disorder','created_date','datetime NOT NULL');
		$this->addColumn('consultant','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('consultant_created_user_id_fk','consultant','created_user_id','user','id');
		$this->addColumn('consultant','created_date','datetime NOT NULL');
		$this->addColumn('contact','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('contact_created_user_id_fk','contact','created_user_id','user','id');
		$this->addColumn('contact','created_date','datetime NOT NULL');
		$this->addColumn('contact_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('contact_type_created_user_id_fk','contact_type','created_user_id','user','id');
		$this->addColumn('contact_type','created_date','datetime NOT NULL');
		$this->addColumn('country','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('country_created_user_id_fk','country','created_user_id','user','id');
		$this->addColumn('country','created_date','datetime NOT NULL');
		$this->addColumn('disorder','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('disorder_created_user_id_fk','disorder','created_user_id','user','id');
		$this->addColumn('disorder','created_date','datetime NOT NULL');
		$this->addColumn('element_allergies','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_allergies_created_user_id_fk','element_allergies','created_user_id','user','id');
		$this->addColumn('element_allergies','created_date','datetime NOT NULL');
		$this->addColumn('element_anterior_segment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_anterior_segment_created_user_id_fk','element_anterior_segment','created_user_id','user','id');
		$this->addColumn('element_anterior_segment','created_date','datetime NOT NULL');
		$this->addColumn('element_conclusion','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_conclusion_created_user_id_fk','element_conclusion','created_user_id','user','id');
		$this->addColumn('element_conclusion','created_date','datetime NOT NULL');
		$this->addColumn('element_cranial_nerves','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_cranial_nerves_created_user_id_fk','element_cranial_nerves','created_user_id','user','id');
		$this->addColumn('element_cranial_nerves','created_date','datetime NOT NULL');
		$this->addColumn('element_diabetes_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_diabetes_type_created_user_id_fk','element_diabetes_type','created_user_id','user','id');
		$this->addColumn('element_diabetes_type','created_date','datetime NOT NULL');
		$this->addColumn('element_diagnosis','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_diagnosis_created_user_id_fk','element_diagnosis','created_user_id','user','id');
		$this->addColumn('element_diagnosis','created_date','datetime NOT NULL');
		$this->addColumn('element_extraocular_movements','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_extraocular_movements_created_user_id_fk','element_extraocular_movements','created_user_id','user','id');
		$this->addColumn('element_extraocular_movements','created_date','datetime NOT NULL');
		$this->addColumn('element_foh','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_foh_created_user_id_fk','element_foh','created_user_id','user','id');
		$this->addColumn('element_foh','created_date','datetime NOT NULL');
		$this->addColumn('element_gonioscopy','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_gonioscopy_created_user_id_fk','element_gonioscopy','created_user_id','user','id');
		$this->addColumn('element_gonioscopy','created_date','datetime NOT NULL');
		$this->addColumn('element_history','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_history_created_user_id_fk','element_history','created_user_id','user','id');
		$this->addColumn('element_history','created_date','datetime NOT NULL');
		$this->addColumn('element_hpc','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_hpc_created_user_id_fk','element_hpc','created_user_id','user','id');
		$this->addColumn('element_hpc','created_date','datetime NOT NULL');
		$this->addColumn('element_intraocular_pressure','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_intraocular_pressure_created_user_id_fk','element_intraocular_pressure','created_user_id','user','id');
		$this->addColumn('element_intraocular_pressure','created_date','datetime NOT NULL');
		$this->addColumn('element_letterout','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_letterout_created_user_id_fk','element_letterout','created_user_id','user','id');
		$this->addColumn('element_letterout','created_date','datetime NOT NULL');
		$this->addColumn('element_medication','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_medication_created_user_id_fk','element_medication','created_user_id','user','id');
		$this->addColumn('element_medication','created_date','datetime NOT NULL');
		$this->addColumn('element_mini_refraction','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_mini_refraction_created_user_id_fk','element_mini_refraction','created_user_id','user','id');
		$this->addColumn('element_mini_refraction','created_date','datetime NOT NULL');
		$this->addColumn('element_nsc_grade','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_nsc_grade_created_user_id_fk','element_nsc_grade','created_user_id','user','id');
		$this->addColumn('element_nsc_grade','created_date','datetime NOT NULL');
		$this->dropForeignKey('user_fk','element_operation');
		$this->renameColumn('element_operation','user_id','created_user_id');
		$this->addForeignKey('element_operation_created_user_id_fk','element_operation','created_user_id','user','id');
		$this->addColumn('element_operation','created_date','datetime NOT NULL');
		$this->addColumn('element_orbital_examination','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_orbital_examination_created_user_id_fk','element_orbital_examination','created_user_id','user','id');
		$this->addColumn('element_orbital_examination','created_date','datetime NOT NULL');
		$this->addColumn('element_past_history','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_past_history_created_user_id_fk','element_past_history','created_user_id','user','id');
		$this->addColumn('element_past_history','created_date','datetime NOT NULL');
		$this->addColumn('element_pmh','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_pmh_created_user_id_fk','element_pmh','created_user_id','user','id');
		$this->addColumn('element_pmh','created_date','datetime NOT NULL');
		$this->addColumn('element_poh','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_poh_created_user_id_fk','element_poh','created_user_id','user','id');
		$this->addColumn('element_poh','created_date','datetime NOT NULL');
		$this->addColumn('element_posterior_segment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_posterior_segment_created_user_id_fk','element_posterior_segment','created_user_id','user','id');
		$this->addColumn('element_posterior_segment','created_date','datetime NOT NULL');
		$this->addColumn('element_referred_from_screening','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_referred_from_screening_created_user_id_fk','element_referred_from_screening','created_user_id','user','id');
		$this->addColumn('element_referred_from_screening','created_date','datetime NOT NULL');
		$this->addColumn('element_registered_blind','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_registered_blind_created_user_id_fk','element_registered_blind','created_user_id','user','id');
		$this->addColumn('element_registered_blind','created_date','datetime NOT NULL');
		$this->addColumn('element_social_history','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_social_history_created_user_id_fk','element_social_history','created_user_id','user','id');
		$this->addColumn('element_social_history','created_date','datetime NOT NULL');
		$this->addColumn('element_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_type_created_user_id_fk','element_type','created_user_id','user','id');
		$this->addColumn('element_type','created_date','datetime NOT NULL');
		$this->addColumn('element_visual_acuity','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_visual_acuity_created_user_id_fk','element_visual_acuity','created_user_id','user','id');
		$this->addColumn('element_visual_acuity','created_date','datetime NOT NULL');
		$this->addColumn('element_visual_fields','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_visual_fields_created_user_id_fk','element_visual_fields','created_user_id','user','id');
		$this->addColumn('element_visual_fields','created_date','datetime NOT NULL');
		$this->addColumn('element_visual_function','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('element_visual_function_created_user_id_fk','element_visual_function','created_user_id','user','id');
		$this->addColumn('element_visual_function','created_date','datetime NOT NULL');
		$this->addColumn('episode','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('episode_created_user_id_fk','episode','created_user_id','user','id');
		$this->addColumn('episode','created_date','datetime NOT NULL');
		$this->dropForeignKey('event_2','event');
		$this->renameColumn('event','user_id','created_user_id');
		$this->addForeignKey('event_created_user_id_fk','event','created_user_id','user','id');
		$this->addColumn('event','created_date','datetime NOT NULL');
		$this->addColumn('event_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('event_type_created_user_id_fk','event_type','created_user_id','user','id');
		$this->addColumn('event_type','created_date','datetime NOT NULL');
		$this->addColumn('firm','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('firm_created_user_id_fk','firm','created_user_id','user','id');
		$this->addColumn('firm','created_date','datetime NOT NULL');
		$this->addColumn('firm_user_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('firm_user_assignment_created_user_id_fk','firm_user_assignment','created_user_id','user','id');
		$this->addColumn('firm_user_assignment','created_date','datetime NOT NULL');
		$this->addColumn('gp','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('gp_created_user_id_fk','gp','created_user_id','user','id');
		$this->addColumn('gp','created_date','datetime NOT NULL');
		$this->addColumn('letter_template','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('letter_template_created_user_id_fk','letter_template','created_user_id','user','id');
		$this->addColumn('letter_template','created_date','datetime NOT NULL');
		$this->addColumn('manual_contact','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('manual_contact_created_user_id_fk','manual_contact','created_user_id','user','id');
		$this->addColumn('manual_contact','created_date','datetime NOT NULL');
		$this->addColumn('nsc_grade','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('nsc_grade_created_user_id_fk','nsc_grade','created_user_id','user','id');
		$this->addColumn('nsc_grade','created_date','datetime NOT NULL');
		$this->addColumn('opcs_code','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('opcs_code_created_user_id_fk','opcs_code','created_user_id','user','id');
		$this->addColumn('opcs_code','created_date','datetime NOT NULL');
		$this->addColumn('operation_procedure_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('operation_procedure_assignment_created_user_id_fk','operation_procedure_assignment','created_user_id','user','id');
		$this->addColumn('operation_procedure_assignment','created_date','datetime NOT NULL');
		$this->addColumn('patient','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('patient_created_user_id_fk','patient','created_user_id','user','id');
		$this->addColumn('patient','created_date','datetime NOT NULL');
		$this->addColumn('patient_contact_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('patient_contact_assignment_created_user_id_fk','patient_contact_assignment','created_user_id','user','id');
		$this->addColumn('patient_contact_assignment','created_date','datetime NOT NULL');
		$this->addColumn('phrase','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('phrase_created_user_id_fk','phrase','created_user_id','user','id');
		$this->addColumn('phrase','created_date','datetime NOT NULL');
		$this->addColumn('phrase_by_firm','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('phrase_by_firm_created_user_id_fk','phrase_by_firm','created_user_id','user','id');
		$this->addColumn('phrase_by_firm','created_date','datetime NOT NULL');
		$this->addColumn('phrase_by_specialty','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('phrase_by_specialty_created_user_id_fk','phrase_by_specialty','created_user_id','user','id');
		$this->addColumn('phrase_by_specialty','created_date','datetime NOT NULL');
		$this->addColumn('phrase_name','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('phrase_name_created_user_id_fk','phrase_name','created_user_id','user','id');
		$this->addColumn('phrase_name','created_date','datetime NOT NULL');
		$this->addColumn('possible_element_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('possible_element_type_created_user_id_fk','possible_element_type','created_user_id','user','id');
		$this->addColumn('possible_element_type','created_date','datetime NOT NULL');
		$this->addColumn('proc','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('proc_created_user_id_fk','proc','created_user_id','user','id');
		$this->addColumn('proc','created_date','datetime NOT NULL');
		$this->addColumn('proc_opcs_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('proc_opcs_assignment_created_user_id_fk','proc_opcs_assignment','created_user_id','user','id');
		$this->addColumn('proc_opcs_assignment','created_date','datetime NOT NULL');
		$this->addColumn('proc_specialty_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('proc_specialty_assignment_created_user_id_fk','proc_specialty_assignment','created_user_id','user','id');
		$this->addColumn('proc_specialty_assignment','created_date','datetime NOT NULL');
		$this->addColumn('proc_specialty_subsection_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('proc_specialty_subsection_assignment_created_user_id_fk','proc_specialty_subsection_assignment','created_user_id','user','id');
		$this->addColumn('proc_specialty_subsection_assignment','created_date','datetime NOT NULL');
		$this->addColumn('referral','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('referral_created_user_id_fk','referral','created_user_id','user','id');
		$this->addColumn('referral','created_date','datetime NOT NULL');
		$this->addColumn('referral_episode_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('referral_episode_assignment_created_user_id_fk','referral_episode_assignment','created_user_id','user','id');
		$this->addColumn('referral_episode_assignment','created_date','datetime NOT NULL');
		$this->addColumn('section','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('section_created_user_id_fk','section','created_user_id','user','id');
		$this->addColumn('section','created_date','datetime NOT NULL');
		$this->addColumn('section_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('section_type_created_user_id_fk','section_type','created_user_id','user','id');
		$this->addColumn('section_type','created_date','datetime NOT NULL');
		$this->addColumn('sequence','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('sequence_created_user_id_fk','sequence','created_user_id','user','id');
		$this->addColumn('sequence','created_date','datetime NOT NULL');
		$this->addColumn('sequence_firm_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('sequence_firm_assignment_created_user_id_fk','sequence_firm_assignment','created_user_id','user','id');
		$this->addColumn('sequence_firm_assignment','created_date','datetime NOT NULL');
		$this->addColumn('service','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('service_created_user_id_fk','service','created_user_id','user','id');
		$this->addColumn('service','created_date','datetime NOT NULL');
		$this->addColumn('service_specialty_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('service_specialty_assignment_created_user_id_fk','service_specialty_assignment','created_user_id','user','id');
		$this->addColumn('service_specialty_assignment','created_date','datetime NOT NULL');
		$this->addColumn('session','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('session_created_user_id_fk','session','created_user_id','user','id');
		$this->addColumn('session','created_date','datetime NOT NULL');
		$this->addColumn('site','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('site_created_user_id_fk','site','created_user_id','user','id');
		$this->addColumn('site','created_date','datetime NOT NULL');
		$this->addColumn('site_element_type','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('site_element_type_created_user_id_fk','site_element_type','created_user_id','user','id');
		$this->addColumn('site_element_type','created_date','datetime NOT NULL');
		$this->addColumn('specialty','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('specialty_created_user_id_fk','specialty','created_user_id','user','id');
		$this->addColumn('specialty','created_date','datetime NOT NULL');
		$this->addColumn('specialty_subsection','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('specialty_subsection_created_user_id_fk','specialty_subsection','created_user_id','user','id');
		$this->addColumn('specialty_subsection','created_date','datetime NOT NULL');
		$this->addColumn('tbl_migration','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('tbl_migration_created_user_id_fk','tbl_migration','created_user_id','user','id');
		$this->addColumn('tbl_migration','created_date','datetime NOT NULL');
		$this->addColumn('theatre','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('theatre_created_user_id_fk','theatre','created_user_id','user','id');
		$this->addColumn('theatre','created_date','datetime NOT NULL');
		$this->addColumn('theatre_ward_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('theatre_ward_assignment_created_user_id_fk','theatre_ward_assignment','created_user_id','user','id');
		$this->addColumn('theatre_ward_assignment','created_date','datetime NOT NULL');
		$this->addColumn('user','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_created_user_id_fk','user','created_user_id','user','id');
		$this->addColumn('user','created_date','datetime NOT NULL');
		$this->addColumn('user_contact_assignment','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_contact_assignment_created_user_id_fk','user_contact_assignment','created_user_id','user','id');
		$this->addColumn('user_contact_assignment','created_date','datetime NOT NULL');
		$this->addColumn('user_firm_rights','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_firm_rights_created_user_id_fk','user_firm_rights','created_user_id','user','id');
		$this->addColumn('user_firm_rights','created_date','datetime NOT NULL');
		$this->addColumn('user_service_rights','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_service_rights_created_user_id_fk','user_service_rights','created_user_id','user','id');
		$this->addColumn('user_service_rights','created_date','datetime NOT NULL');
		$this->addColumn('user_session','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_session_created_user_id_fk','user_session','created_user_id','user','id');
		$this->addColumn('user_session','created_date','datetime NOT NULL');
		$this->addColumn('ward','created_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('ward_created_user_id_fk','ward','created_user_id','user','id');
		$this->addColumn('ward','created_date','datetime NOT NULL');
	}

	public function down()
	{
		$this->dropForeignKey('address_created_user_id_fk','address');
		$this->dropColumn('address','created_user_id');
		$this->dropColumn('address','created_date');
		$this->dropForeignKey('authassignment_created_user_id_fk','authassignment');
		$this->dropColumn('authassignment','created_user_id');
		$this->dropColumn('authassignment','created_date');
		$this->dropForeignKey('authitem_created_user_id_fk','authitem');
		$this->dropColumn('authitem','created_user_id');
		$this->dropColumn('authitem','created_date');
		$this->dropForeignKey('authitemchild_created_user_id_fk','authitemchild');
		$this->dropColumn('authitemchild','created_user_id');
		$this->dropColumn('authitemchild','created_date');
		$this->dropForeignKey('booking_created_user_id_fk','booking');
		$this->dropColumn('booking','created_user_id');
		$this->dropColumn('booking','created_date');
		$this->dropForeignKey('cancellation_reason_created_user_id_fk','cancellation_reason');
		$this->dropColumn('cancellation_reason','created_user_id');
		$this->dropColumn('cancellation_reason','created_date');
		$this->dropForeignKey('cancelled_booking_created_user_id_fk','cancelled_booking');
		$this->dropColumn('cancelled_booking','created_user_id');
		$this->dropColumn('cancelled_booking','created_date');
		$this->addColumn('cancelled_booking','user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->dropForeignKey('cancelled_operation_created_user_id_fk','cancelled_operation');
		$this->dropColumn('cancelled_operation','created_user_id');
		$this->dropColumn('cancelled_operation','created_date');
		$this->addColumn('cancelled_operation','user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->dropForeignKey('common_ophthalmic_disorder_created_user_id_fk','common_ophthalmic_disorder');
		$this->dropColumn('common_ophthalmic_disorder','created_user_id');
		$this->dropColumn('common_ophthalmic_disorder','created_date');
		$this->dropForeignKey('common_systemic_disorder_created_user_id_fk','common_systemic_disorder');
		$this->dropColumn('common_systemic_disorder','created_user_id');
		$this->dropColumn('common_systemic_disorder','created_date');
		$this->dropForeignKey('consultant_created_user_id_fk','consultant');
		$this->dropColumn('consultant','created_user_id');
		$this->dropColumn('consultant','created_date');
		$this->dropForeignKey('contact_created_user_id_fk','contact');
		$this->dropColumn('contact','created_user_id');
		$this->dropColumn('contact','created_date');
		$this->dropForeignKey('contact_type_created_user_id_fk','contact_type');
		$this->dropColumn('contact_type','created_user_id');
		$this->dropColumn('contact_type','created_date');
		$this->dropForeignKey('country_created_user_id_fk','country');
		$this->dropColumn('country','created_user_id');
		$this->dropColumn('country','created_date');
		$this->dropForeignKey('disorder_created_user_id_fk','disorder');
		$this->dropColumn('disorder','created_user_id');
		$this->dropColumn('disorder','created_date');
		$this->dropForeignKey('element_allergies_created_user_id_fk','element_allergies');
		$this->dropColumn('element_allergies','created_user_id');
		$this->dropColumn('element_allergies','created_date');
		$this->dropForeignKey('element_anterior_segment_created_user_id_fk','element_anterior_segment');
		$this->dropColumn('element_anterior_segment','created_user_id');
		$this->dropColumn('element_anterior_segment','created_date');
		$this->dropForeignKey('element_conclusion_created_user_id_fk','element_conclusion');
		$this->dropColumn('element_conclusion','created_user_id');
		$this->dropColumn('element_conclusion','created_date');
		$this->dropForeignKey('element_cranial_nerves_created_user_id_fk','element_cranial_nerves');
		$this->dropColumn('element_cranial_nerves','created_user_id');
		$this->dropColumn('element_cranial_nerves','created_date');
		$this->dropForeignKey('element_diabetes_type_created_user_id_fk','element_diabetes_type');
		$this->dropColumn('element_diabetes_type','created_user_id');
		$this->dropColumn('element_diabetes_type','created_date');
		$this->dropForeignKey('element_diagnosis_created_user_id_fk','element_diagnosis');
		$this->dropColumn('element_diagnosis','created_user_id');
		$this->dropColumn('element_diagnosis','created_date');
		$this->dropForeignKey('element_extraocular_movements_created_user_id_fk','element_extraocular_movements');
		$this->dropColumn('element_extraocular_movements','created_user_id');
		$this->dropColumn('element_extraocular_movements','created_date');
		$this->dropForeignKey('element_foh_created_user_id_fk','element_foh');
		$this->dropColumn('element_foh','created_user_id');
		$this->dropColumn('element_foh','created_date');
		$this->dropForeignKey('element_gonioscopy_created_user_id_fk','element_gonioscopy');
		$this->dropColumn('element_gonioscopy','created_user_id');
		$this->dropColumn('element_gonioscopy','created_date');
		$this->dropForeignKey('element_history_created_user_id_fk','element_history');
		$this->dropColumn('element_history','created_user_id');
		$this->dropColumn('element_history','created_date');
		$this->dropForeignKey('element_hpc_created_user_id_fk','element_hpc');
		$this->dropColumn('element_hpc','created_user_id');
		$this->dropColumn('element_hpc','created_date');
		$this->dropForeignKey('element_intraocular_pressure_created_user_id_fk','element_intraocular_pressure');
		$this->dropColumn('element_intraocular_pressure','created_user_id');
		$this->dropColumn('element_intraocular_pressure','created_date');
		$this->dropForeignKey('element_letterout_created_user_id_fk','element_letterout');
		$this->dropColumn('element_letterout','created_user_id');
		$this->dropColumn('element_letterout','created_date');
		$this->dropForeignKey('element_medication_created_user_id_fk','element_medication');
		$this->dropColumn('element_medication','created_user_id');
		$this->dropColumn('element_medication','created_date');
		$this->dropForeignKey('element_mini_refraction_created_user_id_fk','element_mini_refraction');
		$this->dropColumn('element_mini_refraction','created_user_id');
		$this->dropColumn('element_mini_refraction','created_date');
		$this->dropForeignKey('element_nsc_grade_created_user_id_fk','element_nsc_grade');
		$this->dropColumn('element_nsc_grade','created_user_id');
		$this->dropColumn('element_nsc_grade','created_date');
		$this->dropForeignKey('element_operation_created_user_id_fk','element_operation');
		$this->dropColumn('element_operation','created_user_id');
		$this->dropColumn('element_operation','created_date');
		$this->addColumn('element_operation','user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('user_fk','element_operation','user_id','user','id');
		$this->dropForeignKey('element_orbital_examination_created_user_id_fk','element_orbital_examination');
		$this->dropColumn('element_orbital_examination','created_user_id');
		$this->dropColumn('element_orbital_examination','created_date');
		$this->dropForeignKey('element_past_history_created_user_id_fk','element_past_history');
		$this->dropColumn('element_past_history','created_user_id');
		$this->dropColumn('element_past_history','created_date');
		$this->dropForeignKey('element_pmh_created_user_id_fk','element_pmh');
		$this->dropColumn('element_pmh','created_user_id');
		$this->dropColumn('element_pmh','created_date');
		$this->dropForeignKey('element_poh_created_user_id_fk','element_poh');
		$this->dropColumn('element_poh','created_user_id');
		$this->dropColumn('element_poh','created_date');
		$this->dropForeignKey('element_posterior_segment_created_user_id_fk','element_posterior_segment');
		$this->dropColumn('element_posterior_segment','created_user_id');
		$this->dropColumn('element_posterior_segment','created_date');
		$this->dropForeignKey('element_referred_from_screening_created_user_id_fk','element_referred_from_screening');
		$this->dropColumn('element_referred_from_screening','created_user_id');
		$this->dropColumn('element_referred_from_screening','created_date');
		$this->dropForeignKey('element_registered_blind_created_user_id_fk','element_registered_blind');
		$this->dropColumn('element_registered_blind','created_user_id');
		$this->dropColumn('element_registered_blind','created_date');
		$this->dropForeignKey('element_social_history_created_user_id_fk','element_social_history');
		$this->dropColumn('element_social_history','created_user_id');
		$this->dropColumn('element_social_history','created_date');
		$this->dropForeignKey('element_type_created_user_id_fk','element_type');
		$this->dropColumn('element_type','created_user_id');
		$this->dropColumn('element_type','created_date');
		$this->dropForeignKey('element_visual_acuity_created_user_id_fk','element_visual_acuity');
		$this->dropColumn('element_visual_acuity','created_user_id');
		$this->dropColumn('element_visual_acuity','created_date');
		$this->dropForeignKey('element_visual_fields_created_user_id_fk','element_visual_fields');
		$this->dropColumn('element_visual_fields','created_user_id');
		$this->dropColumn('element_visual_fields','created_date');
		$this->dropForeignKey('element_visual_function_created_user_id_fk','element_visual_function');
		$this->dropColumn('element_visual_function','created_user_id');
		$this->dropColumn('element_visual_function','created_date');
		$this->dropForeignKey('episode_created_user_id_fk','episode');
		$this->dropColumn('episode','created_user_id');
		$this->dropColumn('episode','created_date');
		$this->dropForeignKey('event_created_user_id_fk','event');
		$this->dropColumn('event','created_user_id');
		$this->dropColumn('event','created_date');
		$this->addColumn('event','user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addForeignKey('event_2','event','user_id','user','id');
		$this->dropForeignKey('event_type_created_user_id_fk','event_type');
		$this->dropColumn('event_type','created_user_id');
		$this->dropColumn('event_type','created_date');
		$this->dropForeignKey('firm_created_user_id_fk','firm');
		$this->dropColumn('firm','created_user_id');
		$this->dropColumn('firm','created_date');
		$this->dropForeignKey('firm_user_assignment_created_user_id_fk','firm_user_assignment');
		$this->dropColumn('firm_user_assignment','created_user_id');
		$this->dropColumn('firm_user_assignment','created_date');
		$this->dropForeignKey('gp_created_user_id_fk','gp');
		$this->dropColumn('gp','created_user_id');
		$this->dropColumn('gp','created_date');
		$this->dropForeignKey('letter_template_created_user_id_fk','letter_template');
		$this->dropColumn('letter_template','created_user_id');
		$this->dropColumn('letter_template','created_date');
		$this->dropForeignKey('manual_contact_created_user_id_fk','manual_contact');
		$this->dropColumn('manual_contact','created_user_id');
		$this->dropColumn('manual_contact','created_date');
		$this->dropForeignKey('nsc_grade_created_user_id_fk','nsc_grade');
		$this->dropColumn('nsc_grade','created_user_id');
		$this->dropColumn('nsc_grade','created_date');
		$this->dropForeignKey('opcs_code_created_user_id_fk','opcs_code');
		$this->dropColumn('opcs_code','created_user_id');
		$this->dropColumn('opcs_code','created_date');
		$this->dropForeignKey('operation_procedure_assignment_created_user_id_fk','operation_procedure_assignment');
		$this->dropColumn('operation_procedure_assignment','created_user_id');
		$this->dropColumn('operation_procedure_assignment','created_date');
		$this->dropForeignKey('patient_created_user_id_fk','patient');
		$this->dropColumn('patient','created_user_id');
		$this->dropColumn('patient','created_date');
		$this->dropForeignKey('patient_contact_assignment_created_user_id_fk','patient_contact_assignment');
		$this->dropColumn('patient_contact_assignment','created_user_id');
		$this->dropColumn('patient_contact_assignment','created_date');
		$this->dropForeignKey('phrase_created_user_id_fk','phrase');
		$this->dropColumn('phrase','created_user_id');
		$this->dropColumn('phrase','created_date');
		$this->dropForeignKey('phrase_by_firm_created_user_id_fk','phrase_by_firm');
		$this->dropColumn('phrase_by_firm','created_user_id');
		$this->dropColumn('phrase_by_firm','created_date');
		$this->dropForeignKey('phrase_by_specialty_created_user_id_fk','phrase_by_specialty');
		$this->dropColumn('phrase_by_specialty','created_user_id');
		$this->dropColumn('phrase_by_specialty','created_date');
		$this->dropForeignKey('phrase_name_created_user_id_fk','phrase_name');
		$this->dropColumn('phrase_name','created_user_id');
		$this->dropColumn('phrase_name','created_date');
		$this->dropForeignKey('possible_element_type_created_user_id_fk','possible_element_type');
		$this->dropColumn('possible_element_type','created_user_id');
		$this->dropColumn('possible_element_type','created_date');
		$this->dropForeignKey('proc_created_user_id_fk','proc');
		$this->dropColumn('proc','created_user_id');
		$this->dropColumn('proc','created_date');
		$this->dropForeignKey('proc_opcs_assignment_created_user_id_fk','proc_opcs_assignment');
		$this->dropColumn('proc_opcs_assignment','created_user_id');
		$this->dropColumn('proc_opcs_assignment','created_date');
		$this->dropForeignKey('proc_specialty_assignment_created_user_id_fk','proc_specialty_assignment');
		$this->dropColumn('proc_specialty_assignment','created_user_id');
		$this->dropColumn('proc_specialty_assignment','created_date');
		$this->dropForeignKey('proc_specialty_subsection_assignment_created_user_id_fk','proc_specialty_subsection_assignment');
		$this->dropColumn('proc_specialty_subsection_assignment','created_user_id');
		$this->dropColumn('proc_specialty_subsection_assignment','created_date');
		$this->dropForeignKey('referral_created_user_id_fk','referral');
		$this->dropColumn('referral','created_user_id');
		$this->dropColumn('referral','created_date');
		$this->dropForeignKey('referral_episode_assignment_created_user_id_fk','referral_episode_assignment');
		$this->dropColumn('referral_episode_assignment','created_user_id');
		$this->dropColumn('referral_episode_assignment','created_date');
		$this->dropForeignKey('section_created_user_id_fk','section');
		$this->dropColumn('section','created_user_id');
		$this->dropColumn('section','created_date');
		$this->dropForeignKey('section_type_created_user_id_fk','section_type');
		$this->dropColumn('section_type','created_user_id');
		$this->dropColumn('section_type','created_date');
		$this->dropForeignKey('sequence_created_user_id_fk','sequence');
		$this->dropColumn('sequence','created_user_id');
		$this->dropColumn('sequence','created_date');
		$this->dropForeignKey('sequence_firm_assignment_created_user_id_fk','sequence_firm_assignment');
		$this->dropColumn('sequence_firm_assignment','created_user_id');
		$this->dropColumn('sequence_firm_assignment','created_date');
		$this->dropForeignKey('service_created_user_id_fk','service');
		$this->dropColumn('service','created_user_id');
		$this->dropColumn('service','created_date');
		$this->dropForeignKey('service_specialty_assignment_created_user_id_fk','service_specialty_assignment');
		$this->dropColumn('service_specialty_assignment','created_user_id');
		$this->dropColumn('service_specialty_assignment','created_date');
		$this->dropForeignKey('session_created_user_id_fk','session');
		$this->dropColumn('session','created_user_id');
		$this->dropColumn('session','created_date');
		$this->dropForeignKey('site_created_user_id_fk','site');
		$this->dropColumn('site','created_user_id');
		$this->dropColumn('site','created_date');
		$this->dropForeignKey('site_element_type_created_user_id_fk','site_element_type');
		$this->dropColumn('site_element_type','created_user_id');
		$this->dropColumn('site_element_type','created_date');
		$this->dropForeignKey('specialty_created_user_id_fk','specialty');
		$this->dropColumn('specialty','created_user_id');
		$this->dropColumn('specialty','created_date');
		$this->dropForeignKey('specialty_subsection_created_user_id_fk','specialty_subsection');
		$this->dropColumn('specialty_subsection','created_user_id');
		$this->dropColumn('specialty_subsection','created_date');
		$this->dropForeignKey('tbl_migration_created_user_id_fk','tbl_migration');
		$this->dropColumn('tbl_migration','created_user_id');
		$this->dropColumn('tbl_migration','created_date');
		$this->dropForeignKey('theatre_created_user_id_fk','theatre');
		$this->dropColumn('theatre','created_user_id');
		$this->dropColumn('theatre','created_date');
		$this->dropForeignKey('theatre_ward_assignment_created_user_id_fk','theatre_ward_assignment');
		$this->dropColumn('theatre_ward_assignment','created_user_id');
		$this->dropColumn('theatre_ward_assignment','created_date');
		$this->dropForeignKey('user_created_user_id_fk','user');
		$this->dropColumn('user','created_user_id');
		$this->dropColumn('user','created_date');
		$this->dropForeignKey('user_contact_assignment_created_user_id_fk','user_contact_assignment');
		$this->dropColumn('user_contact_assignment','created_user_id');
		$this->dropColumn('user_contact_assignment','created_date');
		$this->dropForeignKey('user_firm_rights_created_user_id_fk','user_firm_rights');
		$this->dropColumn('user_firm_rights','created_user_id');
		$this->dropColumn('user_firm_rights','created_date');
		$this->dropForeignKey('user_service_rights_created_user_id_fk','user_service_rights');
		$this->dropColumn('user_service_rights','created_user_id');
		$this->dropColumn('user_service_rights','created_date');
		$this->dropForeignKey('user_session_created_user_id_fk','user_session');
		$this->dropColumn('user_session','created_user_id');
		$this->dropColumn('user_session','created_date');
		$this->dropForeignKey('ward_created_user_id_fk','ward');
		$this->dropColumn('ward','created_user_id');
		$this->dropColumn('ward','created_date');
	}
}
?>
