<?php

class m111220_143310_last_modified_user_id_and_date extends CDbMigration
{
	public function up()
	{
		$this->addColumn('address','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('address','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('address_last_modified_user_id_fk','address','last_modified_user_id','user','id');
		$this->addColumn('authassignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('authassignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('authassignment_last_modified_user_id_fk','authassignment','last_modified_user_id','user','id');
		$this->addColumn('authitem','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('authitem','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('authitem_last_modified_user_id_fk','authitem','last_modified_user_id','user','id');
		$this->addColumn('authitemchild','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('authitemchild','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('authitemchild_last_modified_user_id_fk','authitemchild','last_modified_user_id','user','id');
		$this->addColumn('booking','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('booking','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('booking_last_modified_user_id_fk','booking','last_modified_user_id','user','id');
		$this->addColumn('cancellation_reason','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('cancellation_reason','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('cancellation_reason_last_modified_user_id_fk','cancellation_reason','last_modified_user_id','user','id');
		$this->addColumn('cancelled_booking','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('cancelled_booking','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('cancelled_booking_last_modified_user_id_fk','cancelled_booking','last_modified_user_id','user','id');
		$this->addColumn('cancelled_operation','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('cancelled_operation','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('cancelled_operation_last_modified_user_id_fk','cancelled_operation','last_modified_user_id','user','id');
		$this->addColumn('common_ophthalmic_disorder','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('common_ophthalmic_disorder','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('common_ophthalmic_disorder_last_modified_user_id_fk','common_ophthalmic_disorder','last_modified_user_id','user','id');
		$this->addColumn('common_systemic_disorder','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('common_systemic_disorder','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('common_systemic_disorder_last_modified_user_id_fk','common_systemic_disorder','last_modified_user_id','user','id');
		$this->addColumn('consultant','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('consultant','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('consultant_last_modified_user_id_fk','consultant','last_modified_user_id','user','id');
		$this->addColumn('contact','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('contact','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('contact_last_modified_user_id_fk','contact','last_modified_user_id','user','id');
		$this->addColumn('contact_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('contact_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('contact_type_last_modified_user_id_fk','contact_type','last_modified_user_id','user','id');
		$this->addColumn('country','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('country','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('country_last_modified_user_id_fk','country','last_modified_user_id','user','id');
		$this->addColumn('disorder','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('disorder','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('disorder_last_modified_user_id_fk','disorder','last_modified_user_id','user','id');
		$this->addColumn('element_allergies','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_allergies','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_allergies_last_modified_user_id_fk','element_allergies','last_modified_user_id','user','id');
		$this->addColumn('element_anterior_segment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_anterior_segment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_anterior_segment_last_modified_user_id_fk','element_anterior_segment','last_modified_user_id','user','id');
		$this->addColumn('element_conclusion','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_conclusion','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_conclusion_last_modified_user_id_fk','element_conclusion','last_modified_user_id','user','id');
		$this->addColumn('element_cranial_nerves','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_cranial_nerves','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_cranial_nerves_last_modified_user_id_fk','element_cranial_nerves','last_modified_user_id','user','id');
		$this->addColumn('element_diabetes_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_diabetes_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_diabetes_type_last_modified_user_id_fk','element_diabetes_type','last_modified_user_id','user','id');
		$this->addColumn('element_diagnosis','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_diagnosis','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_diagnosis_last_modified_user_id_fk','element_diagnosis','last_modified_user_id','user','id');
		$this->addColumn('element_extraocular_movements','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_extraocular_movements','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_extraocular_movements_last_modified_user_id_fk','element_extraocular_movements','last_modified_user_id','user','id');
		$this->addColumn('element_foh','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_foh','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_foh_last_modified_user_id_fk','element_foh','last_modified_user_id','user','id');
		$this->addColumn('element_gonioscopy','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_gonioscopy','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_gonioscopy_last_modified_user_id_fk','element_gonioscopy','last_modified_user_id','user','id');
		$this->addColumn('element_history','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_history','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_history_last_modified_user_id_fk','element_history','last_modified_user_id','user','id');
		$this->addColumn('element_hpc','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_hpc','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_hpc_last_modified_user_id_fk','element_hpc','last_modified_user_id','user','id');
		$this->addColumn('element_intraocular_pressure','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_intraocular_pressure','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_intraocular_pressure_last_modified_user_id_fk','element_intraocular_pressure','last_modified_user_id','user','id');
		$this->addColumn('element_letterout','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_letterout','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_letterout_last_modified_user_id_fk','element_letterout','last_modified_user_id','user','id');
		$this->addColumn('element_medication','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_medication','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_medication_last_modified_user_id_fk','element_medication','last_modified_user_id','user','id');
		$this->addColumn('element_mini_refraction','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_mini_refraction','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_mini_refraction_last_modified_user_id_fk','element_mini_refraction','last_modified_user_id','user','id');
		$this->addColumn('element_nsc_grade','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_nsc_grade','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_nsc_grade_last_modified_user_id_fk','element_nsc_grade','last_modified_user_id','user','id');
		$this->addColumn('element_operation','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_operation','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_operation_last_modified_user_id_fk','element_operation','last_modified_user_id','user','id');
		$this->addColumn('element_orbital_examination','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_orbital_examination','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_orbital_examination_last_modified_user_id_fk','element_orbital_examination','last_modified_user_id','user','id');
		$this->addColumn('element_past_history','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_past_history','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_past_history_last_modified_user_id_fk','element_past_history','last_modified_user_id','user','id');
		$this->addColumn('element_pmh','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_pmh','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_pmh_last_modified_user_id_fk','element_pmh','last_modified_user_id','user','id');
		$this->addColumn('element_poh','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_poh','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_poh_last_modified_user_id_fk','element_poh','last_modified_user_id','user','id');
		$this->addColumn('element_posterior_segment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_posterior_segment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_posterior_segment_last_modified_user_id_fk','element_posterior_segment','last_modified_user_id','user','id');
		$this->addColumn('element_referred_from_screening','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_referred_from_screening','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_referred_from_screening_last_modified_user_id_fk','element_referred_from_screening','last_modified_user_id','user','id');
		$this->addColumn('element_registered_blind','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_registered_blind','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_registered_blind_last_modified_user_id_fk','element_registered_blind','last_modified_user_id','user','id');
		$this->addColumn('element_social_history','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_social_history','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_social_history_last_modified_user_id_fk','element_social_history','last_modified_user_id','user','id');
		$this->addColumn('element_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_type_last_modified_user_id_fk','element_type','last_modified_user_id','user','id');
		$this->addColumn('element_visual_acuity','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_visual_acuity','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_visual_acuity_last_modified_user_id_fk','element_visual_acuity','last_modified_user_id','user','id');
		$this->addColumn('element_visual_fields','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_visual_fields','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_visual_fields_last_modified_user_id_fk','element_visual_fields','last_modified_user_id','user','id');
		$this->addColumn('element_visual_function','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('element_visual_function','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('element_visual_function_last_modified_user_id_fk','element_visual_function','last_modified_user_id','user','id');
		$this->addColumn('episode','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('episode','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('episode_last_modified_user_id_fk','episode','last_modified_user_id','user','id');
		$this->addColumn('event','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('event','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('event_last_modified_user_id_fk','event','last_modified_user_id','user','id');
		$this->addColumn('event_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('event_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('event_type_last_modified_user_id_fk','event_type','last_modified_user_id','user','id');
		$this->addColumn('firm','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('firm','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('firm_last_modified_user_id_fk','firm','last_modified_user_id','user','id');
		$this->addColumn('firm_user_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('firm_user_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('firm_user_assignment_last_modified_user_id_fk','firm_user_assignment','last_modified_user_id','user','id');
		$this->addColumn('gp','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('gp','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('gp_last_modified_user_id_fk','gp','last_modified_user_id','user','id');
		$this->addColumn('letter_template','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('letter_template','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('letter_template_last_modified_user_id_fk','letter_template','last_modified_user_id','user','id');
		$this->addColumn('manual_contact','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('manual_contact','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('manual_contact_last_modified_user_id_fk','manual_contact','last_modified_user_id','user','id');
		$this->addColumn('nsc_grade','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('nsc_grade','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('nsc_grade_last_modified_user_id_fk','nsc_grade','last_modified_user_id','user','id');
		$this->addColumn('opcs_code','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('opcs_code','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('opcs_code_last_modified_user_id_fk','opcs_code','last_modified_user_id','user','id');
		$this->addColumn('operation_procedure_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('operation_procedure_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('operation_procedure_assignment_last_modified_user_id_fk','operation_procedure_assignment','last_modified_user_id','user','id');
		$this->addColumn('patient','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('patient','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('patient_last_modified_user_id_fk','patient','last_modified_user_id','user','id');
		$this->addColumn('patient_contact_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('patient_contact_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('patient_contact_assignment_last_modified_user_id_fk','patient_contact_assignment','last_modified_user_id','user','id');
		$this->addColumn('phrase','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('phrase','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('phrase_last_modified_user_id_fk','phrase','last_modified_user_id','user','id');
		$this->addColumn('phrase_by_firm','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('phrase_by_firm','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('phrase_by_firm_last_modified_user_id_fk','phrase_by_firm','last_modified_user_id','user','id');
		$this->addColumn('phrase_by_specialty','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('phrase_by_specialty','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('phrase_by_specialty_last_modified_user_id_fk','phrase_by_specialty','last_modified_user_id','user','id');
		$this->addColumn('phrase_name','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('phrase_name','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('phrase_name_last_modified_user_id_fk','phrase_name','last_modified_user_id','user','id');
		$this->addColumn('possible_element_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('possible_element_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('possible_element_type_last_modified_user_id_fk','possible_element_type','last_modified_user_id','user','id');
		$this->addColumn('proc','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('proc','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('proc_last_modified_user_id_fk','proc','last_modified_user_id','user','id');
		$this->addColumn('proc_opcs_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('proc_opcs_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('proc_opcs_assignment_last_modified_user_id_fk','proc_opcs_assignment','last_modified_user_id','user','id');
		$this->addColumn('proc_specialty_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('proc_specialty_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('proc_specialty_assignment_last_modified_user_id_fk','proc_specialty_assignment','last_modified_user_id','user','id');
		$this->addColumn('proc_specialty_subsection_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('proc_specialty_subsection_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('proc_specialty_subsection_assignment_last_modified_user_id_fk','proc_specialty_subsection_assignment','last_modified_user_id','user','id');
		$this->addColumn('referral','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('referral','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('referral_last_modified_user_id_fk','referral','last_modified_user_id','user','id');
		$this->addColumn('referral_episode_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('referral_episode_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('referral_episode_assignment_last_modified_user_id_fk','referral_episode_assignment','last_modified_user_id','user','id');
		$this->addColumn('section','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('section','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('section_last_modified_user_id_fk','section','last_modified_user_id','user','id');
		$this->addColumn('section_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('section_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('section_type_last_modified_user_id_fk','section_type','last_modified_user_id','user','id');
		$this->addColumn('sequence','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('sequence','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('sequence_last_modified_user_id_fk','sequence','last_modified_user_id','user','id');
		$this->addColumn('sequence_firm_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('sequence_firm_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('sequence_firm_assignment_last_modified_user_id_fk','sequence_firm_assignment','last_modified_user_id','user','id');
		$this->addColumn('service','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('service','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('service_last_modified_user_id_fk','service','last_modified_user_id','user','id');
		$this->addColumn('service_specialty_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('service_specialty_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('service_specialty_assignment_last_modified_user_id_fk','service_specialty_assignment','last_modified_user_id','user','id');
		$this->addColumn('session','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('session','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('session_last_modified_user_id_fk','session','last_modified_user_id','user','id');
		$this->addColumn('site','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('site','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('site_last_modified_user_id_fk','site','last_modified_user_id','user','id');
		$this->addColumn('site_element_type','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('site_element_type','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('site_element_type_last_modified_user_id_fk','site_element_type','last_modified_user_id','user','id');
		$this->addColumn('specialty','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('specialty','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('specialty_last_modified_user_id_fk','specialty','last_modified_user_id','user','id');
		$this->addColumn('specialty_subsection','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('specialty_subsection','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('specialty_subsection_last_modified_user_id_fk','specialty_subsection','last_modified_user_id','user','id');
		$this->addColumn('tbl_migration','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('tbl_migration','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('tbl_migration_last_modified_user_id_fk','tbl_migration','last_modified_user_id','user','id');
		$this->addColumn('theatre','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('theatre','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('theatre_last_modified_user_id_fk','theatre','last_modified_user_id','user','id');
		$this->addColumn('theatre_ward_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('theatre_ward_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('theatre_ward_assignment_last_modified_user_id_fk','theatre_ward_assignment','last_modified_user_id','user','id');
		$this->addColumn('user','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('user','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('user_last_modified_user_id_fk','user','last_modified_user_id','user','id');
		$this->addColumn('user_contact_assignment','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('user_contact_assignment','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('user_contact_assignment_last_modified_user_id_fk','user_contact_assignment','last_modified_user_id','user','id');
		$this->addColumn('user_firm_rights','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('user_firm_rights','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('user_firm_rights_last_modified_user_id_fk','user_firm_rights','last_modified_user_id','user','id');
		$this->addColumn('user_service_rights','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('user_service_rights','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('user_service_rights_last_modified_user_id_fk','user_service_rights','last_modified_user_id','user','id');
		$this->addColumn('user_session','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('user_session','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('user_session_last_modified_user_id_fk','user_session','last_modified_user_id','user','id');
		$this->addColumn('ward','last_modified_user_id','int(10) unsigned NOT NULL DEFAULT 1');
		$this->addColumn('ward','last_modified_date','datetime NOT NULL');
		$this->addForeignKey('ward_last_modified_user_id_fk','ward','last_modified_user_id','user','id');
	}

	public function down()
	{
		$this->dropForeignKey('address_last_modified_user_id_fk','address');
		$this->dropColumn('address','last_modified_user_id');
		$this->dropColumn('address','last_modified_date');
		$this->dropForeignKey('authassignment_last_modified_user_id_fk','authassignment');
		$this->dropColumn('authassignment','last_modified_user_id');
		$this->dropColumn('authassignment','last_modified_date');
		$this->dropForeignKey('authitem_last_modified_user_id_fk','authitem');
		$this->dropColumn('authitem','last_modified_user_id');
		$this->dropColumn('authitem','last_modified_date');
		$this->dropForeignKey('authitemchild_last_modified_user_id_fk','authitemchild');
		$this->dropColumn('authitemchild','last_modified_user_id');
		$this->dropColumn('authitemchild','last_modified_date');
		$this->dropForeignKey('booking_last_modified_user_id_fk','booking');
		$this->dropColumn('booking','last_modified_user_id');
		$this->dropColumn('booking','last_modified_date');
		$this->dropForeignKey('cancellation_reason_last_modified_user_id_fk','cancellation_reason');
		$this->dropColumn('cancellation_reason','last_modified_user_id');
		$this->dropColumn('cancellation_reason','last_modified_date');
		$this->dropForeignKey('cancelled_booking_last_modified_user_id_fk','cancelled_booking');
		$this->dropColumn('cancelled_booking','last_modified_user_id');
		$this->dropColumn('cancelled_booking','last_modified_date');
		$this->dropForeignKey('cancelled_operation_last_modified_user_id_fk','cancelled_operation');
		$this->dropColumn('cancelled_operation','last_modified_user_id');
		$this->dropColumn('cancelled_operation','last_modified_date');
		$this->dropForeignKey('common_ophthalmic_disorder_last_modified_user_id_fk','common_ophthalmic_disorder');
		$this->dropColumn('common_ophthalmic_disorder','last_modified_user_id');
		$this->dropColumn('common_ophthalmic_disorder','last_modified_date');
		$this->dropForeignKey('common_systemic_disorder_last_modified_user_id_fk','common_systemic_disorder');
		$this->dropColumn('common_systemic_disorder','last_modified_user_id');
		$this->dropColumn('common_systemic_disorder','last_modified_date');
		$this->dropForeignKey('consultant_last_modified_user_id_fk','consultant');
		$this->dropColumn('consultant','last_modified_user_id');
		$this->dropColumn('consultant','last_modified_date');
		$this->dropForeignKey('contact_last_modified_user_id_fk','contact');
		$this->dropColumn('contact','last_modified_user_id');
		$this->dropColumn('contact','last_modified_date');
		$this->dropForeignKey('contact_type_last_modified_user_id_fk','contact_type');
		$this->dropColumn('contact_type','last_modified_user_id');
		$this->dropColumn('contact_type','last_modified_date');
		$this->dropForeignKey('country_last_modified_user_id_fk','country');
		$this->dropColumn('country','last_modified_user_id');
		$this->dropColumn('country','last_modified_date');
		$this->dropForeignKey('disorder_last_modified_user_id_fk','disorder');
		$this->dropColumn('disorder','last_modified_user_id');
		$this->dropColumn('disorder','last_modified_date');
		$this->dropForeignKey('element_allergies_last_modified_user_id_fk','element_allergies');
		$this->dropColumn('element_allergies','last_modified_user_id');
		$this->dropColumn('element_allergies','last_modified_date');
		$this->dropForeignKey('element_anterior_segment_last_modified_user_id_fk','element_anterior_segment');
		$this->dropColumn('element_anterior_segment','last_modified_user_id');
		$this->dropColumn('element_anterior_segment','last_modified_date');
		$this->dropForeignKey('element_conclusion_last_modified_user_id_fk','element_conclusion');
		$this->dropColumn('element_conclusion','last_modified_user_id');
		$this->dropColumn('element_conclusion','last_modified_date');
		$this->dropForeignKey('element_cranial_nerves_last_modified_user_id_fk','element_cranial_nerves');
		$this->dropColumn('element_cranial_nerves','last_modified_user_id');
		$this->dropColumn('element_cranial_nerves','last_modified_date');
		$this->dropForeignKey('element_diabetes_type_last_modified_user_id_fk','element_diabetes_type');
		$this->dropColumn('element_diabetes_type','last_modified_user_id');
		$this->dropColumn('element_diabetes_type','last_modified_date');
		$this->dropForeignKey('element_diagnosis_last_modified_user_id_fk','element_diagnosis');
		$this->dropColumn('element_diagnosis','last_modified_user_id');
		$this->dropColumn('element_diagnosis','last_modified_date');
		$this->dropForeignKey('element_extraocular_movements_last_modified_user_id_fk','element_extraocular_movements');
		$this->dropColumn('element_extraocular_movements','last_modified_user_id');
		$this->dropColumn('element_extraocular_movements','last_modified_date');
		$this->dropForeignKey('element_foh_last_modified_user_id_fk','element_foh');
		$this->dropColumn('element_foh','last_modified_user_id');
		$this->dropColumn('element_foh','last_modified_date');
		$this->dropForeignKey('element_gonioscopy_last_modified_user_id_fk','element_gonioscopy');
		$this->dropColumn('element_gonioscopy','last_modified_user_id');
		$this->dropColumn('element_gonioscopy','last_modified_date');
		$this->dropForeignKey('element_history_last_modified_user_id_fk','element_history');
		$this->dropColumn('element_history','last_modified_user_id');
		$this->dropColumn('element_history','last_modified_date');
		$this->dropForeignKey('element_hpc_last_modified_user_id_fk','element_hpc');
		$this->dropColumn('element_hpc','last_modified_user_id');
		$this->dropColumn('element_hpc','last_modified_date');
		$this->dropForeignKey('element_intraocular_pressure_last_modified_user_id_fk','element_intraocular_pressure');
		$this->dropColumn('element_intraocular_pressure','last_modified_user_id');
		$this->dropColumn('element_intraocular_pressure','last_modified_date');
		$this->dropForeignKey('element_letterout_last_modified_user_id_fk','element_letterout');
		$this->dropColumn('element_letterout','last_modified_user_id');
		$this->dropColumn('element_letterout','last_modified_date');
		$this->dropForeignKey('element_medication_last_modified_user_id_fk','element_medication');
		$this->dropColumn('element_medication','last_modified_user_id');
		$this->dropColumn('element_medication','last_modified_date');
		$this->dropForeignKey('element_mini_refraction_last_modified_user_id_fk','element_mini_refraction');
		$this->dropColumn('element_mini_refraction','last_modified_user_id');
		$this->dropColumn('element_mini_refraction','last_modified_date');
		$this->dropForeignKey('element_nsc_grade_last_modified_user_id_fk','element_nsc_grade');
		$this->dropColumn('element_nsc_grade','last_modified_user_id');
		$this->dropColumn('element_nsc_grade','last_modified_date');
		$this->dropForeignKey('element_operation_last_modified_user_id_fk','element_operation');
		$this->dropColumn('element_operation','last_modified_user_id');
		$this->dropColumn('element_operation','last_modified_date');
		$this->dropForeignKey('element_orbital_examination_last_modified_user_id_fk','element_orbital_examination');
		$this->dropColumn('element_orbital_examination','last_modified_user_id');
		$this->dropColumn('element_orbital_examination','last_modified_date');
		$this->dropForeignKey('element_past_history_last_modified_user_id_fk','element_past_history');
		$this->dropColumn('element_past_history','last_modified_user_id');
		$this->dropColumn('element_past_history','last_modified_date');
		$this->dropForeignKey('element_pmh_last_modified_user_id_fk','element_pmh');
		$this->dropColumn('element_pmh','last_modified_user_id');
		$this->dropColumn('element_pmh','last_modified_date');
		$this->dropForeignKey('element_poh_last_modified_user_id_fk','element_poh');
		$this->dropColumn('element_poh','last_modified_user_id');
		$this->dropColumn('element_poh','last_modified_date');
		$this->dropForeignKey('element_posterior_segment_last_modified_user_id_fk','element_posterior_segment');
		$this->dropColumn('element_posterior_segment','last_modified_user_id');
		$this->dropColumn('element_posterior_segment','last_modified_date');
		$this->dropForeignKey('element_referred_from_screening_last_modified_user_id_fk','element_referred_from_screening');
		$this->dropColumn('element_referred_from_screening','last_modified_user_id');
		$this->dropColumn('element_referred_from_screening','last_modified_date');
		$this->dropForeignKey('element_registered_blind_last_modified_user_id_fk','element_registered_blind');
		$this->dropColumn('element_registered_blind','last_modified_user_id');
		$this->dropColumn('element_registered_blind','last_modified_date');
		$this->dropForeignKey('element_social_history_last_modified_user_id_fk','element_social_history');
		$this->dropColumn('element_social_history','last_modified_user_id');
		$this->dropColumn('element_social_history','last_modified_date');
		$this->dropForeignKey('element_type_last_modified_user_id_fk','element_type');
		$this->dropColumn('element_type','last_modified_user_id');
		$this->dropColumn('element_type','last_modified_date');
		$this->dropForeignKey('element_visual_acuity_last_modified_user_id_fk','element_visual_acuity');
		$this->dropColumn('element_visual_acuity','last_modified_user_id');
		$this->dropColumn('element_visual_acuity','last_modified_date');
		$this->dropForeignKey('element_visual_fields_last_modified_user_id_fk','element_visual_fields');
		$this->dropColumn('element_visual_fields','last_modified_user_id');
		$this->dropColumn('element_visual_fields','last_modified_date');
		$this->dropForeignKey('element_visual_function_last_modified_user_id_fk','element_visual_function');
		$this->dropColumn('element_visual_function','last_modified_user_id');
		$this->dropColumn('element_visual_function','last_modified_date');
		$this->dropForeignKey('episode_last_modified_user_id_fk','episode');
		$this->dropColumn('episode','last_modified_user_id');
		$this->dropColumn('episode','last_modified_date');
		$this->dropForeignKey('event_last_modified_user_id_fk','event');
		$this->dropColumn('event','last_modified_user_id');
		$this->dropColumn('event','last_modified_date');
		$this->dropForeignKey('event_type_last_modified_user_id_fk','event_type');
		$this->dropColumn('event_type','last_modified_user_id');
		$this->dropColumn('event_type','last_modified_date');
		$this->dropForeignKey('firm_last_modified_user_id_fk','firm');
		$this->dropColumn('firm','last_modified_user_id');
		$this->dropColumn('firm','last_modified_date');
		$this->dropForeignKey('firm_user_assignment_last_modified_user_id_fk','firm_user_assignment');
		$this->dropColumn('firm_user_assignment','last_modified_user_id');
		$this->dropColumn('firm_user_assignment','last_modified_date');
		$this->dropForeignKey('gp_last_modified_user_id_fk','gp');
		$this->dropColumn('gp','last_modified_user_id');
		$this->dropColumn('gp','last_modified_date');
		$this->dropForeignKey('letter_template_last_modified_user_id_fk','letter_template');
		$this->dropColumn('letter_template','last_modified_user_id');
		$this->dropColumn('letter_template','last_modified_date');
		$this->dropForeignKey('manual_contact_last_modified_user_id_fk','manual_contact');
		$this->dropColumn('manual_contact','last_modified_user_id');
		$this->dropColumn('manual_contact','last_modified_date');
		$this->dropForeignKey('nsc_grade_last_modified_user_id_fk','nsc_grade');
		$this->dropColumn('nsc_grade','last_modified_user_id');
		$this->dropColumn('nsc_grade','last_modified_date');
		$this->dropForeignKey('opcs_code_last_modified_user_id_fk','opcs_code');
		$this->dropColumn('opcs_code','last_modified_user_id');
		$this->dropColumn('opcs_code','last_modified_date');
		$this->dropForeignKey('operation_procedure_assignment_last_modified_user_id_fk','operation_procedure_assignment');
		$this->dropColumn('operation_procedure_assignment','last_modified_user_id');
		$this->dropColumn('operation_procedure_assignment','last_modified_date');
		$this->dropForeignKey('patient_last_modified_user_id_fk','patient');
		$this->dropColumn('patient','last_modified_user_id');
		$this->dropColumn('patient','last_modified_date');
		$this->dropForeignKey('patient_contact_assignment_last_modified_user_id_fk','patient_contact_assignment');
		$this->dropColumn('patient_contact_assignment','last_modified_user_id');
		$this->dropColumn('patient_contact_assignment','last_modified_date');
		$this->dropForeignKey('phrase_last_modified_user_id_fk','phrase');
		$this->dropColumn('phrase','last_modified_user_id');
		$this->dropColumn('phrase','last_modified_date');
		$this->dropForeignKey('phrase_by_firm_last_modified_user_id_fk','phrase_by_firm');
		$this->dropColumn('phrase_by_firm','last_modified_user_id');
		$this->dropColumn('phrase_by_firm','last_modified_date');
		$this->dropForeignKey('phrase_by_specialty_last_modified_user_id_fk','phrase_by_specialty');
		$this->dropColumn('phrase_by_specialty','last_modified_user_id');
		$this->dropColumn('phrase_by_specialty','last_modified_date');
		$this->dropForeignKey('phrase_name_last_modified_user_id_fk','phrase_name');
		$this->dropColumn('phrase_name','last_modified_user_id');
		$this->dropColumn('phrase_name','last_modified_date');
		$this->dropForeignKey('possible_element_type_last_modified_user_id_fk','possible_element_type');
		$this->dropColumn('possible_element_type','last_modified_user_id');
		$this->dropColumn('possible_element_type','last_modified_date');
		$this->dropForeignKey('proc_last_modified_user_id_fk','proc');
		$this->dropColumn('proc','last_modified_user_id');
		$this->dropColumn('proc','last_modified_date');
		$this->dropForeignKey('proc_opcs_assignment_last_modified_user_id_fk','proc_opcs_assignment');
		$this->dropColumn('proc_opcs_assignment','last_modified_user_id');
		$this->dropColumn('proc_opcs_assignment','last_modified_date');
		$this->dropForeignKey('proc_specialty_assignment_last_modified_user_id_fk','proc_specialty_assignment');
		$this->dropColumn('proc_specialty_assignment','last_modified_user_id');
		$this->dropColumn('proc_specialty_assignment','last_modified_date');
		$this->dropForeignKey('proc_specialty_subsection_assignment_last_modified_user_id_fk','proc_specialty_subsection_assignment');
		$this->dropColumn('proc_specialty_subsection_assignment','last_modified_user_id');
		$this->dropColumn('proc_specialty_subsection_assignment','last_modified_date');
		$this->dropForeignKey('referral_last_modified_user_id_fk','referral');
		$this->dropColumn('referral','last_modified_user_id');
		$this->dropColumn('referral','last_modified_date');
		$this->dropForeignKey('referral_episode_assignment_last_modified_user_id_fk','referral_episode_assignment');
		$this->dropColumn('referral_episode_assignment','last_modified_user_id');
		$this->dropColumn('referral_episode_assignment','last_modified_date');
		$this->dropForeignKey('section_last_modified_user_id_fk','section');
		$this->dropColumn('section','last_modified_user_id');
		$this->dropColumn('section','last_modified_date');
		$this->dropForeignKey('section_type_last_modified_user_id_fk','section_type');
		$this->dropColumn('section_type','last_modified_user_id');
		$this->dropColumn('section_type','last_modified_date');
		$this->dropForeignKey('sequence_last_modified_user_id_fk','sequence');
		$this->dropColumn('sequence','last_modified_user_id');
		$this->dropColumn('sequence','last_modified_date');
		$this->dropForeignKey('sequence_firm_assignment_last_modified_user_id_fk','sequence_firm_assignment');
		$this->dropColumn('sequence_firm_assignment','last_modified_user_id');
		$this->dropColumn('sequence_firm_assignment','last_modified_date');
		$this->dropForeignKey('service_last_modified_user_id_fk','service');
		$this->dropColumn('service','last_modified_user_id');
		$this->dropColumn('service','last_modified_date');
		$this->dropForeignKey('service_specialty_assignment_last_modified_user_id_fk','service_specialty_assignment');
		$this->dropColumn('service_specialty_assignment','last_modified_user_id');
		$this->dropColumn('service_specialty_assignment','last_modified_date');
		$this->dropForeignKey('session_last_modified_user_id_fk','session');
		$this->dropColumn('session','last_modified_user_id');
		$this->dropColumn('session','last_modified_date');
		$this->dropForeignKey('site_last_modified_user_id_fk','site');
		$this->dropColumn('site','last_modified_user_id');
		$this->dropColumn('site','last_modified_date');
		$this->dropForeignKey('site_element_type_last_modified_user_id_fk','site_element_type');
		$this->dropColumn('site_element_type','last_modified_user_id');
		$this->dropColumn('site_element_type','last_modified_date');
		$this->dropForeignKey('specialty_last_modified_user_id_fk','specialty');
		$this->dropColumn('specialty','last_modified_user_id');
		$this->dropColumn('specialty','last_modified_date');
		$this->dropForeignKey('specialty_subsection_last_modified_user_id_fk','specialty_subsection');
		$this->dropColumn('specialty_subsection','last_modified_user_id');
		$this->dropColumn('specialty_subsection','last_modified_date');
		$this->dropForeignKey('tbl_migration_last_modified_user_id_fk','tbl_migration');
		$this->dropColumn('tbl_migration','last_modified_user_id');
		$this->dropColumn('tbl_migration','last_modified_date');
		$this->dropForeignKey('theatre_last_modified_user_id_fk','theatre');
		$this->dropColumn('theatre','last_modified_user_id');
		$this->dropColumn('theatre','last_modified_date');
		$this->dropForeignKey('theatre_ward_assignment_last_modified_user_id_fk','theatre_ward_assignment');
		$this->dropColumn('theatre_ward_assignment','last_modified_user_id');
		$this->dropColumn('theatre_ward_assignment','last_modified_date');
		$this->dropForeignKey('user_last_modified_user_id_fk','user');
		$this->dropColumn('user','last_modified_user_id');
		$this->dropColumn('user','last_modified_date');
		$this->dropForeignKey('user_contact_assignment_last_modified_user_id_fk','user_contact_assignment');
		$this->dropColumn('user_contact_assignment','last_modified_user_id');
		$this->dropColumn('user_contact_assignment','last_modified_date');
		$this->dropForeignKey('user_firm_rights_last_modified_user_id_fk','user_firm_rights');
		$this->dropColumn('user_firm_rights','last_modified_user_id');
		$this->dropColumn('user_firm_rights','last_modified_date');
		$this->dropForeignKey('user_service_rights_last_modified_user_id_fk','user_service_rights');
		$this->dropColumn('user_service_rights','last_modified_user_id');
		$this->dropColumn('user_service_rights','last_modified_date');
		$this->dropForeignKey('user_session_last_modified_user_id_fk','user_session');
		$this->dropColumn('user_session','last_modified_user_id');
		$this->dropColumn('user_session','last_modified_date');
		$this->dropForeignKey('ward_last_modified_user_id_fk','ward');
		$this->dropColumn('ward','last_modified_user_id');
		$this->dropColumn('ward','last_modified_date');
	}
}
?>
