<?php

class m120306_121306_new_specialty_table extends CDbMigration
{
	public function up()
	{
		$this->createTable('specialty',array(
			'id' => 'int(10) unsigned NOT NULL AUTO_INCREMENT',
			'name' => "varchar(255) NOT NULL DEFAULT ''",
			'code' => "varchar(3) NOT NULL DEFAULT ''",
			'PRIMARY KEY (`id`)'
		), 'ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin');

		$this->insert('specialty',array('id'=>1,'name'=>'Abdominal Radiology','code'=>'AR'));
		$this->insert('specialty',array('id'=>2,'name'=>'Abdominal Surgery','code'=>'AS'));
		$this->insert('specialty',array('id'=>3,'name'=>'Addiction Medicine','code'=>'ADM'));
		$this->insert('specialty',array('id'=>4,'name'=>'Addiction Psychiatry','code'=>'ADP'));
		$this->insert('specialty',array('id'=>5,'name'=>'Adolescent Medicine (Family Medicine)','code'=>'AMF'));
		$this->insert('specialty',array('id'=>6,'name'=>'Adolescent Medicine (Internal Medicine)','code'=>'AMI'));
		$this->insert('specialty',array('id'=>7,'name'=>'Adolescent Medicine (Pediatrics)','code'=>'ADL'));
		$this->insert('specialty',array('id'=>8,'name'=>'Adult Reconstructive Orthopedics','code'=>'OAR'));
		$this->insert('specialty',array('id'=>9,'name'=>'Aerospace Medicine','code'=>'AM'));
		$this->insert('specialty',array('id'=>10,'name'=>'Allergy','code'=>'A'));
		$this->insert('specialty',array('id'=>11,'name'=>'Allergy & Immunology','code'=>'AI'));
		$this->insert('specialty',array('id'=>12,'name'=>'Clinical Laboratory Immunology (Allergy & Immunology)','code'=>'ALI'));
		$this->insert('specialty',array('id'=>13,'name'=>'Anatomic/Clinical Pathology','code'=>'PTH'));
		$this->insert('specialty',array('id'=>14,'name'=>'Anatomic Pathology','code'=>'ATP'));
		$this->insert('specialty',array('id'=>15,'name'=>'Anesthesiology','code'=>'AN'));
		$this->insert('specialty',array('id'=>16,'name'=>'Blood Banking/Transfusion Medicine','code'=>'BBK'));
		$this->insert('specialty',array('id'=>17,'name'=>'Clinical Cardiac Electrophysiology','code'=>'ICE'));
		$this->insert('specialty',array('id'=>18,'name'=>'Cardiothoracic Radiology','code'=>'CTR'));
		$this->insert('specialty',array('id'=>19,'name'=>'Cardiothoracic Surgery','code'=>'CTS'));
		$this->insert('specialty',array('id'=>20,'name'=>'Cardiovascular Disease','code'=>'CD'));
		$this->insert('specialty',array('id'=>21,'name'=>'Chemical Pathology','code'=>'PCH'));
		$this->insert('specialty',array('id'=>22,'name'=>'Child and Adolescent Psychiatry','code'=>'CHP'));
		$this->insert('specialty',array('id'=>23,'name'=>'Child Neurology','code'=>'CHN'));
		$this->insert('specialty',array('id'=>24,'name'=>'Clinical Biochemical Genetics','code'=>'CBG'));
		$this->insert('specialty',array('id'=>25,'name'=>'Clinical Cytogenetics','code'=>'CCG'));
		$this->insert('specialty',array('id'=>26,'name'=>'Clinical Genetics','code'=>'CG'));
		$this->insert('specialty',array('id'=>27,'name'=>'Clinical and Laboratory Dermatological Immunology','code'=>'DDL'));
		$this->insert('specialty',array('id'=>28,'name'=>'Clinical and Laboratory Immunology (Internal Medicine)','code'=>'ILI'));
		$this->insert('specialty',array('id'=>29,'name'=>'Clinical and Laboratory Immunology (Pediatrics)','code'=>'PLI'));
		$this->insert('specialty',array('id'=>30,'name'=>'Clinical Molecular Genetics','code'=>'CMG'));
		$this->insert('specialty',array('id'=>31,'name'=>'Clinical Neurophysiology','code'=>'CN'));
		$this->insert('specialty',array('id'=>32,'name'=>'Clinical Pathology','code'=>'CLP'));
		$this->insert('specialty',array('id'=>33,'name'=>'Clinical Pharmacology','code'=>'PA'));
		$this->insert('specialty',array('id'=>34,'name'=>'Colon & Rectal Surgery','code'=>'CRS'));
		$this->insert('specialty',array('id'=>35,'name'=>'Cosmetic Surgery','code'=>'CS'));
		$this->insert('specialty',array('id'=>36,'name'=>'Craniofacial Surgery','code'=>'CFS'));
		$this->insert('specialty',array('id'=>37,'name'=>'Critical Care Medicine (Anesthesiology)','code'=>'CCA'));
		$this->insert('specialty',array('id'=>38,'name'=>'Critical Care Medicine (Internal Medicine)','code'=>'CCM'));
		$this->insert('specialty',array('id'=>39,'name'=>'Critical Care Medicine (Neurological Surgery)','code'=>'NCC'));
		$this->insert('specialty',array('id'=>40,'name'=>'Critical Care Medicine (Obstetrics & Gynecology)','code'=>'OCC'));
		$this->insert('specialty',array('id'=>41,'name'=>'Cytopathology','code'=>'PCP'));
		$this->insert('specialty',array('id'=>42,'name'=>'Dermatology','code'=>'D'));
		$this->insert('specialty',array('id'=>43,'name'=>'Dermatopathology','code'=>'DMP'));
		$this->insert('specialty',array('id'=>44,'name'=>'Dermatologic Surgery','code'=>'DS'));
		$this->insert('specialty',array('id'=>45,'name'=>'Developmental-Behavioral  Pediatrics','code'=>'DBP'));
		$this->insert('specialty',array('id'=>46,'name'=>'Diabetes','code'=>'DIA'));
		$this->insert('specialty',array('id'=>47,'name'=>'Diagnostic Radiology','code'=>'DR'));
		$this->insert('specialty',array('id'=>48,'name'=>'Emergency Medicine','code'=>'EM'));
		$this->insert('specialty',array('id'=>49,'name'=>'Endocrinology, Diabetes and Metabolism','code'=>'END'));
		$this->insert('specialty',array('id'=>50,'name'=>'Endovascular Surgical Neuroradiology','code'=>'ESN'));
		$this->insert('specialty',array('id'=>51,'name'=>'Epidemiology','code'=>'EP'));
		$this->insert('specialty',array('id'=>52,'name'=>'Facial Plastic Surgery','code'=>'FPS'));
		$this->insert('specialty',array('id'=>53,'name'=>'Family Practice','code'=>'FP'));
		$this->insert('specialty',array('id'=>54,'name'=>'Forensic Pathology','code'=>'FOP'));
		$this->insert('specialty',array('id'=>55,'name'=>'Forensic Psychiatry','code'=>'PFP'));
		$this->insert('specialty',array('id'=>56,'name'=>'Gastroenterology','code'=>'GE'));
		$this->insert('specialty',array('id'=>57,'name'=>'General Practice','code'=>'GP'));
		$this->insert('specialty',array('id'=>58,'name'=>'General Preventive Medicine','code'=>'GPM'));
		$this->insert('specialty',array('id'=>59,'name'=>'General Surgery','code'=>'GS'));
		$this->insert('specialty',array('id'=>60,'name'=>'Geriatric Medicine (Family Practice)','code'=>'FPG'));
		$this->insert('specialty',array('id'=>61,'name'=>'Geriatric Medicine (Internal Medicine)','code'=>'IMG'));
		$this->insert('specialty',array('id'=>62,'name'=>'Geriatric Psychiatry','code'=>'PYG'));
		$this->insert('specialty',array('id'=>63,'name'=>'Gynecology','code'=>'GYN'));
		$this->insert('specialty',array('id'=>64,'name'=>'Gynecological Oncology','code'=>'GO'));
		$this->insert('specialty',array('id'=>65,'name'=>'Hand Surgery','code'=>'HS'));
		$this->insert('specialty',array('id'=>66,'name'=>'Head & Neck Surgery','code'=>'HNS'));
		$this->insert('specialty',array('id'=>67,'name'=>'Hematology (Internal Medicine)','code'=>'HEM'));
		$this->insert('specialty',array('id'=>68,'name'=>'Hematology (Pathology)','code'=>'HMP'));
		$this->insert('specialty',array('id'=>69,'name'=>'Hematology/Oncology','code'=>'HO'));
		$this->insert('specialty',array('id'=>70,'name'=>'Hepatology','code'=>'HEP'));
		$this->insert('specialty',array('id'=>71,'name'=>'Hospitalist','code'=>'HOS'));
		$this->insert('specialty',array('id'=>72,'name'=>'Immunology','code'=>'IG'));
		$this->insert('specialty',array('id'=>73,'name'=>'Immunopathology','code'=>'PIP'));
		$this->insert('specialty',array('id'=>74,'name'=>'Infectious Disease','code'=>'ID'));
		$this->insert('specialty',array('id'=>75,'name'=>'Internal Medicine','code'=>'IM'));
		$this->insert('specialty',array('id'=>76,'name'=>'Internal Medicine/Pediatrics','code'=>'MPD'));
		$this->insert('specialty',array('id'=>77,'name'=>'Interventional Cardiology','code'=>'IC'));
		$this->insert('specialty',array('id'=>78,'name'=>'Legal Medicine','code'=>'LM'));
		$this->insert('specialty',array('id'=>79,'name'=>'Maternal & Fetal Medicine','code'=>'MFM'));
		$this->insert('specialty',array('id'=>80,'name'=>'Maxillofacial Radiology','code'=>'MXR'));
		$this->insert('specialty',array('id'=>81,'name'=>'Medical Genetics','code'=>'MG'));
		$this->insert('specialty',array('id'=>82,'name'=>'Medical Management','code'=>'MDM'));
		$this->insert('specialty',array('id'=>83,'name'=>'Medical Microbiology','code'=>'MM'));
		$this->insert('specialty',array('id'=>84,'name'=>'Medical Oncology','code'=>'ON'));
		$this->insert('specialty',array('id'=>85,'name'=>'Medical Toxicology (Emergency Medicine)','code'=>'ETX'));
		$this->insert('specialty',array('id'=>86,'name'=>'Medical Toxicology (Pediatrics)','code'=>'PDT'));
		$this->insert('specialty',array('id'=>87,'name'=>'Medical Toxicology (Preventive Medicine)','code'=>'PTX'));
		$this->insert('specialty',array('id'=>88,'name'=>'Molecular Genetic Pathology (Medical Genetics)','code'=>'MGG'));
		$this->insert('specialty',array('id'=>89,'name'=>'Molecular Genetic Pathology (Pathology)','code'=>'MGP'));
		$this->insert('specialty',array('id'=>90,'name'=>'Musculoskeletal Oncology','code'=>'OMO'));
		$this->insert('specialty',array('id'=>91,'name'=>'Musculoskeletal Radiology','code'=>'MSR'));
		$this->insert('specialty',array('id'=>92,'name'=>'Neonatal-Perinatal Medicine','code'=>'NPM'));
		$this->insert('specialty',array('id'=>93,'name'=>'Nephrology','code'=>'NEP'));
		$this->insert('specialty',array('id'=>94,'name'=>'Neurodevelopmental Disabilities (Pediatrics)','code'=>'NDP'));
		$this->insert('specialty',array('id'=>95,'name'=>'Neurodevelopmental Disabilities (Psychiatry & Neurology)','code'=>'NDN'));
		$this->insert('specialty',array('id'=>96,'name'=>'Neurology','code'=>'N'));
		$this->insert('specialty',array('id'=>97,'name'=>'Neurology/Diagnostic Radiology/Neuroradiology','code'=>'NRN'));
		$this->insert('specialty',array('id'=>98,'name'=>'Neurological Surgery','code'=>'NS'));
		$this->insert('specialty',array('id'=>99,'name'=>'Neuropathology','code'=>'NP'));
		$this->insert('specialty',array('id'=>100,'name'=>'Neuropsychiatry','code'=>'NUP'));
		$this->insert('specialty',array('id'=>101,'name'=>'Neuroradiology','code'=>'RNR'));
		$this->insert('specialty',array('id'=>102,'name'=>'Nuclear Cardiology','code'=>'NC'));
		$this->insert('specialty',array('id'=>103,'name'=>'Nuclear Medicine','code'=>'NM'));
		$this->insert('specialty',array('id'=>104,'name'=>'Nuclear Radiology','code'=>'NR'));
		$this->insert('specialty',array('id'=>105,'name'=>'Nutrition','code'=>'NTR'));
		$this->insert('specialty',array('id'=>106,'name'=>'Obstetrics','code'=>'OBS'));
		$this->insert('specialty',array('id'=>107,'name'=>'Obstetrics & Gynecology','code'=>'OBG'));
		$this->insert('specialty',array('id'=>108,'name'=>'Occupational Medicine','code'=>'OM'));
		$this->insert('specialty',array('id'=>109,'name'=>'Ophthalmology','code'=>'OPH'));
		$this->insert('specialty',array('id'=>110,'name'=>'Oral & Maxillofacial Surgery','code'=>'OMF'));
		$this->insert('specialty',array('id'=>111,'name'=>'Orthopedic Surgery','code'=>'ORS'));
		$this->insert('specialty',array('id'=>112,'name'=>'Orthopedic Surgery of the Spine','code'=>'OSS'));
		$this->insert('specialty',array('id'=>113,'name'=>'Orthopedic Trauma','code'=>'OTR'));
		$this->insert('specialty',array('id'=>114,'name'=>'Orthopedics, Foot and Ankle','code'=>'OFA'));
		$this->insert('specialty',array('id'=>115,'name'=>'Osteopathic Manipulative Medicine','code'=>'OMM'));
		$this->insert('specialty',array('id'=>116,'name'=>'Other','code'=>'OS'));
		$this->insert('specialty',array('id'=>117,'name'=>'Otolaryngology','code'=>'OTO'));
		$this->insert('specialty',array('id'=>118,'name'=>'Otology/Neurotology','code'=>'OT'));
		$this->insert('specialty',array('id'=>119,'name'=>'Pain Management','code'=>'APM'));
		$this->insert('specialty',array('id'=>120,'name'=>'Pain Medicine','code'=>'PMD'));
		$this->insert('specialty',array('id'=>121,'name'=>'Pain Medicine (Psychiatry)','code'=>'PPN'));
		$this->insert('specialty',array('id'=>122,'name'=>'Palliative Medicine','code'=>'PLM'));
		$this->insert('specialty',array('id'=>123,'name'=>'Pediatric Allergy','code'=>'PDA'));
		$this->insert('specialty',array('id'=>124,'name'=>'Pediatric Anesthesiology (Pediatrics)','code'=>'PAN'));
		$this->insert('specialty',array('id'=>125,'name'=>'Pediatric Cardiology','code'=>'PDC'));
		$this->insert('specialty',array('id'=>126,'name'=>'Pediatric Cardiothoric Surgery','code'=>'PCS'));
		$this->insert('specialty',array('id'=>127,'name'=>'Pediatric Critical Care Medicine','code'=>'CCP'));
		$this->insert('specialty',array('id'=>128,'name'=>'Pediatric Dermatology','code'=>'PDD'));
		$this->insert('specialty',array('id'=>129,'name'=>'Pediatric Emergency Medicine (Emergency Medicine)','code'=>'PE'));
		$this->insert('specialty',array('id'=>130,'name'=>'Pediatric Emergency Medicine (Pediatrics)','code'=>'PEM'));
		$this->insert('specialty',array('id'=>131,'name'=>'Pediatric Endocrinology','code'=>'PDE'));
		$this->insert('specialty',array('id'=>132,'name'=>'Pediatric Gastroenterology','code'=>'PG'));
		$this->insert('specialty',array('id'=>133,'name'=>'Pediatric Hematology/Oncology','code'=>'PHO'));
		$this->insert('specialty',array('id'=>134,'name'=>'Pediatric Infectious Disease','code'=>'PDI'));
		$this->insert('specialty',array('id'=>135,'name'=>'Pediatric Nephrology','code'=>'PN'));
		$this->insert('specialty',array('id'=>136,'name'=>'Pediatric Ophthalmology','code'=>'PO'));
		$this->insert('specialty',array('id'=>137,'name'=>'Pediatric Orthopedics','code'=>'OP'));
		$this->insert('specialty',array('id'=>138,'name'=>'Pediatric Otolaryngology','code'=>'PDO'));
		$this->insert('specialty',array('id'=>139,'name'=>'Pediatric Pathology','code'=>'PP'));
		$this->insert('specialty',array('id'=>140,'name'=>'Pediatric Pulmonology','code'=>'PDP'));
		$this->insert('specialty',array('id'=>141,'name'=>'Pediatric Radiology','code'=>'PDR'));
		$this->insert('specialty',array('id'=>142,'name'=>'Pediatric Rehabilitation Medicine','code'=>'RPM'));
		$this->insert('specialty',array('id'=>143,'name'=>'Pediatric Rheumatology','code'=>'PPR'));
		$this->insert('specialty',array('id'=>144,'name'=>'Pediatric Surgery (Neurology)','code'=>'NSP'));
		$this->insert('specialty',array('id'=>145,'name'=>'Pediatric Surgery (Surgery)','code'=>'PDS'));
		$this->insert('specialty',array('id'=>146,'name'=>'Pediatric Urology','code'=>'UP'));
		$this->insert('specialty',array('id'=>147,'name'=>'Pediatrics','code'=>'PD'));
		$this->insert('specialty',array('id'=>148,'name'=>'Pharmaceutical Medicine','code'=>'PHM'));
		$this->insert('specialty',array('id'=>149,'name'=>'Phlebology','code'=>'PHL'));
		$this->insert('specialty',array('id'=>150,'name'=>'Physical Medicine & Rehabilitation','code'=>'PM'));
		$this->insert('specialty',array('id'=>151,'name'=>'Plastic Surgery','code'=>'PS'));
		$this->insert('specialty',array('id'=>152,'name'=>'Plastic Surgery within the Head & Neck','code'=>'PSH'));
		$this->insert('specialty',array('id'=>153,'name'=>'Procedural Dermatology','code'=>'PRD'));
		$this->insert('specialty',array('id'=>154,'name'=>'Proctology','code'=>'PRO'));
		$this->insert('specialty',array('id'=>155,'name'=>'Psychiatry','code'=>'P'));
		$this->insert('specialty',array('id'=>156,'name'=>'Psychoanalysis','code'=>'PYA'));
		$this->insert('specialty',array('id'=>157,'name'=>'Psychosomatic Medicine','code'=>'PYM'));
		$this->insert('specialty',array('id'=>158,'name'=>'Public Health and General Preventive Medicine','code'=>'MPH'));
		$this->insert('specialty',array('id'=>159,'name'=>'Pulmonary Critical Care Medicine','code'=>'PCC'));
		$this->insert('specialty',array('id'=>160,'name'=>'Pulmonary Disease','code'=>'PUD'));
		$this->insert('specialty',array('id'=>161,'name'=>'Radiation Oncology','code'=>'RO'));
		$this->insert('specialty',array('id'=>162,'name'=>'Radiological Physics','code'=>'RP'));
		$this->insert('specialty',array('id'=>163,'name'=>'Radiology','code'=>'R'));
		$this->insert('specialty',array('id'=>164,'name'=>'Radioisotopic Pathology','code'=>'RIP'));
		$this->insert('specialty',array('id'=>165,'name'=>'Reproductive Endocrinology & Infertility','code'=>'REN'));
		$this->insert('specialty',array('id'=>166,'name'=>'Rheumatology','code'=>'RHU'));
		$this->insert('specialty',array('id'=>167,'name'=>'Selective Pathology','code'=>'SP'));
		$this->insert('specialty',array('id'=>168,'name'=>'Sleep Medicine','code'=>'SM'));
		$this->insert('specialty',array('id'=>169,'name'=>'Spinal Cord Injury Medicine','code'=>'SCI'));
		$this->insert('specialty',array('id'=>170,'name'=>'Sports Medicine (Emergency Medicine)','code'=>'ESM'));
		$this->insert('specialty',array('id'=>171,'name'=>'Sports Medicine (Family Practice)','code'=>'FSM'));
		$this->insert('specialty',array('id'=>172,'name'=>'Sports Medicine (Internal Medicine)','code'=>'ISM'));
		$this->insert('specialty',array('id'=>173,'name'=>'Sports Medicine (Orthopedic Surgery)','code'=>'OSM'));
		$this->insert('specialty',array('id'=>174,'name'=>'Sports Medicine (Pediatrics)','code'=>'PSM'));
		$this->insert('specialty',array('id'=>175,'name'=>'Sports Medicine (Physical Medicine & Rehabilitation)','code'=>'PMM'));
		$this->insert('specialty',array('id'=>176,'name'=>'Surgical Critical Care (Surgery)','code'=>'CCS'));
		$this->insert('specialty',array('id'=>177,'name'=>'Surgical Oncology','code'=>'SO'));
		$this->insert('specialty',array('id'=>178,'name'=>'Thoracic Surgery','code'=>'TS'));
		$this->insert('specialty',array('id'=>179,'name'=>'Trauma Surgery','code'=>'TRS'));
		$this->insert('specialty',array('id'=>180,'name'=>'Transplant Surgery','code'=>'TTS'));
		$this->insert('specialty',array('id'=>181,'name'=>'Undersea & Hyperbaric Medicine (Emergency Medicine)','code'=>'UME'));
		$this->insert('specialty',array('id'=>182,'name'=>'Undersea & Hyperbaric Medicine (Preventive Medicine)','code'=>'UM'));
		$this->insert('specialty',array('id'=>183,'name'=>'Unspecified','code'=>'US'));
		$this->insert('specialty',array('id'=>184,'name'=>'Urgent Care Medicine','code'=>'UCM'));
		$this->insert('specialty',array('id'=>185,'name'=>'Urology','code'=>'U'));
		$this->insert('specialty',array('id'=>186,'name'=>'Vascular and Interventional Radiology','code'=>'VIR'));
		$this->insert('specialty',array('id'=>187,'name'=>'Vascular Medicine','code'=>'VM'));
		$this->insert('specialty',array('id'=>188,'name'=>'Vascular Neurology','code'=>'VN'));
		$this->insert('specialty',array('id'=>189,'name'=>'Vascular Surgery','code'=>'VS'));
	}

	public function down()
	{
		$this->dropTable('specialty');
	}
}
