<?php

class m131206_132245_soft_deletion extends CDbMigration
{
	public function up()
	{
		$this->addColumn('address','deleted','tinyint(1) unsigned not null');
		$this->addColumn('address_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('address_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('address_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('allergy','deleted','tinyint(1) unsigned not null');
		$this->addColumn('allergy_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_agent','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_agent_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_complication','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_complication_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_delivery','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_delivery_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetic_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetist','deleted','tinyint(1) unsigned not null');
		$this->addColumn('anaesthetist_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('benefit','deleted','tinyint(1) unsigned not null');
		$this->addColumn('benefit_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_patient_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_patient_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_practice_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_practice_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_service','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_service_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_service_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_service_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('commissioning_body_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_ophthalmic_disorder','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_ophthalmic_disorder_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_previous_operation','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_previous_operation_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_systemic_disorder','deleted','tinyint(1) unsigned not null');
		$this->addColumn('common_systemic_disorder_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('complication','deleted','tinyint(1) unsigned not null');
		$this->addColumn('complication_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('consultant','deleted','tinyint(1) unsigned not null');
		$this->addColumn('consultant_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_label','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_label_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_location','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_location_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_metadata','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_metadata_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('contact_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('country','deleted','tinyint(1) unsigned not null');
		$this->addColumn('country_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('disorder','deleted','tinyint(1) unsigned not null');
		$this->addColumn('disorder_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('disorder_tree','deleted','tinyint(1) unsigned not null');
		$this->addColumn('disorder_tree_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_allergy_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_allergy_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_duration','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_duration_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_form','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_form_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_frequency','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_frequency_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_route','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_route_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_route_option','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_route_option_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set_item_taper','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_set_item_taper_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('drug_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_agent','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_agent_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_complication','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_complication_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_delivery','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_delivery_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetic_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetist','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_anaesthetist_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_eye','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_eye_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_priority','deleted','tinyint(1) unsigned not null');
		$this->addColumn('element_type_priority_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('episode_status','deleted','tinyint(1) unsigned not null');
		$this->addColumn('episode_status_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ethnic_group','deleted','tinyint(1) unsigned not null');
		$this->addColumn('ethnic_group_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_group','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_group_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_issue','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_issue_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('event_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_condition','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_condition_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_relative','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_relative_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_side','deleted','tinyint(1) unsigned not null');
		$this->addColumn('family_history_side_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('firm','deleted','tinyint(1) unsigned not null');
		$this->addColumn('firm_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('firm_user_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('firm_user_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('gp','deleted','tinyint(1) unsigned not null');
		$this->addColumn('gp_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('institution','deleted','tinyint(1) unsigned not null');
		$this->addColumn('institution_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('institution_consultant_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('institution_consultant_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('issue','deleted','tinyint(1) unsigned not null');
		$this->addColumn('issue_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('language','deleted','tinyint(1) unsigned not null');
		$this->addColumn('language_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('manual_contact','deleted','tinyint(1) unsigned not null');
		$this->addColumn('manual_contact_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('medication','deleted','tinyint(1) unsigned not null');
		$this->addColumn('medication_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('nsc_grade','deleted','tinyint(1) unsigned not null');
		$this->addColumn('nsc_grade_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('opcs_code','deleted','tinyint(1) unsigned not null');
		$this->addColumn('opcs_code_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('operative_device','deleted','tinyint(1) unsigned not null');
		$this->addColumn('operative_device_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('pas_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('pas_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('pas_patient_merged','deleted','tinyint(1) unsigned not null');
		$this->addColumn('pas_patient_merged_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_allergy_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_allergy_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_contact_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_contact_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_oph_info','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_oph_info_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_oph_info_cvi_status','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_oph_info_cvi_status_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_shortcode','deleted','tinyint(1) unsigned not null');
		$this->addColumn('patient_shortcode_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('period','deleted','tinyint(1) unsigned not null');
		$this->addColumn('period_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('person','deleted','tinyint(1) unsigned not null');
		$this->addColumn('person_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('practice','deleted','tinyint(1) unsigned not null');
		$this->addColumn('practice_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('previous_operation','deleted','tinyint(1) unsigned not null');
		$this->addColumn('previous_operation_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('priority','deleted','tinyint(1) unsigned not null');
		$this->addColumn('priority_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_opcs_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_opcs_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_subspecialty_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_subspecialty_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_subspecialty_subsection_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('proc_subspecialty_subsection_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_additional','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_additional_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_benefit','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_benefit_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_complication','deleted','tinyint(1) unsigned not null');
		$this->addColumn('procedure_complication_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('protected_file','deleted','tinyint(1) unsigned not null');
		$this->addColumn('protected_file_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral_episode_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral_episode_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('referral_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element_field','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element_field_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element_join','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_element_join_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_table','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_table_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_table_relation','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_table_relation_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_dataset_related_entity_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_graph','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_graph_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_graph_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_graph_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input_data_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input_data_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input_option','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_input_option_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_data_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_data_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_list_item','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_list_item_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_list_item_conditional','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_list_item_conditional_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_pair_field','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_item_pair_field_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_query_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_query_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_validation_rule','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_validation_rule_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_validation_rule_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('report_validation_rule_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('secondary_diagnosis','deleted','tinyint(1) unsigned not null');
		$this->addColumn('secondary_diagnosis_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('service','deleted','tinyint(1) unsigned not null');
		$this->addColumn('service_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('service_subspecialty_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('service_subspecialty_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_field_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_field_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_firm','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_firm_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_installation','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_installation_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_institution','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_institution_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_metadata','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_metadata_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_site','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_site_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_specialty','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_specialty_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_subspecialty','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_subspecialty_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_user','deleted','tinyint(1) unsigned not null');
		$this->addColumn('setting_user_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_consultant_assignment','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_consultant_assignment_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_anaesthetic_agent','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_anaesthetic_agent_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_anaesthetic_agent_default','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_anaesthetic_agent_default_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_drug','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_drug_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_operative_device','deleted','tinyint(1) unsigned not null');
		$this->addColumn('site_subspecialty_operative_device_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('specialty','deleted','tinyint(1) unsigned not null');
		$this->addColumn('specialty_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('specialty_type','deleted','tinyint(1) unsigned not null');
		$this->addColumn('specialty_type_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('subspecialty','deleted','tinyint(1) unsigned not null');
		$this->addColumn('subspecialty_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('subspecialty_subsection','deleted','tinyint(1) unsigned not null');
		$this->addColumn('subspecialty_subsection_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm_preference','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm_preference_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm_rights','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_firm_rights_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_service_rights','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_service_rights_version','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_site','deleted','tinyint(1) unsigned not null');
		$this->addColumn('user_site_version','deleted','tinyint(1) unsigned not null');
	}

	public function down()
	{
		$this->dropColumn('address','deleted');
		$this->dropColumn('address_version','deleted');
		$this->dropColumn('address_type','deleted');
		$this->dropColumn('address_type_version','deleted');
		$this->dropColumn('allergy','deleted');
		$this->dropColumn('allergy_version','deleted');
		$this->dropColumn('anaesthetic_agent','deleted');
		$this->dropColumn('anaesthetic_agent_version','deleted');
		$this->dropColumn('anaesthetic_complication','deleted');
		$this->dropColumn('anaesthetic_complication_version','deleted');
		$this->dropColumn('anaesthetic_delivery','deleted');
		$this->dropColumn('anaesthetic_delivery_version','deleted');
		$this->dropColumn('anaesthetic_type','deleted');
		$this->dropColumn('anaesthetic_type_version','deleted');
		$this->dropColumn('anaesthetist','deleted');
		$this->dropColumn('anaesthetist_version','deleted');
		$this->dropColumn('benefit','deleted');
		$this->dropColumn('benefit_version','deleted');
		$this->dropColumn('commissioning_body','deleted');
		$this->dropColumn('commissioning_body_version','deleted');
		$this->dropColumn('commissioning_body_patient_assignment','deleted');
		$this->dropColumn('commissioning_body_patient_assignment_version','deleted');
		$this->dropColumn('commissioning_body_practice_assignment','deleted');
		$this->dropColumn('commissioning_body_practice_assignment_version','deleted');
		$this->dropColumn('commissioning_body_service','deleted');
		$this->dropColumn('commissioning_body_service_version','deleted');
		$this->dropColumn('commissioning_body_service_type','deleted');
		$this->dropColumn('commissioning_body_service_type_version','deleted');
		$this->dropColumn('commissioning_body_type','deleted');
		$this->dropColumn('commissioning_body_type_version','deleted');
		$this->dropColumn('common_ophthalmic_disorder','deleted');
		$this->dropColumn('common_ophthalmic_disorder_version','deleted');
		$this->dropColumn('common_previous_operation','deleted');
		$this->dropColumn('common_previous_operation_version','deleted');
		$this->dropColumn('common_systemic_disorder','deleted');
		$this->dropColumn('common_systemic_disorder_version','deleted');
		$this->dropColumn('complication','deleted');
		$this->dropColumn('complication_version','deleted');
		$this->dropColumn('consultant','deleted');
		$this->dropColumn('consultant_version','deleted');
		$this->dropColumn('contact','deleted');
		$this->dropColumn('contact_version','deleted');
		$this->dropColumn('contact_label','deleted');
		$this->dropColumn('contact_label_version','deleted');
		$this->dropColumn('contact_location','deleted');
		$this->dropColumn('contact_location_version','deleted');
		$this->dropColumn('contact_metadata','deleted');
		$this->dropColumn('contact_metadata_version','deleted');
		$this->dropColumn('contact_type','deleted');
		$this->dropColumn('contact_type_version','deleted');
		$this->dropColumn('country','deleted');
		$this->dropColumn('country_version','deleted');
		$this->dropColumn('disorder','deleted');
		$this->dropColumn('disorder_version','deleted');
		$this->dropColumn('disorder_tree','deleted');
		$this->dropColumn('disorder_tree_version','deleted');
		$this->dropColumn('drug','deleted');
		$this->dropColumn('drug_version','deleted');
		$this->dropColumn('drug_allergy_assignment','deleted');
		$this->dropColumn('drug_allergy_assignment_version','deleted');
		$this->dropColumn('drug_duration','deleted');
		$this->dropColumn('drug_duration_version','deleted');
		$this->dropColumn('drug_form','deleted');
		$this->dropColumn('drug_form_version','deleted');
		$this->dropColumn('drug_frequency','deleted');
		$this->dropColumn('drug_frequency_version','deleted');
		$this->dropColumn('drug_route','deleted');
		$this->dropColumn('drug_route_version','deleted');
		$this->dropColumn('drug_route_option','deleted');
		$this->dropColumn('drug_route_option_version','deleted');
		$this->dropColumn('drug_set','deleted');
		$this->dropColumn('drug_set_version','deleted');
		$this->dropColumn('drug_set_item','deleted');
		$this->dropColumn('drug_set_item_version','deleted');
		$this->dropColumn('drug_set_item_taper','deleted');
		$this->dropColumn('drug_set_item_taper_version','deleted');
		$this->dropColumn('drug_type','deleted');
		$this->dropColumn('drug_type_version','deleted');
		$this->dropColumn('element_type','deleted');
		$this->dropColumn('element_type_version','deleted');
		$this->dropColumn('element_type_anaesthetic_agent','deleted');
		$this->dropColumn('element_type_anaesthetic_agent_version','deleted');
		$this->dropColumn('element_type_anaesthetic_complication','deleted');
		$this->dropColumn('element_type_anaesthetic_complication_version','deleted');
		$this->dropColumn('element_type_anaesthetic_delivery','deleted');
		$this->dropColumn('element_type_anaesthetic_delivery_version','deleted');
		$this->dropColumn('element_type_anaesthetic_type','deleted');
		$this->dropColumn('element_type_anaesthetic_type_version','deleted');
		$this->dropColumn('element_type_anaesthetist','deleted');
		$this->dropColumn('element_type_anaesthetist_version','deleted');
		$this->dropColumn('element_type_eye','deleted');
		$this->dropColumn('element_type_eye_version','deleted');
		$this->dropColumn('element_type_priority','deleted');
		$this->dropColumn('element_type_priority_version','deleted');
		$this->dropColumn('episode_status','deleted');
		$this->dropColumn('episode_status_version','deleted');
		$this->dropColumn('ethnic_group','deleted');
		$this->dropColumn('ethnic_group_version','deleted');
		$this->dropColumn('event_group','deleted');
		$this->dropColumn('event_group_version','deleted');
		$this->dropColumn('event_issue','deleted');
		$this->dropColumn('event_issue_version','deleted');
		$this->dropColumn('event_type','deleted');
		$this->dropColumn('event_type_version','deleted');
		$this->dropColumn('family_history','deleted');
		$this->dropColumn('family_history_version','deleted');
		$this->dropColumn('family_history_condition','deleted');
		$this->dropColumn('family_history_condition_version','deleted');
		$this->dropColumn('family_history_relative','deleted');
		$this->dropColumn('family_history_relative_version','deleted');
		$this->dropColumn('family_history_side','deleted');
		$this->dropColumn('family_history_side_version','deleted');
		$this->dropColumn('firm','deleted');
		$this->dropColumn('firm_version','deleted');
		$this->dropColumn('firm_user_assignment','deleted');
		$this->dropColumn('firm_user_assignment_version','deleted');
		$this->dropColumn('gp','deleted');
		$this->dropColumn('gp_version','deleted');
		$this->dropColumn('institution','deleted');
		$this->dropColumn('institution_version','deleted');
		$this->dropColumn('institution_consultant_assignment','deleted');
		$this->dropColumn('institution_consultant_assignment_version','deleted');
		$this->dropColumn('issue','deleted');
		$this->dropColumn('issue_version','deleted');
		$this->dropColumn('language','deleted');
		$this->dropColumn('language_version','deleted');
		$this->dropColumn('manual_contact','deleted');
		$this->dropColumn('manual_contact_version','deleted');
		$this->dropColumn('medication','deleted');
		$this->dropColumn('medication_version','deleted');
		$this->dropColumn('nsc_grade','deleted');
		$this->dropColumn('nsc_grade_version','deleted');
		$this->dropColumn('opcs_code','deleted');
		$this->dropColumn('opcs_code_version','deleted');
		$this->dropColumn('operative_device','deleted');
		$this->dropColumn('operative_device_version','deleted');
		$this->dropColumn('pas_assignment','deleted');
		$this->dropColumn('pas_assignment_version','deleted');
		$this->dropColumn('pas_patient_merged','deleted');
		$this->dropColumn('pas_patient_merged_version','deleted');
		$this->dropColumn('patient','deleted');
		$this->dropColumn('patient_version','deleted');
		$this->dropColumn('patient_allergy_assignment','deleted');
		$this->dropColumn('patient_allergy_assignment_version','deleted');
		$this->dropColumn('patient_contact_assignment','deleted');
		$this->dropColumn('patient_contact_assignment_version','deleted');
		$this->dropColumn('patient_oph_info','deleted');
		$this->dropColumn('patient_oph_info_version','deleted');
		$this->dropColumn('patient_oph_info_cvi_status','deleted');
		$this->dropColumn('patient_oph_info_cvi_status_version','deleted');
		$this->dropColumn('patient_shortcode','deleted');
		$this->dropColumn('patient_shortcode_version','deleted');
		$this->dropColumn('period','deleted');
		$this->dropColumn('period_version','deleted');
		$this->dropColumn('person','deleted');
		$this->dropColumn('person_version','deleted');
		$this->dropColumn('practice','deleted');
		$this->dropColumn('practice_version','deleted');
		$this->dropColumn('previous_operation','deleted');
		$this->dropColumn('previous_operation_version','deleted');
		$this->dropColumn('priority','deleted');
		$this->dropColumn('priority_version','deleted');
		$this->dropColumn('proc','deleted');
		$this->dropColumn('proc_version','deleted');
		$this->dropColumn('proc_opcs_assignment','deleted');
		$this->dropColumn('proc_opcs_assignment_version','deleted');
		$this->dropColumn('proc_subspecialty_assignment','deleted');
		$this->dropColumn('proc_subspecialty_assignment_version','deleted');
		$this->dropColumn('proc_subspecialty_subsection_assignment','deleted');
		$this->dropColumn('proc_subspecialty_subsection_assignment_version','deleted');
		$this->dropColumn('procedure_additional','deleted');
		$this->dropColumn('procedure_additional_version','deleted');
		$this->dropColumn('procedure_benefit','deleted');
		$this->dropColumn('procedure_benefit_version','deleted');
		$this->dropColumn('procedure_complication','deleted');
		$this->dropColumn('procedure_complication_version','deleted');
		$this->dropColumn('protected_file','deleted');
		$this->dropColumn('protected_file_version','deleted');
		$this->dropColumn('referral','deleted');
		$this->dropColumn('referral_version','deleted');
		$this->dropColumn('referral_episode_assignment','deleted');
		$this->dropColumn('referral_episode_assignment_version','deleted');
		$this->dropColumn('referral_type','deleted');
		$this->dropColumn('referral_type_version','deleted');
		$this->dropColumn('report_dataset','deleted');
		$this->dropColumn('report_dataset_version','deleted');
		$this->dropColumn('report_dataset_element','deleted');
		$this->dropColumn('report_dataset_element_version','deleted');
		$this->dropColumn('report_dataset_element_field','deleted');
		$this->dropColumn('report_dataset_element_field_version','deleted');
		$this->dropColumn('report_dataset_element_join','deleted');
		$this->dropColumn('report_dataset_element_join_version','deleted');
		$this->dropColumn('report_dataset_related_entity','deleted');
		$this->dropColumn('report_dataset_related_entity_version','deleted');
		$this->dropColumn('report_dataset_related_entity_table','deleted');
		$this->dropColumn('report_dataset_related_entity_table_version','deleted');
		$this->dropColumn('report_dataset_related_entity_table_relation','deleted');
		$this->dropColumn('report_dataset_related_entity_table_relation_version','deleted');
		$this->dropColumn('report_dataset_related_entity_type','deleted');
		$this->dropColumn('report_dataset_related_entity_type_version','deleted');
		$this->dropColumn('report_graph','deleted');
		$this->dropColumn('report_graph_version','deleted');
		$this->dropColumn('report_graph_item','deleted');
		$this->dropColumn('report_graph_item_version','deleted');
		$this->dropColumn('report_input','deleted');
		$this->dropColumn('report_input_version','deleted');
		$this->dropColumn('report_input_data_type','deleted');
		$this->dropColumn('report_input_data_type_version','deleted');
		$this->dropColumn('report_input_option','deleted');
		$this->dropColumn('report_input_option_version','deleted');
		$this->dropColumn('report_item','deleted');
		$this->dropColumn('report_item_version','deleted');
		$this->dropColumn('report_item_data_type','deleted');
		$this->dropColumn('report_item_data_type_version','deleted');
		$this->dropColumn('report_item_list_item','deleted');
		$this->dropColumn('report_item_list_item_version','deleted');
		$this->dropColumn('report_item_list_item_conditional','deleted');
		$this->dropColumn('report_item_list_item_conditional_version','deleted');
		$this->dropColumn('report_item_pair_field','deleted');
		$this->dropColumn('report_item_pair_field_version','deleted');
		$this->dropColumn('report_query_type','deleted');
		$this->dropColumn('report_query_type_version','deleted');
		$this->dropColumn('report_validation_rule','deleted');
		$this->dropColumn('report_validation_rule_version','deleted');
		$this->dropColumn('report_validation_rule_type','deleted');
		$this->dropColumn('report_validation_rule_type_version','deleted');
		$this->dropColumn('secondary_diagnosis','deleted');
		$this->dropColumn('secondary_diagnosis_version','deleted');
		$this->dropColumn('service','deleted');
		$this->dropColumn('service_version','deleted');
		$this->dropColumn('service_subspecialty_assignment','deleted');
		$this->dropColumn('service_subspecialty_assignment_version','deleted');
		$this->dropColumn('setting_field_type','deleted');
		$this->dropColumn('setting_field_type_version','deleted');
		$this->dropColumn('setting_firm','deleted');
		$this->dropColumn('setting_firm_version','deleted');
		$this->dropColumn('setting_installation','deleted');
		$this->dropColumn('setting_installation_version','deleted');
		$this->dropColumn('setting_institution','deleted');
		$this->dropColumn('setting_institution_version','deleted');
		$this->dropColumn('setting_metadata','deleted');
		$this->dropColumn('setting_metadata_version','deleted');
		$this->dropColumn('setting_site','deleted');
		$this->dropColumn('setting_site_version','deleted');
		$this->dropColumn('setting_specialty','deleted');
		$this->dropColumn('setting_specialty_version','deleted');
		$this->dropColumn('setting_subspecialty','deleted');
		$this->dropColumn('setting_subspecialty_version','deleted');
		$this->dropColumn('setting_user','deleted');
		$this->dropColumn('setting_user_version','deleted');
		$this->dropColumn('site','deleted');
		$this->dropColumn('site_version','deleted');
		$this->dropColumn('site_consultant_assignment','deleted');
		$this->dropColumn('site_consultant_assignment_version','deleted');
		$this->dropColumn('site_subspecialty_anaesthetic_agent','deleted');
		$this->dropColumn('site_subspecialty_anaesthetic_agent_version','deleted');
		$this->dropColumn('site_subspecialty_anaesthetic_agent_default','deleted');
		$this->dropColumn('site_subspecialty_anaesthetic_agent_default_version','deleted');
		$this->dropColumn('site_subspecialty_drug','deleted');
		$this->dropColumn('site_subspecialty_drug_version','deleted');
		$this->dropColumn('site_subspecialty_operative_device','deleted');
		$this->dropColumn('site_subspecialty_operative_device_version','deleted');
		$this->dropColumn('specialty','deleted');
		$this->dropColumn('specialty_version','deleted');
		$this->dropColumn('specialty_type','deleted');
		$this->dropColumn('specialty_type_version','deleted');
		$this->dropColumn('subspecialty','deleted');
		$this->dropColumn('subspecialty_version','deleted');
		$this->dropColumn('subspecialty_subsection','deleted');
		$this->dropColumn('subspecialty_subsection_version','deleted');
		$this->dropColumn('user','deleted');
		$this->dropColumn('user_version','deleted');
		$this->dropColumn('user_firm','deleted');
		$this->dropColumn('user_firm_version','deleted');
		$this->dropColumn('user_firm_preference','deleted');
		$this->dropColumn('user_firm_preference_version','deleted');
		$this->dropColumn('user_firm_rights','deleted');
		$this->dropColumn('user_firm_rights_version','deleted');
		$this->dropColumn('user_service_rights','deleted');
		$this->dropColumn('user_service_rights_version','deleted');
		$this->dropColumn('user_site','deleted');
		$this->dropColumn('user_site_version','deleted');
	}
}
