<?php

class m140110_084630_table_versioning extends OEMigration
{
    public function up()
    {
        $this->renameColumn('ophciexamination_injectmanagecomplex_notreatmentreason', 'enabled', 'active');
        $this->renameColumn('ophciexamination_injectmanagecomplex_question', 'enabled', 'active');
        $this->renameColumn('ophciexamination_injectmanagecomplex_risk', 'enabled', 'active');
        $this->renameColumn('ophciexamination_lasermanagement_lasertype', 'enabled', 'active');
        $this->renameColumn('ophciexamination_oct_fluidtype', 'enabled', 'active');
        $this->renameColumn('ophciexamination_oct_fluidstatus', 'enabled', 'active');

        $this->renameColumn('ophciexamination_visual_acuity_unit', 'tooltip', 'active');

        $this->addColumn('ophciexamination_anteriorsegment_cct_method', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_cataractsurgicalmanagement_sfsurgeon', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_clinicoutcome_role', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_clinicoutcome_status', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_comorbidities_item', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_drgrading_clinicalmaculopathy', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_drgrading_clinicalretinopathy', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_drgrading_nscmaculopathy', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_drgrading_nscretinopathy', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_instrument', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_management_deferralreason', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_management_status', 'active', 'boolean not null default true');
        $this->addColumn('ophciexamination_oct_method', 'active', 'boolean not null default true');

        $this->versionExistingTable('et_ophciexamination_adnexalcomorbidity');
        $this->versionExistingTable('et_ophciexamination_anteriorsegment');
        $this->versionExistingTable('et_ophciexamination_anteriorsegment_cct');
        $this->versionExistingTable('et_ophciexamination_cataractsurgicalmanagement');
        $this->versionExistingTable('et_ophciexamination_clinicoutcome');
        $this->versionExistingTable('et_ophciexamination_comorbidities');
        $this->versionExistingTable('et_ophciexamination_conclusion');
        $this->versionExistingTable('et_ophciexamination_diagnoses');
        $this->versionExistingTable('et_ophciexamination_dilation');
        $this->versionExistingTable('et_ophciexamination_drgrading');
        $this->versionExistingTable('et_ophciexamination_glaucomarisk');
        $this->versionExistingTable('et_ophciexamination_gonioscopy');
        $this->versionExistingTable('et_ophciexamination_history');
        $this->versionExistingTable('et_ophciexamination_injectionmanagement');
        $this->versionExistingTable('et_ophciexamination_injectionmanagementcomplex');
        $this->versionExistingTable('et_ophciexamination_intraocularpressure');
        $this->versionExistingTable('et_ophciexamination_investigation');
        $this->versionExistingTable('et_ophciexamination_lasermanagement');
        $this->versionExistingTable('et_ophciexamination_management');
        $this->versionExistingTable('et_ophciexamination_oct');
        $this->versionExistingTable('et_ophciexamination_opticdisc');
        $this->versionExistingTable('et_ophciexamination_posteriorpole');
        $this->versionExistingTable('et_ophciexamination_pupillaryabnormalities');
        $this->versionExistingTable('et_ophciexamination_refraction');
        $this->versionExistingTable('et_ophciexamination_risks');
        $this->versionExistingTable('et_ophciexamination_visualacuity');
        $this->versionExistingTable('ophciexamination_anteriorsegment_cct_method');
        $this->versionExistingTable('ophciexamination_anteriorsegment_cortical');
        $this->versionExistingTable('ophciexamination_anteriorsegment_nuclear');
        $this->versionExistingTable('ophciexamination_anteriorsegment_pupil');
        $this->versionExistingTable('ophciexamination_attribute');
        $this->versionExistingTable('ophciexamination_attribute_element');
        $this->versionExistingTable('ophciexamination_attribute_option');
        $this->versionExistingTable('ophciexamination_cataractsurgicalmanagement_eye');
        $this->versionExistingTable('ophciexamination_cataractsurgicalmanagement_sfsurgeon');
        $this->versionExistingTable('ophciexamination_clinicoutcome_role');
        $this->versionExistingTable('ophciexamination_clinicoutcome_status');
        $this->versionExistingTable('ophciexamination_clinicoutcome_template');
        $this->versionExistingTable('ophciexamination_comorbidities_assignment');
        $this->versionExistingTable('ophciexamination_comorbidities_item');
        $this->versionExistingTable('ophciexamination_diagnosis');
        $this->versionExistingTable('ophciexamination_dilation_drugs');
        $this->versionExistingTable('ophciexamination_dilation_treatment');
        $this->versionExistingTable('ophciexamination_drgrading_clinicalmaculopathy');
        $this->versionExistingTable('ophciexamination_drgrading_clinicalretinopathy');
        $this->versionExistingTable('ophciexamination_drgrading_nscmaculopathy');
        $this->versionExistingTable('ophciexamination_drgrading_nscretinopathy');
        $this->versionExistingTable('ophciexamination_element_set');
        $this->versionExistingTable('ophciexamination_element_set_item');
        $this->versionExistingTable('ophciexamination_workflow_rule');
        $this->versionExistingTable('ophciexamination_event_elementset_assignment');
        $this->versionExistingTable('ophciexamination_glaucomarisk_risk');
        $this->versionExistingTable('ophciexamination_gonioscopy_description');
        $this->versionExistingTable('ophciexamination_gonioscopy_van_herick');
        $this->versionExistingTable('ophciexamination_injectmanagecomplex_answer');
        $this->versionExistingTable('ophciexamination_injectmanagecomplex_notreatmentreason');
        $this->versionExistingTable('ophciexamination_injectmanagecomplex_question');
        $this->versionExistingTable('ophciexamination_injectmanagecomplex_risk');
        $this->versionExistingTable('ophciexamination_injectmanagecomplex_risk_assignment');
        $this->versionExistingTable('ophciexamination_instrument');
        $this->versionExistingTable('ophciexamination_intraocularpressure_reading');
        $this->versionExistingTable('ophciexamination_lasermanagement_lasertype');
        $this->versionExistingTable('ophciexamination_management_deferralreason');
        $this->versionExistingTable('ophciexamination_management_status');
        $this->versionExistingTable('ophciexamination_oct_fluidstatus');
        $this->versionExistingTable('ophciexamination_oct_fluidtype');
        $this->versionExistingTable('ophciexamination_oct_fluidtype_assignment');
        $this->versionExistingTable('ophciexamination_oct_method');
        $this->versionExistingTable('ophciexamination_opticdisc_cd_ratio');
        $this->versionExistingTable('ophciexamination_opticdisc_lens');
        $this->versionExistingTable('ophciexamination_pupillaryabnormalities_abnormality');
        $this->versionExistingTable('ophciexamination_refraction_fraction');
        $this->versionExistingTable('ophciexamination_refraction_integer');
        $this->versionExistingTable('ophciexamination_refraction_sign');
        $this->versionExistingTable('ophciexamination_refraction_type');
        $this->versionExistingTable('ophciexamination_visual_acuity_unit');
        $this->versionExistingTable('ophciexamination_visual_acuity_unit_value');
        $this->versionExistingTable('ophciexamination_visualacuity_method');
        $this->versionExistingTable('ophciexamination_visualacuity_reading');
        $this->versionExistingTable('ophciexamination_workflow');
    }

    public function down()
    {
        $this->dropTable('et_ophciexamination_adnexalcomorbidity_version');
        $this->dropTable('et_ophciexamination_anteriorsegment_version');
        $this->dropTable('et_ophciexamination_anteriorsegment_cct_version');
        $this->dropTable('et_ophciexamination_cataractsurgicalmanagement_version');
        $this->dropTable('et_ophciexamination_clinicoutcome_version');
        $this->dropTable('et_ophciexamination_comorbidities_version');
        $this->dropTable('et_ophciexamination_conclusion_version');
        $this->dropTable('et_ophciexamination_diagnoses_version');
        $this->dropTable('et_ophciexamination_dilation_version');
        $this->dropTable('et_ophciexamination_drgrading_version');
        $this->dropTable('et_ophciexamination_glaucomarisk_version');
        $this->dropTable('et_ophciexamination_gonioscopy_version');
        $this->dropTable('et_ophciexamination_history_version');
        $this->dropTable('et_ophciexamination_injectionmanagement_version');
        $this->dropTable('et_ophciexamination_injectionmanagementcomplex_version');
        $this->dropTable('et_ophciexamination_intraocularpressure_version');
        $this->dropTable('et_ophciexamination_investigation_version');
        $this->dropTable('et_ophciexamination_lasermanagement_version');
        $this->dropTable('et_ophciexamination_management_version');
        $this->dropTable('et_ophciexamination_oct_version');
        $this->dropTable('et_ophciexamination_opticdisc_version');
        $this->dropTable('et_ophciexamination_posteriorpole_version');
        $this->dropTable('et_ophciexamination_pupillaryabnormalities_version');
        $this->dropTable('et_ophciexamination_refraction_version');
        $this->dropTable('et_ophciexamination_risks_version');
        $this->dropTable('et_ophciexamination_visualacuity_version');
        $this->dropTable('ophciexamination_anteriorsegment_cct_method_version');
        $this->dropTable('ophciexamination_anteriorsegment_cortical_version');
        $this->dropTable('ophciexamination_anteriorsegment_nuclear_version');
        $this->dropTable('ophciexamination_anteriorsegment_pupil_version');
        $this->dropTable('ophciexamination_attribute_version');
        $this->dropTable('ophciexamination_attribute_element_version');
        $this->dropTable('ophciexamination_attribute_option_version');
        $this->dropTable('ophciexamination_cataractsurgicalmanagement_eye_version');
        $this->dropTable('ophciexamination_cataractsurgicalmanagement_sfsurgeon_version');
        $this->dropTable('ophciexamination_clinicoutcome_role_version');
        $this->dropTable('ophciexamination_clinicoutcome_status_version');
        $this->dropTable('ophciexamination_clinicoutcome_template_version');
        $this->dropTable('ophciexamination_comorbidities_assignment_version');
        $this->dropTable('ophciexamination_comorbidities_item_version');
        $this->dropTable('ophciexamination_diagnosis_version');
        $this->dropTable('ophciexamination_dilation_drugs_version');
        $this->dropTable('ophciexamination_dilation_treatment_version');
        $this->dropTable('ophciexamination_drgrading_clinicalmaculopathy_version');
        $this->dropTable('ophciexamination_drgrading_clinicalretinopathy_version');
        $this->dropTable('ophciexamination_drgrading_nscmaculopathy_version');
        $this->dropTable('ophciexamination_drgrading_nscretinopathy_version');
        $this->dropTable('ophciexamination_element_set_version');
        $this->dropTable('ophciexamination_element_set_item_version');
        $this->dropTable('ophciexamination_element_set_rule_version');
        $this->dropTable('ophciexamination_event_elementset_assignment_version');
        $this->dropTable('ophciexamination_glaucomarisk_risk_version');
        $this->dropTable('ophciexamination_gonioscopy_description_version');
        $this->dropTable('ophciexamination_gonioscopy_van_herick_version');
        $this->dropTable('ophciexamination_injectmanagecomplex_answer_version');
        $this->dropTable('ophciexamination_injectmanagecomplex_notreatmentreason_version');
        $this->dropTable('ophciexamination_injectmanagecomplex_question_version');
        $this->dropTable('ophciexamination_injectmanagecomplex_risk_version');
        $this->dropTable('ophciexamination_injectmanagecomplex_risk_assignment_version');
        $this->dropTable('ophciexamination_instrument_version');
        $this->dropTable('ophciexamination_intraocularpressure_reading_version');
        $this->dropTable('ophciexamination_lasermanagement_lasertype_version');
        $this->dropTable('ophciexamination_management_deferralreason_version');
        $this->dropTable('ophciexamination_management_status_version');
        $this->dropTable('ophciexamination_oct_fluidstatus_version');
        $this->dropTable('ophciexamination_oct_fluidtype_version');
        $this->dropTable('ophciexamination_oct_fluidtype_assignment_version');
        $this->dropTable('ophciexamination_oct_method_version');
        $this->dropTable('ophciexamination_opticdisc_cd_ratio_version');
        $this->dropTable('ophciexamination_opticdisc_lens_version');
        $this->dropTable('ophciexamination_pupillaryabnormalities_abnormality_version');
        $this->dropTable('ophciexamination_refraction_fraction_version');
        $this->dropTable('ophciexamination_refraction_integer_version');
        $this->dropTable('ophciexamination_refraction_sign_version');
        $this->dropTable('ophciexamination_refraction_type_version');
        $this->dropTable('ophciexamination_visual_acuity_unit_version');
        $this->dropTable('ophciexamination_visual_acuity_unit_value_version');
        $this->dropTable('ophciexamination_visualacuity_method_version');
        $this->dropTable('ophciexamination_visualacuity_reading_version');
        $this->dropTable('ophciexamination_workflow_version');

        $this->dropColumn('ophciexamination_anteriorsegment_cct_method', 'active');
        $this->dropColumn('ophciexamination_cataractsurgicalmanagement_sfsurgeon', 'active');
        $this->dropColumn('ophciexamination_clinicoutcome_role', 'active');
        $this->dropColumn('ophciexamination_clinicoutcome_status', 'active');
        $this->dropColumn('ophciexamination_comorbidities_item', 'active');
        $this->dropColumn('ophciexamination_drgrading_clinicalmaculopathy', 'active');
        $this->dropColumn('ophciexamination_drgrading_clinicalretinopathy', 'active');
        $this->dropColumn('ophciexamination_drgrading_nscmaculopathy', 'active');
        $this->dropColumn('ophciexamination_drgrading_nscretinopathy', 'active');
        $this->dropColumn('ophciexamination_instrument', 'active');
        $this->dropColumn('ophciexamination_management_deferralreason', 'active');
        $this->dropColumn('ophciexamination_management_status', 'active');
        $this->dropColumn('ophciexamination_oct_method', 'active');

        $this->renameColumn('ophciexamination_visual_acuity_unit', 'active', 'tooltip');

        $this->renameColumn('ophciexamination_injectmanagecomplex_notreatmentreason', 'active', 'enabled');
        $this->renameColumn('ophciexamination_injectmanagecomplex_question', 'active', 'enabled');
        $this->renameColumn('ophciexamination_injectmanagecomplex_risk', 'active', 'enabled');
        $this->renameColumn('ophciexamination_lasermanagement_lasertype', 'active', 'enabled');
        $this->renameColumn('ophciexamination_oct_fluidtype', 'active', 'enabled');
        $this->renameColumn('ophciexamination_oct_fluidstatus', 'active', 'enabled');
    }
}
