use openeyes;
/* disable foreigh key check*/
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE address_type_version;
 SELECT "TRUNCATE TABLE address_type_version" AS "";
TRUNCATE TABLE address_version;
 SELECT "TRUNCATE TABLE address_version" AS "";
TRUNCATE TABLE anaesthetic_agent_version;
 SELECT "TRUNCATE TABLE anaesthetic_agent_version" AS "";
TRUNCATE TABLE anaesthetic_complication_version;
 SELECT "TRUNCATE TABLE anaesthetic_complication_version" AS "";
TRUNCATE TABLE anaesthetic_delivery_version;
 SELECT "TRUNCATE TABLE anaesthetic_delivery_version" AS "";
TRUNCATE TABLE anaesthetic_type_version;
 SELECT "TRUNCATE TABLE anaesthetic_type_version" AS "";
TRUNCATE TABLE anaesthetist_version;
 SELECT "TRUNCATE TABLE anaesthetist_version" AS "";
TRUNCATE TABLE automatic_examination_event_log_version;
 SELECT "TRUNCATE TABLE automatic_examination_event_log_version" AS "";
--  TRUNCATE TABLE archive_patient_allergy_assignment_version;
--  SELECT "TRUNCATE TABLE archive_patient_allergy_assignment_version" AS "";
-- TRUNCATE TABLE archive_patient_risk_assignment_version;
--  SELECT "TRUNCATE TABLE archive_patient_risk_assignment_version" AS "";
TRUNCATE TABLE benefit_version;
 SELECT "TRUNCATE TABLE benefit_version" AS "";
TRUNCATE TABLE commissioning_body_patient_assignment_version;
 SELECT "TRUNCATE TABLE commissioning_body_patient_assignment_version" AS "";
TRUNCATE TABLE commissioning_body_practice_assignment_version;
 SELECT "TRUNCATE TABLE commissioning_body_practice_assignment_version" AS "";
TRUNCATE TABLE commissioning_body_service_type_version;
 SELECT "TRUNCATE TABLE commissioning_body_service_type_version" AS "";
TRUNCATE TABLE commissioning_body_service_version;
 SELECT "TRUNCATE TABLE commissioning_body_service_version" AS "";
TRUNCATE TABLE commissioning_body_type_version;
 SELECT "TRUNCATE TABLE commissioning_body_type_version" AS "";
TRUNCATE TABLE commissioning_body_version;
 SELECT "TRUNCATE TABLE commissioning_body_version" AS "";
TRUNCATE TABLE common_ophthalmic_disorder_group_version;
 SELECT "TRUNCATE TABLE common_ophthalmic_disorder_group_version" AS "";
TRUNCATE TABLE common_ophthalmic_disorder_version;
 SELECT "TRUNCATE TABLE common_ophthalmic_disorder_version" AS "";
TRUNCATE TABLE common_previous_operation_version;
 SELECT "TRUNCATE TABLE common_previous_operation_version" AS "";
TRUNCATE TABLE common_systemic_disorder_version;
 SELECT "TRUNCATE TABLE common_systemic_disorder_version" AS "";
TRUNCATE TABLE complication_version;
 SELECT "TRUNCATE TABLE complication_version" AS "";
TRUNCATE TABLE contact_label_version;
 SELECT "TRUNCATE TABLE contact_label_version" AS "";
TRUNCATE TABLE contact_location_version;
 SELECT "TRUNCATE TABLE contact_location_version" AS "";
TRUNCATE TABLE contact_metadata_version;
 SELECT "TRUNCATE TABLE contact_metadata_version" AS "";
TRUNCATE TABLE contact_practice_associate_version;
 SELECT "TRUNCATE TABLE contact_practice_associate_version" AS "";
TRUNCATE TABLE contact_version;
 SELECT "TRUNCATE TABLE contact_version" AS "";
TRUNCATE TABLE country_version;
 SELECT "TRUNCATE TABLE country_version" AS "";
TRUNCATE TABLE disorder_tree_version;
 SELECT "TRUNCATE TABLE disorder_tree_version" AS "";
TRUNCATE TABLE disorder_version;
 SELECT "TRUNCATE TABLE disorder_version" AS "";
TRUNCATE TABLE document_instance_data_version;
 SELECT "TRUNCATE TABLE document_instance_data_version" AS "";
TRUNCATE TABLE document_instance_version;
 SELECT "TRUNCATE TABLE document_instance_version" AS "";
TRUNCATE TABLE document_output_version;
 SELECT "TRUNCATE TABLE document_output_version" AS "";
TRUNCATE TABLE document_set_version;
 SELECT "TRUNCATE TABLE document_set_version" AS "";
TRUNCATE TABLE document_target_version;
 SELECT "TRUNCATE TABLE document_target_version" AS "";
TRUNCATE TABLE drug_allergy_assignment_version;
 SELECT "TRUNCATE TABLE drug_allergy_assignment_version" AS "";
TRUNCATE TABLE drug_duration_version;
 SELECT "TRUNCATE TABLE drug_duration_version" AS "";
TRUNCATE TABLE drug_form_version;
 SELECT "TRUNCATE TABLE drug_form_version" AS "";
TRUNCATE TABLE drug_frequency_version;
 SELECT "TRUNCATE TABLE drug_frequency_version" AS "";
TRUNCATE TABLE drug_route_option_version;
 SELECT "TRUNCATE TABLE drug_route_option_version" AS "";
TRUNCATE TABLE drug_route_version;
 SELECT "TRUNCATE TABLE drug_route_version" AS "";
TRUNCATE TABLE drug_set_item_taper_version;
 SELECT "TRUNCATE TABLE drug_set_item_taper_version" AS "";
TRUNCATE TABLE drug_set_item_version;
 SELECT "TRUNCATE TABLE drug_set_item_version" AS "";
TRUNCATE TABLE drug_set_version;
 SELECT "TRUNCATE TABLE drug_set_version" AS "";
TRUNCATE TABLE drug_tag_version;
 SELECT "TRUNCATE TABLE drug_tag_version" AS "";
TRUNCATE TABLE drug_type_version;
 SELECT "TRUNCATE TABLE drug_type_version" AS "";
TRUNCATE TABLE drug_version;
 SELECT "TRUNCATE TABLE drug_version" AS "";
TRUNCATE TABLE element_group_version;
 SELECT "TRUNCATE TABLE element_group_version" AS "";
TRUNCATE TABLE element_type_version;
 SELECT "TRUNCATE TABLE element_type_version" AS "";
TRUNCATE TABLE episode_status_version;
 SELECT "TRUNCATE TABLE episode_status_version" AS "";
TRUNCATE TABLE episode_version;
 SELECT "TRUNCATE TABLE episode_version" AS "";
TRUNCATE TABLE et_ophcididnotattend_comments_version;
 SELECT "TRUNCATE TABLE et_ophcididnotattend_comments_version" AS "";
TRUNCATE TABLE et_ophciexamination_adnexalcomorbidity_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_adnexalcomorbidity_version" AS "";
TRUNCATE TABLE et_ophciexamination_allergies_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_allergies_version" AS "";
TRUNCATE TABLE et_ophciexamination_allergy_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_allergy_version" AS "";
TRUNCATE TABLE et_ophciexamination_anteriorsegment_cct_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_anteriorsegment_cct_version" AS "";
TRUNCATE TABLE et_ophciexamination_anteriorsegment_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_anteriorsegment_version" AS "";
TRUNCATE TABLE et_ophciexamination_bleb_assessment_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_bleb_assessment_version" AS "";
TRUNCATE TABLE et_ophciexamination_cataractsurgicalmanagement_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_cataractsurgicalmanagement_version" AS "";
TRUNCATE TABLE et_ophciexamination_clinicoutcome_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_clinicoutcome_version" AS "";
TRUNCATE TABLE et_ophciexamination_colourvision_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_colourvision_version" AS "";
TRUNCATE TABLE et_ophciexamination_comorbidities_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_comorbidities_version" AS "";
TRUNCATE TABLE et_ophciexamination_conclusion_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_conclusion_version" AS "";
TRUNCATE TABLE et_ophciexamination_currentmanagementplan_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_currentmanagementplan_version" AS "";
TRUNCATE TABLE et_ophciexamination_cvi_status_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_cvi_status_version" AS "";
TRUNCATE TABLE et_ophciexamination_cxl_history_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_cxl_history_version" AS "";
TRUNCATE TABLE et_ophciexamination_cxl_outcome_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_cxl_outcome_version" AS "";
TRUNCATE TABLE et_ophciexamination_diagnoses_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_diagnoses_version" AS "";
TRUNCATE TABLE et_ophciexamination_dilation_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_dilation_version" AS "";
TRUNCATE TABLE et_ophciexamination_drgrading_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_drgrading_version" AS "";
TRUNCATE TABLE et_ophciexamination_examinationrisk_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_examinationrisk_version" AS "";
TRUNCATE TABLE et_ophciexamination_familyhistory_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_familyhistory_version" AS "";
TRUNCATE TABLE et_ophciexamination_fundus_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_fundus_version" AS "";
TRUNCATE TABLE et_ophciexamination_further_findings_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_further_findings_version" AS "";
TRUNCATE TABLE et_ophciexamination_glaucomarisk_version;
 SELECT "TRUNCATE TABLEet_ophciexamination_glaucomarisk_version " AS "";
TRUNCATE TABLE et_ophciexamination_gonioscopy_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_gonioscopy_version" AS "";
TRUNCATE TABLE et_ophciexamination_history_medications_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_history_medications_version" AS "";
TRUNCATE TABLE et_ophciexamination_history_risks_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_history_risks_version" AS "";
TRUNCATE TABLE et_ophciexamination_history_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_history_version" AS "";
TRUNCATE TABLE et_ophciexamination_injectionmanagement_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_injectionmanagement_version" AS "";
TRUNCATE TABLE et_ophciexamination_injectionmanagementcomplex_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_injectionmanagementcomplex_version" AS "";
TRUNCATE TABLE et_ophciexamination_intraocularpressure_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_intraocularpressure_version" AS "";
TRUNCATE TABLE et_ophciexamination_investigation_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_investigation_version" AS "";
TRUNCATE TABLE et_ophciexamination_keratometry_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_keratometry_version" AS "";
TRUNCATE TABLE et_ophciexamination_lasermanagement_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_lasermanagement_version" AS "";
TRUNCATE TABLE et_ophciexamination_management_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_management_version" AS "";
TRUNCATE TABLE et_ophciexamination_medical_lids_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_medical_lids_version" AS "";
TRUNCATE TABLE et_ophciexamination_nearvisualacuity_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_nearvisualacuity_version" AS "";
TRUNCATE TABLE et_ophciexamination_observations_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_observations_version" AS "";
TRUNCATE TABLE et_ophciexamination_oct_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_oct_version" AS "";
TRUNCATE TABLE et_ophciexamination_opticdisc_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_opticdisc_version" AS "";
TRUNCATE TABLE et_ophciexamination_optom_comments_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_optom_comments_version" AS "";
TRUNCATE TABLE et_ophciexamination_overallmanagementplan_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_overallmanagementplan_version" AS "";
TRUNCATE TABLE et_ophciexamination_pastsurgery_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_pastsurgery_version" AS "";
TRUNCATE TABLE et_ophciexamination_pcr_risk_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_pcr_risk_version" AS "";
TRUNCATE TABLE et_ophciexamination_posteriorpole_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_posteriorpole_version" AS "";
TRUNCATE TABLE et_ophciexamination_postop_complications_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_postop_complications_version" AS "";
TRUNCATE TABLE et_ophciexamination_pupillaryabnormalities_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_pupillaryabnormalities_version" AS "";
TRUNCATE TABLE et_ophciexamination_refraction_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_refraction_version" AS "";
TRUNCATE TABLE et_ophciexamination_risks_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_risks_version" AS "";
TRUNCATE TABLE et_ophciexamination_slit_lamp_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_slit_lamp_version" AS "";
TRUNCATE TABLE et_ophciexamination_socialhistory_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_socialhistory_version" AS "";
TRUNCATE TABLE et_ophciexamination_specular_microscopy_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_specular_microscopy_version" AS "";
TRUNCATE TABLE et_ophciexamination_surgical_lids_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_surgical_lids_version" AS "";
TRUNCATE TABLE et_ophciexamination_systemic_diagnoses_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_systemic_diagnoses_version" AS "";
TRUNCATE TABLE et_ophciexamination_van_herick_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_van_herick_version" AS "";
TRUNCATE TABLE et_ophciexamination_visualacuity_version;
 SELECT "TRUNCATE TABLE et_ophciexamination_visualacuity_version" AS "";
TRUNCATE TABLE et_ophciphasing_intraocularpressure_version;
 SELECT "TRUNCATE TABLE et_ophciphasing_intraocularpressure_version" AS "";
TRUNCATE TABLE et_ophcocorrespondence_letter_version;
 SELECT "TRUNCATE TABLE et_ophcocorrespondence_letter_version" AS "";
TRUNCATE TABLE et_ophcocvi_clericinfo_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_clericinfo_version" AS "";
TRUNCATE TABLE et_ophcocvi_clinicinfo_disorder_assignment_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_clinicinfo_disorder_assignment_version" AS "";
TRUNCATE TABLE et_ophcocvi_clinicinfo_disorder_section_comment_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_clinicinfo_disorder_section_comment_version" AS "";
TRUNCATE TABLE et_ophcocvi_clinicinfo_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_clinicinfo_version" AS "";
TRUNCATE TABLE et_ophcocvi_consentsig_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_consentsig_version" AS "";
TRUNCATE TABLE et_ophcocvi_demographics_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_demographics_version" AS "";
TRUNCATE TABLE et_ophcocvi_eventinfo_version;
 SELECT "TRUNCATE TABLE et_ophcocvi_eventinfo_version" AS "";
TRUNCATE TABLE et_ophcodocument_document_version;
 SELECT "TRUNCATE TABLE et_ophcodocument_document_version" AS "";
TRUNCATE TABLE et_ophcomessaging_message_version;
 SELECT "TRUNCATE TABLE et_ophcomessaging_message_version" AS "";
TRUNCATE TABLE et_ophcotherapya_exceptional_version;
 SELECT "TRUNCATE TABLE et_ophcotherapya_exceptional_version" AS "";
TRUNCATE TABLE et_ophcotherapya_mrservicein_version;
 SELECT "TRUNCATE TABLE et_ophcotherapya_mrservicein_version" AS "";
TRUNCATE TABLE et_ophcotherapya_patientsuit_version;
 SELECT "TRUNCATE TABLE et_ophcotherapya_patientsuit_version" AS "";
TRUNCATE TABLE et_ophcotherapya_relativecon_version;
 SELECT "TRUNCATE TABLE et_ophcotherapya_relativecon_version" AS "";
TRUNCATE TABLE et_ophcotherapya_therapydiag_version;
 SELECT "TRUNCATE TABLE et_ophcotherapya_therapydiag_version" AS "";
TRUNCATE TABLE et_ophdrprescription_details_version;
 SELECT "TRUNCATE TABLE et_ophdrprescription_details_version" AS "";
TRUNCATE TABLE et_ophinbiometry_biometrydat_version;
 SELECT "TRUNCATE TABLE et_ophinbiometry_biometrydat_version" AS "";
TRUNCATE TABLE et_ophinbiometry_calculation_version;
 SELECT "TRUNCATE TABLE et_ophinbiometry_calculation_version" AS "";
TRUNCATE TABLE et_ophinbiometry_iol_ref_values_version;
 SELECT "TRUNCATE TABLE et_ophinbiometry_iol_ref_values_version" AS "";
TRUNCATE TABLE et_ophinbiometry_measurement_version;
 SELECT "TRUNCATE TABLE et_ophinbiometry_measurement_version" AS "";
TRUNCATE TABLE et_ophinbiometry_selection_version;
 SELECT "TRUNCATE TABLE et_ophinbiometry_selection_version" AS "";
TRUNCATE TABLE et_ophinlabresults_details_version;
 SELECT "TRUNCATE TABLE et_ophinlabresults_details_version" AS "";
TRUNCATE TABLE et_ophinlabresults_result_timed_numeric_version;
 SELECT "TRUNCATE TABLE et_ophinlabresults_result_timed_numeric_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_comments_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_comments_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_condition_ability_assignment_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_condition_ability_assignment_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_condition_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_condition_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_image_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_image_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_result_assessment_assignment_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_result_assessment_assignment_version" AS "";
TRUNCATE TABLE et_ophinvisualfields_result_version;
 SELECT "TRUNCATE TABLE et_ophinvisualfields_result_version" AS "";
TRUNCATE TABLE et_ophleepatientletter_epatientletter_version;
 SELECT "TRUNCATE TABLE et_ophleepatientletter_epatientletter_version" AS "";
TRUNCATE TABLE et_ophleinjection_injection_version;
 SELECT "TRUNCATE TABLE et_ophleinjection_injection_version" AS "";
TRUNCATE TABLE et_ophouanaestheticsataudit_anaesthetis_version;
 SELECT "TRUNCATE TABLE et_ophouanaestheticsataudit_anaesthetis_version" AS "";
TRUNCATE TABLE et_ophouanaestheticsataudit_notes_version;
 SELECT "TRUNCATE TABLE et_ophouanaestheticsataudit_notes_version" AS "";
TRUNCATE TABLE et_ophouanaestheticsataudit_satisfactio_version;
 SELECT "TRUNCATE TABLE et_ophouanaestheticsataudit_satisfactio_version" AS "";
TRUNCATE TABLE et_ophouanaestheticsataudit_vitalsigns_version;
 SELECT "TRUNCATE TABLE et_ophouanaestheticsataudit_vitalsigns_version" AS "";
TRUNCATE TABLE et_ophtrconsent_benfitrisk_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_benfitrisk_version" AS "";
TRUNCATE TABLE et_ophtrconsent_leaflets_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_leaflets_version" AS "";
TRUNCATE TABLE et_ophtrconsent_other_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_other_version" AS "";
TRUNCATE TABLE et_ophtrconsent_permissions_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_permissions_version" AS "";
TRUNCATE TABLE et_ophtrconsent_procedure_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_procedure_version" AS "";
TRUNCATE TABLE et_ophtrconsent_type_version;
 SELECT "TRUNCATE TABLE et_ophtrconsent_type_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_anaesthetic_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_anaesthetic_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_anteriorseg_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_anteriorseg_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_complications_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_complications_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_postinject_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_postinject_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_site_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_site_version" AS "";
TRUNCATE TABLE et_ophtrintravitinjection_treatment_version;
 SELECT "TRUNCATE TABLE et_ophtrintravitinjection_treatment_version" AS "";
TRUNCATE TABLE et_ophtrlaser_anteriorseg_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_anteriorseg_version" AS "";
TRUNCATE TABLE et_ophtrlaser_comments_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_comments_version" AS "";
TRUNCATE TABLE et_ophtrlaser_fundus_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_fundus_version" AS "";
TRUNCATE TABLE et_ophtrlaser_posteriorpo_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_posteriorpo_version" AS "";
TRUNCATE TABLE et_ophtrlaser_site_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_site_version" AS "";
TRUNCATE TABLE et_ophtrlaser_treatment_version;
 SELECT "TRUNCATE TABLE et_ophtrlaser_treatment_version" AS "";
TRUNCATE TABLE et_ophtroperationbooking_contact_details_version;
 SELECT "TRUNCATE TABLE et_ophtroperationbooking_contact_details_version" AS "";
TRUNCATE TABLE et_ophtroperationbooking_diagnosis_version;
 SELECT "TRUNCATE TABLE et_ophtroperationbooking_diagnosis_version" AS "";
TRUNCATE TABLE et_ophtroperationbooking_operation_version;
 SELECT "TRUNCATE TABLE et_ophtroperationbooking_operation_version" AS "";
TRUNCATE TABLE et_ophtroperationbooking_scheduleope_version;
 SELECT "TRUNCATE TABLE et_ophtroperationbooking_scheduleope_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_anaesthetic_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_anaesthetic_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_buckle_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_buckle_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_cataract_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_cataract_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_comments_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_comments_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_cxl_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_cxl_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_genericprocedure_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_genericprocedure_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_glaucomatube_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_glaucomatube_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_membrane_peel_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_membrane_peel_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_mmc_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_mmc_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_postop_drugs_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_postop_drugs_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_procedurelist_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_procedurelist_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_site_theatre_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_site_theatre_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_surgeon_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_surgeon_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_tamponade_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_tamponade_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_trabectome_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_trabectome_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_trabeculectomy_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_trabeculectomy_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_vitrectomy_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_vitrectomy_version" AS "";
TRUNCATE TABLE et_ophtroperationnote_vte_assessment_version;
 SELECT "TRUNCATE TABLE et_ophtroperationnote_vte_assessment_version" AS "";
TRUNCATE TABLE ethnic_group_version;
 SELECT "TRUNCATE TABLE ethnic_group_version" AS "";
TRUNCATE TABLE event_group_version;
 SELECT "TRUNCATE TABLE event_group_version" AS "";
TRUNCATE TABLE event_issue_version;
 SELECT "TRUNCATE TABLE event_issue_version" AS "";
TRUNCATE TABLE event_type_version;
 SELECT "TRUNCATE TABLE event_type_version" AS "";
TRUNCATE TABLE event_version;
 SELECT "TRUNCATE TABLE event_version" AS "";
TRUNCATE TABLE finding_version;
 SELECT "TRUNCATE TABLE finding_version" AS "";
TRUNCATE TABLE findings_subspec_assignment_version;
 SELECT "TRUNCATE TABLE findings_subspec_assignment_version" AS "";
TRUNCATE TABLE firm_user_assignment_version;
 SELECT "TRUNCATE TABLE firm_user_assignment_version" AS "";
TRUNCATE TABLE firm_version;
 SELECT "TRUNCATE TABLE firm_version" AS "";
TRUNCATE TABLE gp_version;
 SELECT "TRUNCATE TABLE gp_version" AS "";
TRUNCATE TABLE institution_version;
 SELECT "TRUNCATE TABLE institution_version" AS "";
TRUNCATE TABLE issue_version;
 SELECT "TRUNCATE TABLE issue_version" AS "";
TRUNCATE TABLE language_version;
 SELECT "TRUNCATE TABLE language_version" AS "";
TRUNCATE TABLE measurement_reference_version;
 SELECT "TRUNCATE TABLE measurement_reference_version" AS "";
TRUNCATE TABLE measurement_type_version;
 SELECT "TRUNCATE TABLE measurement_type_version" AS "";
TRUNCATE TABLE media_data_version;
 SELECT "TRUNCATE TABLE media_data_version" AS "";
TRUNCATE TABLE media_type_version;
 SELECT "TRUNCATE TABLE media_type_version" AS "";
TRUNCATE TABLE medication_adherence_level_version;
 SELECT "TRUNCATE TABLE medication_adherence_level_version" AS "";
TRUNCATE TABLE medication_common_version;
 SELECT "TRUNCATE TABLE medication_common_version" AS "";
TRUNCATE TABLE medication_drug_tag_version;
 SELECT "TRUNCATE TABLE medication_drug_tag_version" AS "";
TRUNCATE TABLE medication_drug_version;
 SELECT "TRUNCATE TABLE medication_drug_version" AS "";
TRUNCATE TABLE nsc_grade_version;
 SELECT "TRUNCATE TABLE nsc_grade_version" AS "";
TRUNCATE TABLE opcs_code_version;
 SELECT "TRUNCATE TABLE opcs_code_version" AS "";
TRUNCATE TABLE operative_device_version;
 SELECT "TRUNCATE TABLE operative_device_version" AS "";
TRUNCATE TABLE ophciexamination_allergy_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_allergy_entry_version" AS "";
TRUNCATE TABLE ophciexamination_allergy_set_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_allergy_set_entry_version" AS "";
TRUNCATE TABLE ophciexamination_allergy_set_version;
 SELECT "TRUNCATE TABLE ophciexamination_allergy_set_version" AS "";
TRUNCATE TABLE ophciexamination_allergy_version;
 SELECT "TRUNCATE TABLE ophciexamination_allergy_version" AS "";
TRUNCATE TABLE ophciexamination_anteriorsegment_cct_method_version;
 SELECT "TRUNCATE TABLE ophciexamination_anteriorsegment_cct_method_version" AS "";
TRUNCATE TABLE ophciexamination_anteriorsegment_cortical_version;
 SELECT "TRUNCATE TABLE ophciexamination_anteriorsegment_cortical_version" AS "";
TRUNCATE TABLE ophciexamination_anteriorsegment_nuclear_version;
 SELECT "TRUNCATE TABLE ophciexamination_anteriorsegment_nuclear_version" AS "";
TRUNCATE TABLE ophciexamination_anteriorsegment_pupil_version;
 SELECT "TRUNCATE TABLE ophciexamination_anteriorsegment_pupil_version" AS "";
TRUNCATE TABLE ophciexamination_attribute_element_version;
 SELECT "TRUNCATE TABLE ophciexamination_attribute_element_version" AS "";
TRUNCATE TABLE ophciexamination_attribute_option_version;
 SELECT "TRUNCATE TABLE ophciexamination_attribute_option_version" AS "";
TRUNCATE TABLE ophciexamination_attribute_version;
 SELECT "TRUNCATE TABLE ophciexamination_attribute_version" AS "";
TRUNCATE TABLE ophciexamination_bleb_assessment_central_area_version;
 SELECT "TRUNCATE TABLE ophciexamination_bleb_assessment_central_area_version" AS "";
TRUNCATE TABLE ophciexamination_bleb_assessment_height_version;
 SELECT "TRUNCATE TABLE ophciexamination_bleb_assessment_height_version" AS "";
TRUNCATE TABLE ophciexamination_bleb_assessment_max_area_version;
 SELECT "TRUNCATE TABLE ophciexamination_bleb_assessment_max_area_version" AS "";
TRUNCATE TABLE ophciexamination_bleb_assessment_vascularity_version;
 SELECT "TRUNCATE TABLE ophciexamination_bleb_assessment_vascularity_version" AS "";
TRUNCATE TABLE ophciexamination_cataractsurgicalmanagement_eye_version;
 SELECT "TRUNCATE TABLE ophciexamination_cataractsurgicalmanagement_eye_version" AS "";
TRUNCATE TABLE ophciexamination_cataractsurgicalmanagement_sfsurgeon_version;
 SELECT "TRUNCATE TABLE ophciexamination_cataractsurgicalmanagement_sfsurgeon_version" AS "";
TRUNCATE TABLE ophciexamination_clinicoutcome_role_version;
 SELECT "TRUNCATE TABLE ophciexamination_clinicoutcome_role_version" AS "";
TRUNCATE TABLE ophciexamination_clinicoutcome_status_options_version;
 SELECT "TRUNCATE TABLE ophciexamination_clinicoutcome_status_options_version" AS "";
TRUNCATE TABLE ophciexamination_clinicoutcome_status_version;
 SELECT "TRUNCATE TABLE ophciexamination_clinicoutcome_status_version" AS "";
TRUNCATE TABLE ophciexamination_clinicoutcome_template_version;
 SELECT "TRUNCATE TABLE ophciexamination_clinicoutcome_template_version" AS "";
TRUNCATE TABLE ophciexamination_colourvision_method_version;
 SELECT "TRUNCATE TABLE ophciexamination_colourvision_method_version" AS "";
TRUNCATE TABLE ophciexamination_colourvision_reading_version;
 SELECT "TRUNCATE TABLE ophciexamination_colourvision_reading_version" AS "";
TRUNCATE TABLE ophciexamination_colourvision_value_version;
 SELECT "TRUNCATE TABLE ophciexamination_colourvision_value_version" AS "";
TRUNCATE TABLE ophciexamination_comorbidities_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_comorbidities_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_comorbidities_item_options_version;
 SELECT "TRUNCATE TABLE ophciexamination_comorbidities_item_options_version" AS "";
TRUNCATE TABLE ophciexamination_comorbidities_item_version;
 SELECT "TRUNCATE TABLE ophciexamination_comorbidities_item_version" AS "";
TRUNCATE TABLE ophciexamination_cxl_cl_removed_version;
 SELECT "TRUNCATE TABLE ophciexamination_cxl_cl_removed_version" AS "";
TRUNCATE TABLE ophciexamination_cxl_ocular_surface_disease_version;
 SELECT "TRUNCATE TABLE ophciexamination_cxl_ocular_surface_disease_version" AS "";
TRUNCATE TABLE ophciexamination_cxl_outcome_diagnosis_version;
 SELECT "TRUNCATE TABLE ophciexamination_cxl_outcome_diagnosis_version" AS "";
TRUNCATE TABLE ophciexamination_cxl_outcome_version;
 SELECT "TRUNCATE TABLE ophciexamination_cxl_outcome_version" AS "";
TRUNCATE TABLE ophciexamination_cxl_quality_score_version;
 SELECT "TRUNCATE TABLE ophciexamination_cxl_quality_score_version" AS "";
TRUNCATE TABLE ophciexamination_diagnosis_version;
 SELECT "TRUNCATE TABLE ophciexamination_diagnosis_version" AS "";
TRUNCATE TABLE ophciexamination_dilation_drugs_version;
 SELECT "TRUNCATE TABLE ophciexamination_dilation_drugs_version" AS "";
TRUNCATE TABLE ophciexamination_dilation_treatment_version;
 SELECT "TRUNCATE TABLE ophciexamination_dilation_treatment_version" AS "";
TRUNCATE TABLE ophciexamination_drgrading_clinicalmaculopathy_version;
 SELECT "TRUNCATE TABLE ophciexamination_drgrading_clinicalmaculopathy_version" AS "";
TRUNCATE TABLE ophciexamination_drgrading_clinicalretinopathy_version;
 SELECT "TRUNCATE TABLE ophciexamination_drgrading_clinicalretinopathy_version" AS "";
TRUNCATE TABLE ophciexamination_drgrading_nscmaculopathy_version;
 SELECT "TRUNCATE TABLE ophciexamination_drgrading_nscmaculopathy_version" AS "";
TRUNCATE TABLE ophciexamination_drgrading_nscretinopathy_version;
 SELECT "TRUNCATE TABLE ophciexamination_drgrading_nscretinopathy_version" AS "";
TRUNCATE TABLE ophciexamination_element_set_item_version;
 SELECT "TRUNCATE TABLE ophciexamination_element_set_item_version" AS "";
TRUNCATE TABLE ophciexamination_element_set_version;
 SELECT "TRUNCATE TABLE ophciexamination_element_set_version" AS "";
TRUNCATE TABLE ophciexamination_event_elementset_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_event_elementset_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_familyhistory_condition_version;
 SELECT "TRUNCATE TABLE ophciexamination_familyhistory_condition_version" AS "";
TRUNCATE TABLE ophciexamination_familyhistory_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_familyhistory_entry_version" AS "";
TRUNCATE TABLE ophciexamination_familyhistory_relative_version;
 SELECT "TRUNCATE TABLE ophciexamination_familyhistory_relative_version" AS "";
TRUNCATE TABLE ophciexamination_familyhistory_side_version;
 SELECT "TRUNCATE TABLE ophciexamination_familyhistory_side_version" AS "";
TRUNCATE TABLE ophciexamination_further_findings_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_further_findings_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_glaucomarisk_risk_version;
 SELECT "TRUNCATE TABLE ophciexamination_glaucomarisk_risk_version" AS "";
TRUNCATE TABLE ophciexamination_gonioscopy_description_version;
 SELECT "TRUNCATE TABLE ophciexamination_gonioscopy_description_version" AS "";
TRUNCATE TABLE ophciexamination_history_medications_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_history_medications_entry_version" AS "";
TRUNCATE TABLE ophciexamination_history_risks_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_history_risks_entry_version" AS "";
TRUNCATE TABLE ophciexamination_injectmanagecomplex_answer_version;
 SELECT "TRUNCATE TABLE ophciexamination_injectmanagecomplex_answer_version" AS "";
TRUNCATE TABLE ophciexamination_injectmanagecomplex_notreatmentreason_version;
 SELECT "TRUNCATE TABLE ophciexamination_injectmanagecomplex_notreatmentreason_version" AS "";
TRUNCATE TABLE ophciexamination_injectmanagecomplex_question_version;
 SELECT "TRUNCATE TABLE ophciexamination_injectmanagecomplex_question_version" AS "";
TRUNCATE TABLE ophciexamination_injectmanagecomplex_risk_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_injectmanagecomplex_risk_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_injectmanagecomplex_risk_version;
 SELECT "TRUNCATE TABLE ophciexamination_injectmanagecomplex_risk_version" AS "";
TRUNCATE TABLE ophciexamination_instrument_version;
 SELECT "TRUNCATE TABLE ophciexamination_instrument_version" AS "";
TRUNCATE TABLE ophciexamination_intraocularpressure_reading_version;
 SELECT "TRUNCATE TABLE ophciexamination_intraocularpressure_reading_version" AS "";
TRUNCATE TABLE ophciexamination_intraocularpressure_value_version;
 SELECT "TRUNCATE TABLE ophciexamination_intraocularpressure_value_version" AS "";
TRUNCATE TABLE ophciexamination_lasermanagement_lasertype_version;
 SELECT "TRUNCATE TABLE ophciexamination_lasermanagement_lasertype_version" AS "";
TRUNCATE TABLE ophciexamination_management_deferralreason_version;
 SELECT "TRUNCATE TABLE ophciexamination_management_deferralreason_version" AS "";
TRUNCATE TABLE ophciexamination_management_status_version;
 SELECT "TRUNCATE TABLE ophciexamination_management_status_version" AS "";
TRUNCATE TABLE ophciexamination_managementdrops_version;
 SELECT "TRUNCATE TABLE ophciexamination_managementdrops_version" AS "";
TRUNCATE TABLE ophciexamination_managementglaucomastatus_version;
 SELECT "TRUNCATE TABLE ophciexamination_managementglaucomastatus_version" AS "";
TRUNCATE TABLE ophciexamination_managementrelproblem_version;
 SELECT "TRUNCATE TABLE ophciexamination_managementrelproblem_version" AS "";
TRUNCATE TABLE ophciexamination_managementsurgery_version;
 SELECT "TRUNCATE TABLE ophciexamination_managementsurgery_version" AS "";
TRUNCATE TABLE ophciexamination_medication_stop_reason_version;
 SELECT "TRUNCATE TABLE ophciexamination_medication_stop_reason_version" AS "";
TRUNCATE TABLE ophciexamination_nearvisualacuity_reading_version;
 SELECT "TRUNCATE TABLE ophciexamination_nearvisualacuity_reading_version" AS "";
TRUNCATE TABLE ophciexamination_oct_fluidstatus_version;
 SELECT "TRUNCATE TABLE ophciexamination_oct_fluidstatus_version" AS "";
TRUNCATE TABLE ophciexamination_oct_fluidtype_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_oct_fluidtype_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_oct_fluidtype_version;
 SELECT "TRUNCATE TABLE ophciexamination_oct_fluidtype_version" AS "";
TRUNCATE TABLE ophciexamination_oct_method_version;
 SELECT "TRUNCATE TABLE ophciexamination_oct_method_version" AS "";
TRUNCATE TABLE ophciexamination_opticdisc_cd_ratio_version;
 SELECT "TRUNCATE TABLE ophciexamination_opticdisc_cd_ratio_version" AS "";
TRUNCATE TABLE ophciexamination_opticdisc_lens_version;
 SELECT "TRUNCATE TABLE ophciexamination_opticdisc_lens_version" AS "";
TRUNCATE TABLE ophciexamination_overallperiod_version;
 SELECT "TRUNCATE TABLE ophciexamination_overallperiod_version" AS "";
TRUNCATE TABLE ophciexamination_pastsurgery_op_version;
 SELECT "TRUNCATE TABLE ophciexamination_pastsurgery_op_version" AS "";
TRUNCATE TABLE ophciexamination_postop_complications_subspecialty_version;
 SELECT "TRUNCATE TABLE ophciexamination_postop_complications_subspecialty_version" AS "";
TRUNCATE TABLE ophciexamination_postop_complications_version;
 SELECT "TRUNCATE TABLE ophciexamination_postop_complications_version" AS "";
TRUNCATE TABLE ophciexamination_postop_et_complications_version;
 SELECT "TRUNCATE TABLE ophciexamination_postop_et_complications_version" AS "";
TRUNCATE TABLE ophciexamination_primary_reason_for_surgery_version;
 SELECT "TRUNCATE TABLE ophciexamination_primary_reason_for_surgery_version" AS "";
TRUNCATE TABLE ophciexamination_pupillaryabnormalities_abnormality_version;
 SELECT "TRUNCATE TABLE ophciexamination_pupillaryabnormalities_abnormality_version" AS "";
TRUNCATE TABLE ophciexamination_qualitative_scale_value_version;
 SELECT "TRUNCATE TABLE ophciexamination_qualitative_scale_value_version" AS "";
TRUNCATE TABLE ophciexamination_qualitative_scale_version;
 SELECT "TRUNCATE TABLE ophciexamination_qualitative_scale_version" AS "";
TRUNCATE TABLE ophciexamination_refraction_cylinder_integer_version;
 SELECT "TRUNCATE TABLE ophciexamination_refraction_cylinder_integer_version" AS "";
TRUNCATE TABLE ophciexamination_refraction_fraction_version;
 SELECT "TRUNCATE TABLE ophciexamination_refraction_fraction_version" AS "";
TRUNCATE TABLE ophciexamination_refraction_sign_version;
 SELECT "TRUNCATE TABLE ophciexamination_refraction_sign_version" AS "";
TRUNCATE TABLE ophciexamination_refraction_sphere_integer_version;
 SELECT "TRUNCATE TABLE ophciexamination_refraction_sphere_integer_version" AS "";
TRUNCATE TABLE ophciexamination_refraction_type_version;
 SELECT "TRUNCATE TABLE ophciexamination_refraction_type_version" AS "";
TRUNCATE TABLE ophciexamination_risk_set_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_risk_set_entry_version" AS "";
TRUNCATE TABLE ophciexamination_risk_set_version;
 SELECT "TRUNCATE TABLE ophciexamination_risk_set_version" AS "";
TRUNCATE TABLE ophciexamination_risk_version;
 SELECT "TRUNCATE TABLE ophciexamination_risk_version" AS "";
TRUNCATE TABLE ophciexamination_scan_quality_version;
 SELECT "TRUNCATE TABLE ophciexamination_scan_quality_version" AS "";
TRUNCATE TABLE ophciexamination_slit_lamp_conditions_version;
 SELECT "TRUNCATE TABLE ophciexamination_slit_lamp_conditions_version" AS "";
TRUNCATE TABLE ophciexamination_slit_lamp_cornea_version;
 SELECT "TRUNCATE TABLE ophciexamination_slit_lamp_cornea_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_accommodation_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_accommodation_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_carer_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_carer_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_driving_status_assignment_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_driving_status_assignment_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_driving_status_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_driving_status_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_occupation_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_occupation_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_smoking_status_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_smoking_status_version" AS "";
TRUNCATE TABLE ophciexamination_socialhistory_substance_misuse_version;
 SELECT "TRUNCATE TABLE ophciexamination_socialhistory_substance_misuse_version" AS "";
TRUNCATE TABLE ophciexamination_specular_microscope_version;
 SELECT "TRUNCATE TABLE ophciexamination_specular_microscope_version" AS "";
TRUNCATE TABLE ophciexamination_surgical_history_set_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_surgical_history_set_entry_version" AS "";
TRUNCATE TABLE ophciexamination_surgical_history_set_version;
 SELECT "TRUNCATE TABLE ophciexamination_surgical_history_set_version" AS "";
TRUNCATE TABLE ophciexamination_systemic_diagnoses_diagnosis_version;
 SELECT "TRUNCATE TABLE ophciexamination_systemic_diagnoses_diagnosis_version" AS "";
TRUNCATE TABLE ophciexamination_systemic_diagnoses_req_diag_check_version;
 SELECT "TRUNCATE TABLE ophciexamination_systemic_diagnoses_req_diag_check_version" AS "";
TRUNCATE TABLE ophciexamination_systemic_diagnoses_set_entry_version;
 SELECT "TRUNCATE TABLE ophciexamination_systemic_diagnoses_set_entry_version" AS "";
TRUNCATE TABLE ophciexamination_systemic_diagnoses_set_version;
 SELECT "TRUNCATE TABLE ophciexamination_systemic_diagnoses_set_version" AS "";
TRUNCATE TABLE ophciexamination_targetiop_version;
 SELECT "TRUNCATE TABLE ophciexamination_targetiop_version" AS "";
TRUNCATE TABLE ophciexamination_tomographer_device_version;
 SELECT "TRUNCATE TABLE ophciexamination_tomographer_device_version" AS "";
TRUNCATE TABLE ophciexamination_topographer_device_version;
 SELECT "TRUNCATE TABLE ophciexamination_topographer_device_version" AS "";
TRUNCATE TABLE ophciexamination_van_herick_version;
 SELECT "TRUNCATE TABLE ophciexamination_van_herick_version" AS "";
TRUNCATE TABLE ophciexamination_visitinterval_version;
 SELECT "TRUNCATE TABLE ophciexamination_visitinterval_version" AS "";
TRUNCATE TABLE ophciexamination_visual_acuity_unit_value_version;
 SELECT "TRUNCATE TABLE ophciexamination_visual_acuity_unit_value_version" AS "";
TRUNCATE TABLE ophciexamination_visual_acuity_unit_version;
 SELECT "TRUNCATE TABLE ophciexamination_visual_acuity_unit_version" AS "";
TRUNCATE TABLE ophciexamination_visualacuity_method_version;
 SELECT "TRUNCATE TABLE ophciexamination_visualacuity_method_version" AS "";
TRUNCATE TABLE ophciexamination_visualacuity_reading_version;
 SELECT "TRUNCATE TABLE ophciexamination_visualacuity_reading_version" AS "";
TRUNCATE TABLE ophciexamination_workflow_rule_version;
 SELECT "TRUNCATE TABLE ophciexamination_workflow_rule_version" AS "";
TRUNCATE TABLE ophciexamination_workflow_version;
 SELECT "TRUNCATE TABLE ophciexamination_workflow_version" AS "";
TRUNCATE TABLE ophciphasing_instrument_version;
 SELECT "TRUNCATE TABLE ophciphasing_instrument_version" AS "";
TRUNCATE TABLE ophciphasing_reading_version;
 SELECT "TRUNCATE TABLE ophciphasing_reading_version" AS "";
TRUNCATE TABLE ophcocorrespondence_cbt_recipient_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_cbt_recipient_version" AS "";
TRUNCATE TABLE ophcocorrespondence_firm_letter_string_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_firm_letter_string_version" AS "";
TRUNCATE TABLE ophcocorrespondence_firm_site_secretary_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_firm_site_secretary_version" AS "";
TRUNCATE TABLE ophcocorrespondence_internal_referral_settings_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_internal_referral_settings_version" AS "";
TRUNCATE TABLE ophcocorrespondence_internal_referral_to_location_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_internal_referral_to_location_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_enclosure_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_enclosure_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_macro_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_macro_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_recipient_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_recipient_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_setting_value_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_setting_value_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_settings_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_settings_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_string_group_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_string_group_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_string_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_string_version" AS "";
TRUNCATE TABLE ophcocorrespondence_letter_type_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_letter_type_version" AS "";
TRUNCATE TABLE ophcocorrespondence_subspecialty_letter_string_version;
 SELECT "TRUNCATE TABLE ophcocorrespondence_subspecialty_letter_string_version" AS "";
TRUNCATE TABLE ophcocvi_clericinfo_contact_urgency_version;
 SELECT "TRUNCATE TABLE ophcocvi_clericinfo_contact_urgency_version" AS "";
TRUNCATE TABLE ophcocvi_clericinfo_employment_status_version;
 SELECT "TRUNCATE TABLE ophcocvi_clericinfo_employment_status_version" AS "";
TRUNCATE TABLE ophcocvi_clericinfo_patient_factor_answer_version;
 SELECT "TRUNCATE TABLE ophcocvi_clericinfo_patient_factor_answer_version" AS "";
TRUNCATE TABLE ophcocvi_clericinfo_patient_factor_version;
 SELECT "TRUNCATE TABLE ophcocvi_clericinfo_patient_factor_version" AS "";
TRUNCATE TABLE ophcocvi_clericinfo_preferred_info_fmt_version;
 SELECT "TRUNCATE TABLE ophcocvi_clericinfo_preferred_info_fmt_version" AS "";
TRUNCATE TABLE ophcocvi_clinicinfo_disorder_section_version;
 SELECT "TRUNCATE TABLE ophcocvi_clinicinfo_disorder_section_version" AS "";
TRUNCATE TABLE ophcocvi_clinicinfo_disorder_version;
 SELECT "TRUNCATE TABLE ophcocvi_clinicinfo_disorder_version" AS "";
TRUNCATE TABLE ophcocvi_clinicinfo_field_of_vision_version;
 SELECT "TRUNCATE TABLE ophcocvi_clinicinfo_field_of_vision_version" AS "";
TRUNCATE TABLE ophcocvi_clinicinfo_low_vision_status_version;
 SELECT "TRUNCATE TABLE ophcocvi_clinicinfo_low_vision_status_version" AS "";
TRUNCATE TABLE ophcodocument_sub_types_version;
 SELECT "TRUNCATE TABLE ophcodocument_sub_types_version" AS "";
TRUNCATE TABLE ophcomessaging_message_comment_version;
 SELECT "TRUNCATE TABLE ophcomessaging_message_comment_version" AS "";
TRUNCATE TABLE ophcomessaging_message_message_type_version;
 SELECT "TRUNCATE TABLE ophcomessaging_message_message_type_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontree_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontree_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontreenode_responsetype_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontreenode_responsetype_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontreenode_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontreenode_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontreenodechoice_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontreenodechoice_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontreenoderule_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontreenoderule_version" AS "";
TRUNCATE TABLE ophcotherapya_decisiontreeoutcome_version;
 SELECT "TRUNCATE TABLE ophcotherapya_decisiontreeoutcome_version" AS "";
TRUNCATE TABLE ophcotherapya_email_attachment_version;
 SELECT "TRUNCATE TABLE ophcotherapya_email_attachment_version" AS "";
TRUNCATE TABLE ophcotherapya_email_recipient_type_version;
 SELECT "TRUNCATE TABLE ophcotherapya_email_recipient_type_version" AS "";
TRUNCATE TABLE ophcotherapya_email_recipient_version;
 SELECT "TRUNCATE TABLE ophcotherapya_email_recipient_version" AS "";
TRUNCATE TABLE ophcotherapya_email_version;
 SELECT "TRUNCATE TABLE ophcotherapya_email_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_deviationreason_ass_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_deviationreason_ass_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_deviationreason_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_deviationreason_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_filecoll_assignment_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_filecoll_assignment_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_intervention_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_intervention_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_pastintervention_stopreason_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_pastintervention_stopreason_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_pastintervention_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_pastintervention_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_standardintervention_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_standardintervention_version" AS "";
TRUNCATE TABLE ophcotherapya_exceptional_startperiod_version;
 SELECT "TRUNCATE TABLE ophcotherapya_exceptional_startperiod_version" AS "";
TRUNCATE TABLE ophcotherapya_filecoll_assignment_version;
 SELECT "TRUNCATE TABLE ophcotherapya_filecoll_assignment_version" AS "";
TRUNCATE TABLE ophcotherapya_filecoll_version;
 SELECT "TRUNCATE TABLE ophcotherapya_filecoll_version" AS "";
TRUNCATE TABLE ophcotherapya_patientsuit_decisiontreenoderesponse_version;
 SELECT "TRUNCATE TABLE ophcotherapya_patientsuit_decisiontreenoderesponse_version" AS "";
TRUNCATE TABLE ophcotherapya_relevanttreatment_version;
 SELECT "TRUNCATE TABLE ophcotherapya_relevanttreatment_version" AS "";
TRUNCATE TABLE ophcotherapya_therapydisorder_version;
 SELECT "TRUNCATE TABLE ophcotherapya_therapydisorder_version" AS "";
TRUNCATE TABLE ophcotherapya_treatment_cost_type_version;
 SELECT "TRUNCATE TABLE ophcotherapya_treatment_cost_type_version" AS "";
TRUNCATE TABLE ophcotherapya_treatment_version;
 SELECT "TRUNCATE TABLE ophcotherapya_treatment_version" AS "";
TRUNCATE TABLE ophdrprescription_dispense_condition_assignment_version;
 SELECT "TRUNCATE TABLE ophdrprescription_dispense_condition_assignment_version" AS "";
TRUNCATE TABLE ophdrprescription_dispense_condition_version;
 SELECT "TRUNCATE TABLE ophdrprescription_dispense_condition_version" AS "";
TRUNCATE TABLE ophdrprescription_dispense_location_version;
 SELECT "TRUNCATE TABLE ophdrprescription_dispense_location_version" AS "";
TRUNCATE TABLE ophdrprescription_item_taper_version;
 SELECT "TRUNCATE TABLE ophdrprescription_item_taper_version" AS "";
TRUNCATE TABLE ophdrprescription_item_version;
 SELECT "TRUNCATE TABLE ophdrprescription_item_version" AS "";
TRUNCATE TABLE ophinbiometry_lenstype_lens_version;
 SELECT "TRUNCATE TABLE ophinbiometry_lenstype_lens_version" AS "";
TRUNCATE TABLE ophinlabresults_type_version;
 SELECT "TRUNCATE TABLE ophinlabresults_type_version" AS "";
TRUNCATE TABLE ophinvisualfields_condition_ability_version;
 SELECT "TRUNCATE TABLE ophinvisualfields_condition_ability_version" AS "";
TRUNCATE TABLE ophinvisualfields_field_measurement_version;
 SELECT "TRUNCATE TABLE ophinvisualfields_field_measurement_version" AS "";
TRUNCATE TABLE ophinvisualfields_pattern_version;
 SELECT "TRUNCATE TABLE ophinvisualfields_pattern_version" AS "";
TRUNCATE TABLE ophinvisualfields_result_assessment_version;
 SELECT "TRUNCATE TABLE ophinvisualfields_result_assessment_version" AS "";
TRUNCATE TABLE ophinvisualfields_strategy_version;
 SELECT "TRUNCATE TABLE ophinvisualfields_strategy_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_anaesthetist_lookup_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_anaesthetist_lookup_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_notes_ready_for_discharge_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_notes_ready_for_discharge_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_body_temp_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_body_temp_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_conscious_lvl_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_conscious_lvl_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_heart_rate_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_heart_rate_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_oxygen_saturation_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_oxygen_saturation_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_respiratory_rate_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_respiratory_rate_version" AS "";
TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_systolic_version;
 SELECT "TRUNCATE TABLE ophouanaestheticsataudit_vitalsigns_systolic_version" AS "";
TRUNCATE TABLE ophtrconsent_leaflet_firm_version;
 SELECT "TRUNCATE TABLE ophtrconsent_leaflet_firm_version" AS "";
TRUNCATE TABLE ophtrconsent_leaflet_subspecialty_version;
 SELECT "TRUNCATE TABLE ophtrconsent_leaflet_subspecialty_version" AS "";
TRUNCATE TABLE ophtrconsent_leaflet_version;
 SELECT "TRUNCATE TABLE ophtrconsent_leaflet_version" AS "";
TRUNCATE TABLE ophtrconsent_leaflets_version;
 SELECT "TRUNCATE TABLE ophtrconsent_leaflets_version" AS "";
TRUNCATE TABLE ophtrconsent_permissions_images_version;
 SELECT "TRUNCATE TABLE ophtrconsent_permissions_images_version" AS "";
TRUNCATE TABLE ophtrconsent_procedure_add_procs_add_procs_version;
 SELECT "TRUNCATE TABLE ophtrconsent_procedure_add_procs_add_procs_version" AS "";
TRUNCATE TABLE ophtrconsent_procedure_anaesthetic_type_version;
 SELECT "TRUNCATE TABLE ophtrconsent_procedure_anaesthetic_type_version" AS "";
TRUNCATE TABLE ophtrconsent_procedure_proc_defaults_version;
 SELECT "TRUNCATE TABLE ophtrconsent_procedure_proc_defaults_version" AS "";
TRUNCATE TABLE ophtrconsent_procedure_procedures_procedures_version;
 SELECT "TRUNCATE TABLE ophtrconsent_procedure_procedures_procedures_version" AS "";
TRUNCATE TABLE ophtrconsent_type_type_version;
 SELECT "TRUNCATE TABLE ophtrconsent_type_type_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_anaestheticagent_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_anaestheticagent_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_anaestheticdelivery_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_anaestheticdelivery_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_anaesthetictype_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_anaesthetictype_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_antiseptic_allergy_assignment_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_antiseptic_allergy_assignment_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_antiseptic_drug_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_antiseptic_drug_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_complicat_assignment_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_complicat_assignment_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_complicat_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_complicat_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_injectionuser_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_injectionuser_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_ioplowering_assign_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_ioplowering_assign_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_ioplowering_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_ioplowering_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_lens_status_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_lens_status_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_postinjection_drops_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_postinjection_drops_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_skin_drug_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_skin_drug_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_skindrug_allergy_assignment_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_skindrug_allergy_assignment_version" AS "";
TRUNCATE TABLE ophtrintravitinjection_treatment_drug_version;
 SELECT "TRUNCATE TABLE ophtrintravitinjection_treatment_drug_version" AS "";
TRUNCATE TABLE ophtrlaser_laser_operator_version;
 SELECT "TRUNCATE TABLE ophtrlaser_laser_operator_version" AS "";
TRUNCATE TABLE ophtrlaser_laserprocedure_assignment_version;
 SELECT "TRUNCATE TABLE ophtrlaser_laserprocedure_assignment_version" AS "";
TRUNCATE TABLE ophtrlaser_laserprocedure_version;
 SELECT "TRUNCATE TABLE ophtrlaser_laserprocedure_version" AS "";
TRUNCATE TABLE ophtrlaser_site_laser_version;
 SELECT "TRUNCATE TABLE ophtrlaser_site_laser_version" AS "";
TRUNCATE TABLE ophtrlaser_type_version;
 SELECT "TRUNCATE TABLE ophtrlaser_type_version" AS "";
TRUNCATE TABLE ophtroperationbooking_admission_letter_warning_rule_type_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_admission_letter_warning_rule_type_version" AS "";
TRUNCATE TABLE ophtroperationbooking_admission_letter_warning_rule_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_admission_letter_warning_rule_version" AS "";
TRUNCATE TABLE ophtroperationbooking_anaesthetic_anaesthetic_type_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_anaesthetic_anaesthetic_type_version" AS "";
TRUNCATE TABLE ophtroperationbooking_letter_contact_rule_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_letter_contact_rule_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_booking_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_booking_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_cancellation_reason_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_cancellation_reason_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_date_letter_sent_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_date_letter_sent_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_erod_rule_item_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_erod_rule_item_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_erod_rule_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_erod_rule_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_erod_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_erod_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_name_rule_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_name_rule_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_priority_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_priority_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_procedures_procedures_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_procedures_procedures_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_sequence_interval_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_sequence_interval_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_sequence_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_sequence_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_session_unavailreason_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_session_unavailreason_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_session_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_session_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_status_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_status_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_theatre_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_theatre_version" AS "";
TRUNCATE TABLE ophtroperationbooking_operation_ward_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_operation_ward_version" AS "";
TRUNCATE TABLE ophtroperationbooking_scheduleope_patientunavail_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_scheduleope_patientunavail_version" AS "";
TRUNCATE TABLE ophtroperationbooking_scheduleope_patientunavailreason_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_scheduleope_patientunavailreason_version" AS "";
TRUNCATE TABLE ophtroperationbooking_scheduleope_schedule_options_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_scheduleope_schedule_options_version" AS "";
TRUNCATE TABLE ophtroperationbooking_waiting_list_contact_rule_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_waiting_list_contact_rule_version" AS "";
TRUNCATE TABLE ophtroperationbooking_whiteboard_settings_data_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_whiteboard_settings_data_version" AS "";
TRUNCATE TABLE ophtroperationbooking_whiteboard_settings_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_whiteboard_settings_version" AS "";
TRUNCATE TABLE ophtroperationbooking_whiteboard_version;
 SELECT "TRUNCATE TABLE ophtroperationbooking_whiteboard_version" AS "";
TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_agent_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_agent_version" AS "";
TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_complication_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_complication_version" AS "";
TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_complications_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_complications_version" AS "";
TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_delivery_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_delivery_version" AS "";
TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_anaesthetic_anaesthetic_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_antimetabolite_application_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_antimetabolite_application_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_buckle_drainage_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_buckle_drainage_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_complication_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_complication_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_complications_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_complications_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_incision_length_default_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_incision_length_default_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_incision_site_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_incision_site_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_incision_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_incision_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_iol_position_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_iol_position_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_iol_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_iol_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_cataract_operative_device_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cataract_operative_device_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_complications_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_complications_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_devices_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_devices_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_epithelial_removal_diameter_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_epithelial_removal_diameter_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_epithelial_removal_method_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_epithelial_removal_method_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_epithelial_status_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_epithelial_status_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_interpulse_duration_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_interpulse_duration_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_interval_between_drops_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_interval_between_drops_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_iontophoresis_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_iontophoresis_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_mitomycin_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_mitomycin_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_protocol_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_protocol_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_riboflavin_preparation_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_riboflavin_preparation_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_soak_duration_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_soak_duration_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_total_exposure_time_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_total_exposure_time_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_uv_irradiance_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_uv_irradiance_version" AS "";
TRUNCATE TABLE ophtroperationnote_cxl_uv_pulse_duration_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_cxl_uv_pulse_duration_version" AS "";
TRUNCATE TABLE ophtroperationnote_gas_percentage_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gas_percentage_version" AS "";
TRUNCATE TABLE ophtroperationnote_gas_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gas_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_gas_volume_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gas_volume_version" AS "";
TRUNCATE TABLE ophtroperationnote_gauge_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gauge_version" AS "";
TRUNCATE TABLE ophtroperationnote_gt_plateposition_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gt_plateposition_version" AS "";
TRUNCATE TABLE ophtroperationnote_gt_tubeposition_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_gt_tubeposition_version" AS "";
TRUNCATE TABLE ophtroperationnote_mmc_concentration_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_mmc_concentration_version" AS "";
TRUNCATE TABLE ophtroperationnote_mmc_volume_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_mmc_volume_version" AS "";
TRUNCATE TABLE ophtroperationnote_postop_drug_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_postop_drug_version" AS "";
TRUNCATE TABLE ophtroperationnote_postop_drugs_drug_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_postop_drugs_drug_version" AS "";
TRUNCATE TABLE ophtroperationnote_postop_site_subspecialty_drug_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_postop_site_subspecialty_drug_version" AS "";
TRUNCATE TABLE ophtroperationnote_procedure_element_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_procedure_element_version" AS "";
TRUNCATE TABLE ophtroperationnote_procedurelist_procedure_assignment_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_procedurelist_procedure_assignment_version" AS "";
TRUNCATE TABLE ophtroperationnote_site_subspecialty_postop_instructions_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_site_subspecialty_postop_instructions_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabectome_comp_ass_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabectome_comp_ass_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabectome_complication_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabectome_complication_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabectome_power_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabectome_power_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_complication_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_complication_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_complications_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_complications_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_conjunctival_flap_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_conjunctival_flap_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_difficulties_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_difficulties_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_difficulty_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_difficulty_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_sclerostomy_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_sclerostomy_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_site_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_site_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_size_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_size_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_viscoelastic_flow_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_viscoelastic_flow_version" AS "";
TRUNCATE TABLE ophtroperationnote_trabeculectomy_viscoelastic_type_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_trabeculectomy_viscoelastic_type_version" AS "";
TRUNCATE TABLE ophtroperationnote_vte_assessment_option_version;
 SELECT "TRUNCATE TABLE ophtroperationnote_vte_assessment_option_version" AS "";
TRUNCATE TABLE pas_patient_merged_version;
 SELECT "TRUNCATE TABLE pas_patient_merged_version" AS "";
TRUNCATE TABLE pasapi_remap_value_version;
 SELECT "TRUNCATE TABLE pasapi_remap_value_version" AS "";
TRUNCATE TABLE pasapi_xpath_remap_version;
 SELECT "TRUNCATE TABLE pasapi_xpath_remap_version" AS "";
TRUNCATE TABLE patient_contact_assignment_version;
 SELECT "TRUNCATE TABLE patient_contact_assignment_version" AS "";
TRUNCATE TABLE patient_contact_associate_version;
 SELECT "TRUNCATE TABLE patient_contact_associate_version" AS "";
TRUNCATE TABLE patient_identifier_version;
 SELECT "TRUNCATE TABLE patient_identifier_version" AS "";
TRUNCATE TABLE patient_measurement_version;
 SELECT "TRUNCATE TABLE patient_measurement_version" AS "";
TRUNCATE TABLE patient_merge_request_version;
 SELECT "TRUNCATE TABLE patient_merge_request_version" AS "";
TRUNCATE TABLE patient_oph_info_cvi_status_version;
 SELECT "TRUNCATE TABLE patient_oph_info_cvi_status_version" AS "";
TRUNCATE TABLE patient_oph_info_version;
 SELECT "TRUNCATE TABLE patient_oph_info_version" AS "";
TRUNCATE TABLE patient_shortcode_version;
 SELECT "TRUNCATE TABLE patient_shortcode_version" AS "";
TRUNCATE TABLE patient_user_referral_version;
 SELECT "TRUNCATE TABLE patient_user_referral_version" AS "";
TRUNCATE TABLE patient_version;
 SELECT "TRUNCATE TABLE patient_version" AS "";
TRUNCATE TABLE patientticketing_clinic_location_version;
 SELECT "TRUNCATE TABLE patientticketing_clinic_location_version" AS "";
TRUNCATE TABLE patientticketing_priority_version;
 SELECT "TRUNCATE TABLE patientticketing_priority_version" AS "";
TRUNCATE TABLE patientticketing_queue_event_type_version;
 SELECT "TRUNCATE TABLE patientticketing_queue_event_type_version" AS "";
TRUNCATE TABLE patientticketing_queue_version;
 SELECT "TRUNCATE TABLE patientticketing_queue_version" AS "";
TRUNCATE TABLE patientticketing_queueoutcome_version;
 SELECT "TRUNCATE TABLE patientticketing_queueoutcome_version" AS "";
TRUNCATE TABLE patientticketing_queueset_version;
 SELECT "TRUNCATE TABLE patientticketing_queueset_version" AS "";
TRUNCATE TABLE patientticketing_queuesetcategory_version;
 SELECT "TRUNCATE TABLE patientticketing_queuesetcategory_version" AS "";
TRUNCATE TABLE patientticketing_ticket_version;
 SELECT "TRUNCATE TABLE patientticketing_ticket_version" AS "";
TRUNCATE TABLE patientticketing_ticketassignoutcomeoption_version;
 SELECT "TRUNCATE TABLE patientticketing_ticketassignoutcomeoption_version" AS "";
TRUNCATE TABLE patientticketing_ticketqueue_assignment_version;
 SELECT "TRUNCATE TABLE patientticketing_ticketqueue_assignment_version" AS "";
TRUNCATE TABLE pcr_risk_values_version;
 SELECT "TRUNCATE TABLE pcr_risk_values_version" AS "";
TRUNCATE TABLE pdf_footer_tag_version;
 SELECT "TRUNCATE TABLE pdf_footer_tag_version" AS "";
TRUNCATE TABLE period_version;
 SELECT "TRUNCATE TABLE period_version" AS "";
TRUNCATE TABLE person_version;
 SELECT "TRUNCATE TABLE person_version" AS "";
TRUNCATE TABLE practice_version;
 SELECT "TRUNCATE TABLE practice_version" AS "";
TRUNCATE TABLE priority_version;
 SELECT "TRUNCATE TABLE priority_version" AS "";
TRUNCATE TABLE proc_opcs_assignment_version;
 SELECT "TRUNCATE TABLE proc_opcs_assignment_version" AS "";
TRUNCATE TABLE proc_subspecialty_assignment_version;
 SELECT "TRUNCATE TABLE proc_subspecialty_assignment_version" AS "";
TRUNCATE TABLE proc_subspecialty_subsection_assignment_version;
 SELECT "TRUNCATE TABLE proc_subspecialty_subsection_assignment_version" AS "";
TRUNCATE TABLE proc_version;
 SELECT "TRUNCATE TABLE proc_version" AS "";
TRUNCATE TABLE procedure_additional_version;
 SELECT "TRUNCATE TABLE procedure_additional_version" AS "";
TRUNCATE TABLE procedure_benefit_version;
 SELECT "TRUNCATE TABLE procedure_benefit_version" AS "";
TRUNCATE TABLE procedure_complication_version;
 SELECT "TRUNCATE TABLE procedure_complication_version" AS "";
TRUNCATE TABLE protected_file_version;
 SELECT "TRUNCATE TABLE protected_file_version" AS "";
TRUNCATE TABLE referral_episode_assignment_version;
 SELECT "TRUNCATE TABLE referral_episode_assignment_version" AS "";
TRUNCATE TABLE referral_type_version;
 SELECT "TRUNCATE TABLE referral_type_version" AS "";
TRUNCATE TABLE referral_version;
 SELECT "TRUNCATE TABLE referral_version" AS "";
TRUNCATE TABLE rtt_version;
 SELECT "TRUNCATE TABLE rtt_version" AS "";
TRUNCATE TABLE secondary_diagnosis_not_present_version;
 SELECT "TRUNCATE TABLE secondary_diagnosis_not_present_version" AS "";
TRUNCATE TABLE secondary_diagnosis_version;
 SELECT "TRUNCATE TABLE secondary_diagnosis_version" AS "";
TRUNCATE TABLE secondaryto_common_oph_disorder_version;
 SELECT "TRUNCATE TABLE secondaryto_common_oph_disorder_version" AS "";
TRUNCATE TABLE service_subspecialty_assignment_version;
 SELECT "TRUNCATE TABLE service_subspecialty_assignment_version" AS "";
TRUNCATE TABLE service_version;
 SELECT "TRUNCATE TABLE service_version" AS "";
TRUNCATE TABLE setting_field_type_version;
 SELECT "TRUNCATE TABLE setting_field_type_version" AS "";
TRUNCATE TABLE setting_firm_version;
 SELECT "TRUNCATE TABLE setting_firm_version" AS "";
TRUNCATE TABLE setting_installation_version;
 SELECT "TRUNCATE TABLE setting_installation_version" AS "";
TRUNCATE TABLE setting_institution_version;
 SELECT "TRUNCATE TABLE setting_institution_version" AS "";
TRUNCATE TABLE setting_internal_referral_version;
 SELECT "TRUNCATE TABLE setting_internal_referral_version" AS "";
TRUNCATE TABLE setting_metadata_version;
 SELECT "TRUNCATE TABLE setting_metadata_version" AS "";
TRUNCATE TABLE setting_site_version;
 SELECT "TRUNCATE TABLE setting_site_version" AS "";
TRUNCATE TABLE setting_specialty_version;
 SELECT "TRUNCATE TABLE setting_specialty_version" AS "";
TRUNCATE TABLE setting_subspecialty_version;
 SELECT "TRUNCATE TABLE setting_subspecialty_version" AS "";
TRUNCATE TABLE setting_user_version;
 SELECT "TRUNCATE TABLE setting_user_version" AS "";
TRUNCATE TABLE site_subspecialty_anaesthetic_agent_default_version;
 SELECT "TRUNCATE TABLE site_subspecialty_anaesthetic_agent_default_version" AS "";
TRUNCATE TABLE site_subspecialty_anaesthetic_agent_version;
 SELECT "TRUNCATE TABLE site_subspecialty_anaesthetic_agent_version" AS "";
TRUNCATE TABLE site_subspecialty_drug_version;
 SELECT "TRUNCATE TABLE site_subspecialty_drug_version" AS "";
TRUNCATE TABLE site_subspecialty_operative_device_version;
 SELECT "TRUNCATE TABLE site_subspecialty_operative_device_version" AS "";
TRUNCATE TABLE site_version;
 SELECT "TRUNCATE TABLE site_version" AS "";
TRUNCATE TABLE specialty_type_version;
 SELECT "TRUNCATE TABLE specialty_type_version" AS "";
TRUNCATE TABLE specialty_version;
 SELECT "TRUNCATE TABLE specialty_version" AS "";
TRUNCATE TABLE subspecialty_subsection_version;
 SELECT "TRUNCATE TABLE subspecialty_subsection_version" AS "";
TRUNCATE TABLE subspecialty_version;
 SELECT "TRUNCATE TABLE subspecialty_version" AS "";
TRUNCATE TABLE tag_version;
 SELECT "TRUNCATE TABLE tag_version" AS "";
TRUNCATE TABLE trial_patient_version;
 SELECT "TRUNCATE TABLE trial_patient_version" AS "";
TRUNCATE TABLE trial_version;
 SELECT "TRUNCATE TABLE trial_version" AS "";
TRUNCATE TABLE unique_codes_mapping_version;
 SELECT "TRUNCATE TABLE unique_codes_mapping_version" AS "";
TRUNCATE TABLE unique_codes_version;
 SELECT "TRUNCATE TABLE unique_codes_version" AS "";
TRUNCATE TABLE user_firm_preference_version;
 SELECT "TRUNCATE TABLE user_firm_preference_version" AS "";
TRUNCATE TABLE user_firm_rights_version;
 SELECT "TRUNCATE TABLE user_firm_rights_version" AS "";
TRUNCATE TABLE user_firm_version;
 SELECT "TRUNCATE TABLE user_firm_version" AS "";
TRUNCATE TABLE user_hotlist_item_version;
 SELECT "TRUNCATE TABLE user_hotlist_item_version" AS "";
TRUNCATE TABLE user_service_rights_version;
 SELECT "TRUNCATE TABLE user_service_rights_version" AS "";
TRUNCATE TABLE user_site_version;
 SELECT "TRUNCATE TABLE user_site_version" AS "";
TRUNCATE TABLE user_trial_assignment_version;
 SELECT "TRUNCATE TABLE user_trial_assignment_version" AS "";
TRUNCATE TABLE user_version;
 SELECT "TRUNCATE TABLE user_version" AS "";
TRUNCATE TABLE worklist_definition_version;
 SELECT "TRUNCATE TABLE worklist_definition_version" AS "";
TRUNCATE TABLE worklist_patient_attribute_version;
 SELECT "TRUNCATE TABLE worklist_patient_attribute_version" AS "";
TRUNCATE TABLE worklist_patient_version;
 SELECT "TRUNCATE TABLE worklist_patient_version" AS "";
TRUNCATE TABLE worklist_version;
 SELECT "TRUNCATE TABLE worklist_version" AS "";

/*enable foreign key check again*/
SET FOREIGN_KEY_CHECKS = 1;
