---
openeyes:
  mysql_root_password: "across-health"
  mysql_host: "127.0.0.1"
  mysql_port: "3306"
  mysql_user: "openeyes"
  mysql_pass: "openeyes"
  mysql_databases: [ openeyes, openeyes_test ]
 # mysql_dump: "/var/www/openeyes/features/vagrant_openeyes.sql"
  mysql_dump: "/var/www/openeyes/protected/modules/sample/sql/openeyes_sample_data.sql"
  vendor_repo: [ "openeyes/vendor" ]
  modules: [ eyedraw, sample ]

server:
  timezone: Europe/London
  locale: en_US.UTF-8
  vagrant_user_password: "vagrant"
  packages: [ build-essential, linux-image-generic-lts-xenial, linux-generic-lts-xenial, curl, git, sendmail-bin, vim, default-jre, openjdk-7-jdk, ant, libbatik-java, libmysql-java, ruby-full, rubygems-integration, libreoffice-core, libreoffice-common, libreoffice-writer ]
vagrant_local:
    vm: { hostname: openeyes.vm }

environment_config:
  DATABASE_NAME: openeyes
  DATABASE_HOST: "{{ openeyes.mysql_host }}"
  DATABASE_PORT: "{{ openeyes.mysql_port }}"
  DATABASE_USER: "{{ openeyes.mysql_user }}"
  DATABASE_PASS: "{{ openeyes.mysql_pass }}"
  DATABASE_TEST_NAME: openeyes_test
  DATABASE_TEST_HOST: "{{ openeyes.mysql_host }}"
  DATABASE_TEST_PORT: "{{ openeyes.mysql_port }}"
  DATABASE_TEST_USER: "{{ openeyes.mysql_user }}"
  DATABASE_TEST_PASS: "{{ openeyes.mysql_pass }}"

# https://github.com/geerlingguy/ansible-role-apache
apache_remove_default_vhost: true
apache_create_vhosts: true
apache_vhosts_filename: "010-openeyes.conf"
apache_vhosts:
  - servername: "openeyes.vm"
    documentroot: "/var/www/openeyes"
    extra_parameters: |
      SetEnv DATABASE_NAME openeyes
      SetEnv DATABASE_HOST "{{ openeyes.mysql_host }}"
      SetEnv DATABASE_PORT "{{ openeyes.mysql_port }}"
      SetEnv DATABASE_USER "{{ openeyes.mysql_user }}"
      SetEnv DATABASE_PASS "{{ openeyes.mysql_pass }}"
      SetEnv DATABASE_TEST_NAME openeyes_test
      SetEnv DATABASE_TEST_HOST "{{ openeyes.mysql_host }}"
      SetEnv DATABASE_TEST_PORT "{{ openeyes.mysql_port }}"
      SetEnv DATABASE_TEST_USER "{{ openeyes.mysql_user }}"
      SetEnv DATABASE_TEST_PASS "{{ openeyes.mysql_pass }}"
apache_mods_enabled:
  - rewrite.load

# https://github.com/geerlingguy/ansible-role-mysql
mysql_root_password: "{{ openeyes.mysql_root_password }}"
mysql_port: "{{ openeyes.mysql_port }}"
mysql_bind_address: '0.0.0.0'
mysql_log_error: /var/log/mysqld.log
mysql_datadir: /var/lib/mysql
mysql_lower_case_table_names: 1
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
mysql_databases:
  - name: openeyes
  - name: openeyes_test
mysql_users:
  - name: "{{ openeyes.mysql_user }}"
    host: "%"
    password: "{{ openeyes.mysql_pass }}"
    priv: "*.*:ALL"

# https://github.com/geerlingguy/ansible-role-nodejs
nodejs_version: "6.x"
nodejs_install_npm_user: "vagrant"
nodejs_npm_global_packages:
  - name: bower
  - name: grunt
  - name: grunt-cli

# https://github.com/geerlingguy/ansible-role-php
php_webserver_daemon: "apache2"
php_use_managed_ini: true
php_date_timezone: "Europe/London"
php_memory_limit: "512M"
php_error_reporting: "E_ALL"
php_display_errors: "On"
php_display_startup_errors: "On"

# http://docs.drupalvm.com/en/latest/other/php-56/
# PHP 5.6 Packages and config start
php_version: "5.6"
php_opcache_enable: false
php_enable_apc: false
php_packages:
  - libapache2-mod-php5
  - php5-cli
  - php5-dev
  - php5-intl
  - php5-mcrypt
  - php5-curl
  - php5-imagick
  - php5-gd
  - imagemagick
  - php5-mysql
  - php5-xsl
php_conf_paths:
  - /etc/php5/fpm
  - /etc/php5/apache2
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/fpm/conf.d
  - /etc/php5/apache2/conf.d
  - /etc/php5/cli/conf.d
# PHP 5.6 Packages and config end

# PHP 7.0 Packages and config start
# php_version: "7.0"
# php_xdebug:
#   - php7-xdebug
# PHP 7.0 Packages and config end

# https://github.com/geerlingguy/ansible-role-php-xdebug
php_xdebug_default_enable: true
php_xdebug_coverage_enable: true
php_xdebug_cli_enable: false
php_xdebug_remote_enable: true
php_xdebug_remote_connect_back: true
php_xdebug_remote_port: "9000"
php_xdebug_idekey: across-health.xdebug
php_xdebug_remote_log: /tmp/xdebug.log # Useful for connection debug

# zealot128.wkhtmltox
wkhtmltox_download_url: 'https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/{{wkhtmltox_main_version}}/wkhtmltox-{{wkhtmltox_minor_version}}_linux-generic-amd64.tar.xz'
