name         'p0deje-display'
version      '0.3.1'
source       'git://github.com/p0deje/puppet-display.git'
author       'Alex Rodionov'
description  'Puppet module which sets up Xvfb + x11vnc as remote display'
summary      'Puppet module which sets up Xvfb + x11vnc as remote display'
license      'Apache License, Version 2.0'
project_page 'https://github.com/p0deje/puppet-display'

dependency 'puppetlabs/concat'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
