<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:14.
 */
class BaseEventTypeElementTest extends PHPUnit_Framework_TestCase {

                       /**
                        * @var BaseEventTypeElement
                        */
                       protected $object;

                       /**
                        * Sets up the fixture, for example, opens a network connection.
                        * This method is called before a test is executed.
                        */
                       protected function setUp() {
                                              $this->object = new BaseEventTypeElement;
                       }

                       /**
                        * Tears down the fixture, for example, closes a network connection.
                        * This method is called after a test is executed.
                        */
                       protected function tearDown() {
                                              
                       }

                       /**
                        * @covers BaseEventTypeElement::getElementType
                        * @todo   Implement testGetElementType().
                        */
                       public function testGetElementType() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::canCopy
                        * @todo   Implement testCanCopy().
                        */
                       public function testCanCopy() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getChildren
                        * @todo   Implement testGetChildren().
                        */
                       public function testGetChildren() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::loadFromExisting
                        * @todo   Implement testLoadFromExisting().
                        */
                       public function testLoadFromExisting() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::render
                        * @todo   Implement testRender().
                        */
                       public function testRender() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getFormOptions
                        * @todo   Implement testGetFormOptions().
                        */
                       public function testGetFormOptions() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getSetting
                        * @todo   Implement testGetSetting().
                        */
                       public function testGetSetting() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::parseSetting
                        * @todo   Implement testParseSetting().
                        */
                       public function testParseSetting() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::setBaseOptions
                        * @todo   Implement testSetBaseOptions().
                        */
                       public function testSetBaseOptions() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getPhraseBySubspecialtyOptions
                        * @todo   Implement testGetPhraseBySubspecialtyOptions().
                        */
                       public function testGetPhraseBySubspecialtyOptions() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::setDefaultOptions
                        * @todo   Implement testSetDefaultOptions().
                        */
                       public function testSetDefaultOptions() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::setUpdateOptions
                        * @todo   Implement testSetUpdateOptions().
                        */
                       public function testSetUpdateOptions() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getInfoText
                        * @todo   Implement testGetInfoText().
                        */
                       public function testGetInfoText() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getDefaultView
                        * @todo   Implement testGetDefaultView().
                        */
                       public function testGetDefaultView() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getCreate_view
                        * @todo   Implement testGetCreate_view().
                        */
                       public function testGetCreate_view() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getUpdate_view
                        * @todo   Implement testGetUpdate_view().
                        */
                       public function testGetUpdate_view() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getView_view
                        * @todo   Implement testGetView_view().
                        */
                       public function testGetView_view() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::getPrint_view
                        * @todo   Implement testGetPrint_view().
                        */
                       public function testGetPrint_view() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::isEditable
                        * @todo   Implement testIsEditable().
                        */
                       public function testIsEditable() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

                       /**
                        * @covers BaseEventTypeElement::requiredIfSide
                        * @todo   Implement testRequiredIfSide().
                        */
                       public function testRequiredIfSide() {
                                              // Remove the following lines when you implement this test.
                                              $this->markTestIncomplete(
                                                        'This test has not been implemented yet.'
                                              );
                       }

}
