<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:16.
 */
class EpisodeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Episode
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Episode;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Episode::model
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::tableName
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::defaultScope
     * @todo   Implement testDefaultScope().
     */
    public function testDefaultScope()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::rules
     * @todo   Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::relations
     * @todo   Implement testRelations().
     */
    public function testRelations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::attributeLabels
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::search
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::hasEventOfType
     * @todo   Implement testHasEventOfType().
     */
    public function testHasEventOfType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getBySubspecialtyAndPatient
     * @todo   Implement testGetBySubspecialtyAndPatient().
     */
    public function testGetBySubspecialtyAndPatient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getPrincipalDiagnosisDisorderTerm
     * @todo   Implement testGetPrincipalDiagnosisDisorderTerm().
     */
    public function testGetPrincipalDiagnosisDisorderTerm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getCurrentEpisodeByFirm
     * @todo   Implement testGetCurrentEpisodeByFirm().
     */
    public function testGetCurrentEpisodeByFirm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getMostRecentEventByType
     * @todo   Implement testGetMostRecentEventByType().
     */
    public function testGetMostRecentEventByType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getAllEventsByType
     * @todo   Implement testGetAllEventsByType().
     */
    public function testGetAllEventsByType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getHidden
     * @todo   Implement testGetHidden().
     */
    public function testGetHidden()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getOpen
     * @todo   Implement testGetOpen().
     */
    public function testGetOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::getEditable
     * @todo   Implement testGetEditable().
     */
    public function testGetEditable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::setPrincipalDiagnosis
     * @todo   Implement testSetPrincipalDiagnosis().
     */
    public function testSetPrincipalDiagnosis()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Episode::audit
     * @todo   Implement testAudit().
     */
    public function testAudit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
