---
- name: OpenEyes Development Server

  hosts: all

  become: true
  become_method: sudo

  vars_files:
    - vars/all.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    - server
    - vagrant_local
    - franklinkim.environment
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.nodejs
    - geerlingguy.php
    - geerlingguy.php-xdebug
    - geerlingguy.composer
    - zealot128.wkhtmltox
    - app
