<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-06 at 17:16:13.
 */
class 
{
    /**
     * @todo Implement queryAll().
     */
    public function queryAll()
    {
        // Remove the following line when you implement this method.
        throw new RuntimeException('Not yet implemented.');
    }
}
