name: Publish Docker image

on:
  push:
    branches:
      - "master"
      - "main"
      - "develop"
      - "release/*"
      - "bugfix/*"
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        # git clone from OEImageBuilder - will need SSH configuring

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker metadata tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: toukanlabsdocker/rtf
          # Only apply the latest tag to the master branch for the primary image
          flavor: |
            latest=${{ contains(github.ref,'refs/heads/master') }}
          # set tags to symantic versions for each release.
          # NOTE: for semver, the tag must contain 3x parts 1.2.3 (e.g v4.1.0)
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern==v{{major}}
            type=edge,branch=develop
    # Build each image in order, except for base image - which can be built separately in the OEBuilder repo
      - name: Build and push production image
        uses: docker/build-push-action@v2
        with:
          context: ./Web-Live # Need to get remote docker file
          push: true
          build-args: # Add build args
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push DB Bootstrap image
        uses: docker/build-push-action@v2
        with:
          context: ./DBBootstrap # Need to get remote docker file
          push: true
          build-args: # Add build args
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push develop image
        uses: docker/build-push-action@v2
        with:
          context: ./Web-Live # Need to get remote docker file
          push: true
          # Add build args
          build-args:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push CI Test image
        uses: docker/build-push-action@v2
        with:
          context: ./Web-Live # Need to get remote docker file
          push: true
          build-args: # Add build args
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      
# description will need updating for each folder
  # update-docker-hub-description:
  #   name: Update docker hub description
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v2

  #     - name: Docker Hub Description
  #       uses: peter-evans/dockerhub-description@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: toukanlabsdocker/rtf
