name: PHPStan

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: 'plaintext'
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
          php_extensions: gd, mbstring, ext-soap, imagick, intl, ldap, mbstring, mysql, soap, xsl, zip  # comma separated list of extensions

      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          path: ${{ steps.files.outputs.files }}
          level: 0
          php_version: 8.0