<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:17.
 */
class PatientContactAssignmentTest extends PHPUnit_Framework_TestCase
{
    /**
       * @var PatientContactAssignment
       */
      protected $object;

      /**
       * Sets up the fixture, for example, opens a network connection.
       * This method is called before a test is executed.
       */
      protected function setUp()
      {
          $this->object = new PatientContactAssignment();
      }

      /**
       * Tears down the fixture, for example, closes a network connection.
       * This method is called after a test is executed.
       */
      protected function tearDown()
      {
      }

      /**
       * @covers PatientContactAssignment::model
       *
       * @todo   Implement testModel().
       */
      public function testModel()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::tableName
       *
       * @todo   Implement testTableName().
       */
      public function testTableName()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::rules
       *
       * @todo   Implement testRules().
       */
      public function testRules()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::relations
       *
       * @todo   Implement testRelations().
       */
      public function testRelations()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::attributeLabels
       *
       * @todo   Implement testAttributeLabels().
       */
      public function testAttributeLabels()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::search
       *
       * @todo   Implement testSearch().
       */
      public function testSearch()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }

      /**
       * @covers PatientContactAssignment::getAddress
       *
       * @todo   Implement testGetAddress().
       */
      public function testGetAddress()
      {
          // Remove the following lines when you implement this test.
            $this->markTestIncomplete(
                      'This test has not been implemented yet.'
            );
      }
}
