<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:20.
 */
class SplitEventTypeElementTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SplitEventTypeElement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SplitEventTypeElement;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SplitEventTypeElement::hasLeft
     * @todo   Implement testHasLeft().
     */
    public function testHasLeft()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SplitEventTypeElement::hasRight
     * @todo   Implement testHasRight().
     */
    public function testHasRight()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SplitEventTypeElement::sidedFields
     * @todo   Implement testSidedFields().
     */
    public function testSidedFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SplitEventTypeElement::sidedDefaults
     * @todo   Implement testSidedDefaults().
     */
    public function testSidedDefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SplitEventTypeElement::setDefaultOptions
     * @todo   Implement testSetDefaultOptions().
     */
    public function testSetDefaultOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SplitEventTypeElement::setUpdateOptions
     * @todo   Implement testSetUpdateOptions().
     */
    public function testSetUpdateOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
